"use client";
import {FormEvent,useEffect,useMemo,useState,type ReactNode} from "react";
import {useRouter} from "next/navigation";
import {createDealControlled,getDealFormLookups,type NewDealInput} from "@/lib/deal-control";
const input="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500";
const initial:NewDealInput={customer_id:"",supplier_id:null,commodity:"",origin_country:"",destination_country:"",incoterm:"FOB",quantity:0,unit:"MT",buy_currency:"USD",sell_currency:"USD",buy_price:0,sell_price:0,buy_rate:null,sell_rate:null,etd:null,eta:null,notes:""};
export default function NewDealPage(){
 const router=useRouter();const[form,setForm]=useState<NewDealInput>(initial),[customers,setCustomers]=useState<any[]>([]),[suppliers,setSuppliers]=useState<any[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{void(async()=>{try{const x=await getDealFormLookups();setCustomers(x.customers);setSuppliers(x.suppliers)}catch(e:any){setError(e?.message||"Unable to load master data.")}finally{setLoading(false)}})()},[]);
 const cross=form.buy_currency!==form.sell_currency;const qty=Number(form.quantity||0),buy=Number(form.buy_price||0),sell=Number(form.sell_price||0),sale=qty*sell;const nativeProfit=cross?null:qty*(sell-buy);const profitAed=cross&&Number(form.buy_rate||0)>0&&Number(form.sell_rate||0)>0?qty*((sell*Number(form.sell_rate))-(buy*Number(form.buy_rate))):!cross&&form.sell_currency==="AED"?Number(nativeProfit||0):!cross&&Number(form.sell_rate||0)>0?Number(nativeProfit||0)*Number(form.sell_rate):0;
 const eligibleSuppliers=useMemo(()=>suppliers.filter(s=>s.status==="active"&&s.kyc_status==="approved"&&(!s.kyc_expiry_date||new Date(s.kyc_expiry_date)>=new Date(new Date().toISOString().slice(0,10)))),[suppliers]);
 function set<K extends keyof NewDealInput>(k:K,v:NewDealInput[K]){setForm(x=>({...x,[k]:v}))}
 async function save(e:FormEvent){e.preventDefault();setError("");setSaving(true);try{const d=await createDealControlled(form);router.push(`/deals?created=${d.id}`)}catch(e:any){setError(e?.message||"Unable to create deal.")}finally{setSaving(false)}}
 return <main className="min-h-screen bg-[#070b14] p-5 text-white md:p-8"><header><p className="text-xs font-semibold uppercase tracking-[.24em] text-blue-400">Commercial Origination</p><h1 className="mt-2 text-3xl font-bold">Create New Deal</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">Create a controlled draft using active customer and compliant supplier master data. Payment and shipment states are system-derived.</p></header>{error&&<div className="mt-5 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{error}</div>}
 <form onSubmit={save} className="mt-6 space-y-5"><Section title="Parties"><div className="grid gap-3 md:grid-cols-2"><Field l="Customer *"><select required disabled={loading} value={form.customer_id} onChange={e=>set("customer_id",e.target.value)} className={input}><option value="">Select active customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></Field><Field l="Supplier"><select disabled={loading} value={form.supplier_id??""} onChange={e=>set("supplier_id",e.target.value||null)} className={input}><option value="">No supplier yet</option>{eligibleSuppliers.map(s=><option key={s.id} value={s.id}>{s.company_name} · KYC approved</option>)}</select><p className="mt-1 text-xs text-slate-500">Only active suppliers with valid approved KYC are selectable.</p></Field></div></Section>
 <Section title="Commercial Scope"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Field l="Commodity *"><input required value={form.commodity} onChange={e=>set("commodity",e.target.value)} className={input}/></Field><Field l="Quantity *"><input required type="number" min="0" step="any" value={form.quantity} onChange={e=>set("quantity",Number(e.target.value))} className={input}/></Field><Field l="Unit"><input value={form.unit} onChange={e=>set("unit",e.target.value)} className={input}/></Field><Field l="Incoterm"><input value={form.incoterm} onChange={e=>set("incoterm",e.target.value.toUpperCase())} className={input}/></Field><Field l="Origin"><input value={form.origin_country} onChange={e=>set("origin_country",e.target.value)} className={input}/></Field><Field l="Destination"><input value={form.destination_country} onChange={e=>set("destination_country",e.target.value)} className={input}/></Field><Field l="ETD"><input type="date" value={form.etd??""} onChange={e=>set("etd",e.target.value||null)} className={input}/></Field><Field l="ETA"><input type="date" value={form.eta??""} onChange={e=>set("eta",e.target.value||null)} className={input}/></Field></div></Section>
 <Section title="Commercial Economics"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Field l="Buy Currency"><Currency value={form.buy_currency} onChange={v=>set("buy_currency",v)}/></Field><Field l="Buy Price"><input type="number" min="0" step="any" value={form.buy_price} onChange={e=>set("buy_price",Number(e.target.value))} className={input}/></Field><Field l="Sell Currency"><Currency value={form.sell_currency} onChange={v=>set("sell_currency",v)}/></Field><Field l="Sell Price"><input type="number" min="0" step="any" value={form.sell_price} onChange={e=>set("sell_price",Number(e.target.value))} className={input}/></Field>{cross&&<><Field l="Buy AED Conversion Rate *"><input required type="number" min="0.000001" step="any" value={form.buy_rate??""} onChange={e=>set("buy_rate",e.target.value?Number(e.target.value):null)} className={input}/></Field><Field l="Sell AED Conversion Rate *"><input required type="number" min="0.000001" step="any" value={form.sell_rate??""} onChange={e=>set("sell_rate",e.target.value?Number(e.target.value):null)} className={input}/></Field></>}{!cross&&form.sell_currency!=="AED"&&<Field l="Optional AED Conversion Rate"><input type="number" min="0" step="any" value={form.sell_rate??""} onChange={e=>set("sell_rate",e.target.value?Number(e.target.value):null)} className={input}/></Field>}</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><K l="Sale Value" v={`${form.sell_currency} ${sale.toLocaleString()}`}/><K l="Native GP" v={nativeProfit===null?"Cross-currency":`${form.sell_currency} ${nativeProfit.toLocaleString()}`}/><K l="Normalized GP" v={`AED ${profitAed.toLocaleString()}`}/></div>{cross&&<p className="mt-3 text-xs text-amber-300">Cross-currency deals require AED conversion rates before approval. Unlike currencies are never subtracted directly.</p>}</Section>
 <Section title="Internal Notes"><textarea value={form.notes} onChange={e=>set("notes",e.target.value)} className={`${input} min-h-28`} placeholder="Commercial conditions, exceptions, commitments, approval context..."/></Section>
 <div className="flex justify-end gap-2"><button type="button" onClick={()=>router.push("/deals")} className="rounded-xl border border-slate-700 px-4 py-3">Cancel</button><button disabled={saving||loading} className="rounded-xl bg-blue-600 px-5 py-3 font-semibold disabled:opacity-50">{saving?"Creating...":"Create Draft Deal"}</button></div></form></main>
}
function Section({title,children}:{title:string;children:ReactNode}){return <section className="rounded-2xl border border-slate-800 bg-[#0d1423] p-5"><h2 className="mb-4 font-semibold">{title}</h2>{children}</section>}
function Field({l,children}:{l:string;children:ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-medium text-slate-400">{l}</span>{children}</label>}
function Currency({value,onChange}:{value:string;onChange:(v:string)=>void}){return <select value={value} onChange={e=>onChange(e.target.value)} className={input}>{["AED","USD","EUR","GBP","CNY","INR","IRR"].map(c=><option key={c}>{c}</option>)}</select>}
function K({l,v}:{l:string;v:string}){return <div className="rounded-xl border border-slate-800 bg-slate-950/50 p-3"><p className="text-xs text-slate-500">{l}</p><p className="mt-1 font-semibold">{v}</p></div>}
