"use client";
import {useEffect,useMemo,useState} from "react";
import {decideEnterpriseApproval,delegateEnterpriseApproval,getEnterpriseApprovalQueue,getEnterpriseUsers,type EnterpriseApproval} from "@/lib/enterprise-control";

const panel="rounded-2xl border border-slate-800 bg-[#0d1423]";
const btn="rounded-xl border border-slate-700 bg-slate-950/40 px-4 py-2.5 text-sm font-medium text-slate-200 hover:border-blue-500 disabled:opacity-40";
const primary="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-500 disabled:opacity-40";
const input="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500";
const pretty=(v:string|null|undefined)=>(v||"—").replaceAll("_"," ");
const money=(n:number|null,c:string|null)=>n==null?"—":`${c||""} ${Number(n).toLocaleString("en-US",{maximumFractionDigits:2})}`.trim();
function tone(v:string){const x=v.toLowerCase();return x==="approved"?"border-emerald-800 bg-emerald-950/40 text-emerald-300":x==="rejected"?"border-red-900 bg-red-950/40 text-red-300":x==="critical"?"border-red-900 bg-red-950/40 text-red-300":x==="high"?"border-orange-900 bg-orange-950/40 text-orange-300":"border-amber-900 bg-amber-950/30 text-amber-300"}

export function ApprovalCenter(){
 const[rows,setRows]=useState<EnterpriseApproval[]>([]),[users,setUsers]=useState<any[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const[filter,setFilter]=useState("pending"),[moduleFilter,setModuleFilter]=useState("ALL"),[selected,setSelected]=useState<EnterpriseApproval|null>(null),[note,setNote]=useState("");
 const[showDelegate,setShowDelegate]=useState(false),[delegateId,setDelegateId]=useState(""),[delegateModule,setDelegateModule]=useState(""),[startsAt,setStartsAt]=useState(""),[endsAt,setEndsAt]=useState(""),[delegateReason,setDelegateReason]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const[q,u]=await Promise.all([getEnterpriseApprovalQueue(),getEnterpriseUsers()]);setRows(q);setUsers(u);if(selected)setSelected(q.find(x=>x.id===selected.id)||null)}catch(e:any){setError(e.message||"Unable to load approvals.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>rows.filter(x=>(filter==="ALL"||x.status===filter)&&(moduleFilter==="ALL"||x.module===moduleFilter)),[rows,filter,moduleFilter]);
 const modules=Array.from(new Set(rows.map(x=>x.module).filter(Boolean)));
 const summary={pending:rows.filter(x=>x.status==="pending").length,overdue:rows.filter(x=>x.status==="pending"&&x.overdue).length,approved:rows.filter(x=>x.status==="approved").length,rejected:rows.filter(x=>x.status==="rejected").length};
 const decide=async(decision:"approved"|"rejected")=>{if(!selected)return;if(decision==="rejected"&&!note.trim())return setError("Rejection comments are required.");setSaving(true);setError("");try{await decideEnterpriseApproval(selected.id,decision,note);setMessage(`Approval ${decision}.`);setNote("");await load()}catch(e:any){setError(e.message||"Decision failed.")}finally{setSaving(false)}};
 const delegate=async()=>{if(!delegateId||!startsAt||!endsAt)return setError("Delegate, start and end are required.");setSaving(true);setError("");try{await delegateEnterpriseApproval(delegateId,delegateModule,new Date(startsAt).toISOString(),new Date(endsAt).toISOString(),delegateReason);setMessage("Approval authority delegated.");setShowDelegate(false);setDelegateId("");setDelegateModule("");setStartsAt("");setEndsAt("");setDelegateReason("")}catch(e:any){setError(e.message||"Delegation failed.")}finally{setSaving(false)}};
 return <main className="min-h-screen bg-[#060a12] p-5 text-white md:p-8"><div className="mx-auto max-w-[1700px]">
  <header className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-blue-400">Enterprise Authority Engine</p><h1 className="mt-2 text-3xl font-bold">Approval & Authority Center</h1><p className="mt-2 max-w-4xl text-sm text-slate-400">One controlled queue for Commercial, Logistics, Finance, Treasury and Document approvals with assignment, delegation, overdue visibility and audit-backed decisions.</p></div><div className="flex gap-2"><button className={btn} onClick={()=>void load()} disabled={loading||saving}>Refresh</button><button className={primary} onClick={()=>setShowDelegate(true)}>Delegate Authority</button></div></header>
  {error&&<div className="mt-5 rounded-xl border border-red-900 bg-red-950/30 p-4 text-sm text-red-300">{error}</div>}{message&&<div className="mt-5 rounded-xl border border-emerald-900 bg-emerald-950/30 p-4 text-sm text-emerald-300">{message}</div>}
  <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Pending",summary.pending],["Overdue",summary.overdue],["Approved",summary.approved],["Rejected",summary.rejected]].map(([l,v])=><div key={String(l)} className={panel+" p-5"}><p className="text-xs text-slate-500">{l}</p><p className="mt-2 text-3xl font-bold">{v}</p></div>)}</section>
  <section className="mt-5 grid gap-5 2xl:grid-cols-[1.2fr_.8fr]"><div className={panel+" overflow-hidden"}><div className="grid gap-3 border-b border-slate-800 p-4 md:grid-cols-2"><select className={input} value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="ALL">All Statuses</option></select><select className={input} value={moduleFilter} onChange={e=>setModuleFilter(e.target.value)}><option value="ALL">All Modules</option>{modules.map(x=><option key={x}>{x}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="text-[10px] uppercase tracking-wider text-slate-500"><tr>{["Request","Module","Amount","Priority","Due","Status",""].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{filtered.map(x=><tr key={x.id} className="border-t border-slate-800"><td className="px-4 py-3"><b>{pretty(x.approval_type)}</b><div className="mt-1 text-xs text-slate-500">{x.reference||x.id} · {x.requester}</div></td><td className="px-4 py-3">{x.module}</td><td className="px-4 py-3">{money(x.amount,x.currency)}</td><td className="px-4 py-3"><span className={`rounded-full border px-2 py-1 text-[10px] font-semibold capitalize ${tone(x.priority)}`}>{x.priority}</span></td><td className={`px-4 py-3 ${x.overdue?"text-red-300":"text-slate-300"}`}>{x.due_at?new Date(x.due_at).toLocaleString():"—"}</td><td className="px-4 py-3"><span className={`rounded-full border px-2 py-1 text-[10px] font-semibold capitalize ${tone(x.status)}`}>{x.status}</span></td><td className="px-4 py-3"><button className={btn} onClick={()=>{setSelected(x);setNote("")}}>Inspect</button></td></tr>)}{!loading&&filtered.length===0&&<tr><td colSpan={7} className="p-10 text-center text-slate-500">No approval records match the current view.</td></tr>}</tbody></table></div></div>
   <aside className={panel+" p-5"}>{selected?<><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-wider text-blue-400">{selected.module}</p><h2 className="mt-2 text-xl font-bold">{pretty(selected.approval_type)}</h2><p className="mt-1 text-xs text-slate-500">{selected.reference||selected.id}</p></div><span className={`rounded-full border px-2 py-1 text-xs capitalize ${tone(selected.status)}`}>{selected.status}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{[["Requested by",selected.requester],["Assigned to",selected.approver],["Amount",money(selected.amount,selected.currency)],["Escalation",String(selected.escalation_level)]].map(([a,b])=><div key={a} className="rounded-xl border border-slate-800 bg-slate-950/30 p-3"><p className="text-[10px] uppercase text-slate-600">{a}</p><p className="mt-1 text-sm">{b}</p></div>)}</div>{selected.comments&&<div className="mt-3 rounded-xl border border-slate-800 p-3 text-sm text-slate-400">{selected.comments}</div>}{selected.status==="pending"&&selected.can_decide&&<><textarea className={`${input} mt-4 min-h-28`} value={note} onChange={e=>setNote(e.target.value)} placeholder="Decision comments / conditions..."/><div className="mt-3 grid grid-cols-2 gap-2"><button className={btn} disabled={saving} onClick={()=>void decide("rejected")}>Reject</button><button className={primary} disabled={saving} onClick={()=>void decide("approved")}>Approve</button></div></>}</>:<div className="flex min-h-60 items-center justify-center text-center text-sm text-slate-500">Select an approval request to inspect its authority, assignment and decision status.</div>}</aside>
  </section>
  {showDelegate&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/80 p-4"><div className="mx-auto mt-16 max-w-2xl rounded-3xl border border-slate-700 bg-[#0b1120] p-6"><div className="flex justify-between"><div><p className="text-xs uppercase tracking-wider text-blue-400">Delegated Authority</p><h2 className="mt-1 text-2xl font-bold">Delegate Approval Rights</h2></div><button className={btn} onClick={()=>setShowDelegate(false)}>Close</button></div><div className="mt-5 grid gap-3 md:grid-cols-2"><select className={input} value={delegateId} onChange={e=>setDelegateId(e.target.value)}><option value="">Select active user</option>{users.map(x=><option key={x.id} value={x.id}>{x.full_name} · {x.role}</option>)}</select><select className={input} value={delegateModule} onChange={e=>setDelegateModule(e.target.value)}><option value="">All Modules</option>{["Commercial","Logistics","Finance","Treasury","Documents"].map(x=><option key={x}>{x}</option>)}</select><input className={input} type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/><input className={input} type="datetime-local" value={endsAt} onChange={e=>setEndsAt(e.target.value)}/><textarea className={`${input} min-h-24 md:col-span-2`} value={delegateReason} onChange={e=>setDelegateReason(e.target.value)} placeholder="Delegation reason..."/></div><div className="mt-4 flex justify-end gap-2"><button className={btn} onClick={()=>setShowDelegate(false)}>Cancel</button><button className={primary} disabled={saving} onClick={()=>void delegate()}>Save Delegation</button></div></div></div>}
 </div></main>
}
