"use client";

import {FormEvent,useEffect,useState} from "react";
import {createUser,loadUserAdministration,setUserActive,setUserRole,type AdminProfile} from "@/lib/user-admin";
const field="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-white outline-none focus:border-blue-500";
const roles=["admin","ceo","manager","dealer","finance","operations","logistics"];
export default function UsersRoute(){
 const[me,setMe]=useState<AdminProfile|null>(null),[users,setUsers]=useState<AdminProfile[]>([]),[form,setForm]=useState({full_name:"",email:"",password:"",role:"dealer"}),[message,setMessage]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState("");
 async function load(){setLoading(true);setError("");try{const x=await loadUserAdministration();setMe(x.me);setUsers(x.users)}catch(e:any){setError(e?.message||"Unable to load users.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function create(e:FormEvent){e.preventDefault();setBusy("create");setError("");setMessage("");try{await createUser(form);setMessage(`User ${form.email} created successfully.`);setForm({full_name:"",email:"",password:"",role:"dealer"});await load()}catch(e:any){setError(e?.message||"Unable to create user.")}finally{setBusy("")}}
 async function toggle(u:AdminProfile){if(u.id===me?.id)return;setBusy(u.id);setError("");try{await setUserActive(u.id,!u.active);setMessage(`${u.full_name||"User"} is now ${u.active?"disabled":"active"}.`);await load()}catch(e:any){setError(e?.message||"Unable to update user status.")}finally{setBusy("")}}
 async function role(u:AdminProfile,value:string){if(u.id===me?.id)return;setBusy(u.id);setError("");try{await setUserRole(u.id,value);setMessage(`${u.full_name||"User"} role changed to ${value}.`);await load()}catch(e:any){setError(e?.message||"Unable to update role.")}finally{setBusy("")}}
 if(loading)return <main className="p-8 text-slate-400">Loading users...</main>;if(me?.role!=="admin")return <main className="p-8 text-red-300">Access denied. Administrator permission is required.</main>;
 return <main className="min-h-screen bg-[#060a12] p-5 text-white md:p-8"><div className="mx-auto max-w-7xl"><header><p className="text-xs font-semibold uppercase tracking-[.22em] text-blue-400">Administration & Access Control</p><h1 className="mt-2 text-3xl font-bold">User Management</h1><p className="mt-2 text-sm text-slate-400">Create authenticated users, assign system roles and control account access. Every change is verified against the stored profile before the UI reports success.</p></header>
 <form onSubmit={create} className="mt-6 grid gap-4 rounded-2xl border border-slate-800 bg-[#0d1424] p-5 md:grid-cols-5"><input required placeholder="Full name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} className={field}/><input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className={field}/><input required minLength={8} type="password" placeholder="Password (8+ chars)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className={field}/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className={field}>{roles.map(r=><option key={r} value={r}>{r.toUpperCase()}</option>)}</select><button type="submit" disabled={busy==="create"} className="rounded-xl bg-blue-600 px-4 py-3 font-semibold disabled:opacity-50">{busy==="create"?"Creating...":"Create User"}</button></form>
 {error&&<p className="mt-4 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}{message&&<p className="mt-4 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm text-emerald-300">{message}</p>}
 <section className="mt-6 overflow-hidden rounded-2xl border border-slate-800 bg-[#0d1424]"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-950/50 text-xs uppercase text-slate-500"><tr><th className="p-4">User</th><th>Role</th><th>Status</th><th>Created</th><th className="p-4 text-right">Control</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t border-slate-800"><td className="p-4"><p className="font-semibold">{u.full_name||"Unnamed user"}</p><p className="mt-1 text-xs text-slate-600">{u.id===me?.id?"Current administrator":"Authenticated profile"}</p></td><td><select disabled={u.id===me?.id||busy===u.id} value={u.role} onChange={e=>void role(u,e.target.value)} className={`${field} py-2`} aria-label={`Role for ${u.full_name||u.id}`}>{roles.map(r=><option key={r} value={r}>{r.toUpperCase()}</option>)}</select></td><td><span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${u.active?"border-emerald-500/30 bg-emerald-500/10 text-emerald-300":"border-red-500/30 bg-red-500/10 text-red-300"}`}>{u.active?"ACTIVE":"DISABLED"}</span></td><td className="text-slate-400">{u.created_at?new Date(u.created_at).toLocaleDateString():"—"}</td><td className="p-4 text-right"><button type="button" onClick={()=>void toggle(u)} disabled={u.id===me?.id||busy===u.id} className={`rounded-xl px-4 py-2 text-sm font-semibold ${u.active?"border border-red-500/30 text-red-300":"bg-emerald-600 text-white"} disabled:opacity-40`}>{busy===u.id?"Updating...":u.active?"Disable User":"Activate User"}</button></td></tr>)}</tbody></table></div></section>
 </div></main>
}
