"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {createQuotationFromOpportunity,convertQuotationToDeal,createShipmentFromCommercialDeal,decideQuotation,generateReceivableInvoice,listCommercialFlow,submitQuotationForReview,type CommercialFlowData} from "@/lib/commercial-flow";

const card="rounded-2xl border border-slate-800 bg-[#0d1423]";
const btn="rounded-xl border border-slate-700 px-3 py-2 text-xs font-semibold text-slate-200 hover:border-blue-500 hover:text-blue-300 disabled:cursor-not-allowed disabled:opacity-40";
const money=new Intl.NumberFormat("en-US",{maximumFractionDigits:0});

export function CommercialFlowControlCenter(){
 const[data,setData]=useState<CommercialFlowData|null>(null),[busy,setBusy]=useState(""),[notice,setNotice]=useState("");
 const load=async()=>{setBusy("load");try{setData(await listCommercialFlow())}catch(e:any){setNotice(e?.message||"Unable to load commercial flow.")}finally{setBusy("")}};
 useEffect(()=>{void load()},[]);
 const stats=useMemo(()=>{if(!data)return{pipeline:0,quotes:0,approved:0,deals:0,shipments:0,uninvoiced:0,outstanding:0};const open=data.opportunities.filter(x=>!["won","lost"].includes(x.stage));const pipeline=open.reduce((n,x)=>n+Number(x.estimated_value||0),0);const approved=data.quotations.filter(x=>x.status==="approved").length;const dealIds=new Set(data.invoices.map(x=>x.deal_id).filter(Boolean));const uninvoiced=data.deals.filter(x=>x.status==="approved"&&!dealIds.has(x.id)).length;const paidByInvoice=new Map<string,number>();data.payments.filter(x=>["completed","paid","settled","executed"].includes(x.status)).forEach(x=>paidByInvoice.set(x.invoice_id,(paidByInvoice.get(x.invoice_id)||0)+Number(x.amount||0)));const outstanding=data.invoices.filter(x=>x.invoice_type==="receivable"&&x.status!=="cancelled").reduce((n,x)=>n+Math.max(0,Number(x.total_amount||0)-(paidByInvoice.get(x.id)||0)),0);return{pipeline,quotes:data.quotations.length,approved,deals:data.deals.length,shipments:data.shipments.length,uninvoiced,outstanding}},[data]);
 async function run(key:string,fn:()=>Promise<any>,ok:string){setBusy(key);setNotice("");try{await fn();setNotice(ok);await load()}catch(e:any){setNotice(e?.message||"Action failed.")}finally{setBusy("")}}
 if(!data)return <main className="min-h-screen bg-[#070b14] p-6 text-white"><div className={`${card} p-8`}>{notice||"Loading Commercial Flow..."}</div></main>;
 const dealForQuote=(qid:string)=>data.deals.find(d=>d.quotation_id===qid); const shipsForDeal=(id:string)=>data.shipments.filter(s=>s.deal_id===id); const invoicesForDeal=(id:string)=>data.invoices.filter(i=>i.deal_id===id&&i.invoice_type==="receivable"&&i.status!=="cancelled");
 return <main className="min-h-screen bg-[#070b14] p-5 text-white md:p-8">
  <header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-blue-400">VTC ONE · Commercial Execution</p><h1 className="mt-2 text-3xl font-bold">Commercial Flow Control Center</h1><p className="mt-2 max-w-4xl text-sm text-slate-400">One controlled chain from opportunity to quotation, deal, shipment, invoice and collection. Every conversion is linked, audited and duplicate-protected.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>void load()} className={btn}>{busy==="load"?"Refreshing...":"Refresh"}</button><Link href="/commercial/opportunities" className={btn}>Opportunities</Link><Link href="/quotations" className={btn}>Quotations</Link><Link href="/deals" className={btn}>Deals</Link></div></header>
  {notice&&<div className="mt-5 rounded-xl border border-blue-500/30 bg-blue-500/10 p-3 text-sm text-blue-100">{notice}</div>}
  <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-7"><K l="Open Pipeline" v={`AED ${money.format(stats.pipeline)}`}/><K l="Quotations" v={String(stats.quotes)}/><K l="Approved Quotes" v={String(stats.approved)}/><K l="Deals" v={String(stats.deals)}/><K l="Shipments" v={String(stats.shipments)}/><K l="Uninvoiced Deals" v={String(stats.uninvoiced)} warn={stats.uninvoiced>0}/><K l="Outstanding A/R" v={`AED ${money.format(stats.outstanding)}`} warn={stats.outstanding>0}/></section>

  <section className="mt-6 grid gap-5 2xl:grid-cols-2">
   <div className={`${card} overflow-hidden`}><Head title="Opportunity → Quotation" sub="Qualified opportunities waiting for controlled quotation creation"/><div className="divide-y divide-slate-800">{data.opportunities.filter(o=>!["won","lost"].includes(o.stage)).map(o=>{const q=data.quotations.find(x=>x.opportunity_id===o.id||x.id===o.quotation_id);return <div key={o.id} className="p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><b>{o.opportunity_no}</b><Badge v={o.stage}/></div><p className="mt-1 text-sm text-slate-300">{o.title} · {o.customers?.company_name||"No customer"}</p><p className="mt-1 text-xs text-slate-500">{o.currency} {money.format(Number(o.estimated_value||0))} · {o.probability}% probability</p></div>{q?<div className="flex items-center gap-2"><Badge v={q.status}/><Link className={btn} href="/quotations">Open {q.quotation_no||"Draft"}</Link></div>:<button disabled={!!busy||!data.permissions.canWrite} onClick={()=>void run(`opp-${o.id}`,()=>createQuotationFromOpportunity(o.id,null),"Draft quotation created and linked.")} className={btn}>{busy===`opp-${o.id}`?"Creating...":"Create Quotation"}</button>}</div></div>})}{!data.opportunities.length&&<Empty t="No opportunities yet."/>}</div></div>

   <div className={`${card} overflow-hidden`}><Head title="Quotation → Deal" sub="Commercial review, approval and controlled conversion"/><div className="divide-y divide-slate-800">{data.quotations.map(q=>{const deal=dealForQuote(q.id);return <div key={q.id} className="p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex gap-2"><b>{q.quotation_no||"Unnumbered Draft"}</b><Badge v={q.status}/></div><p className="mt-1 text-sm text-slate-300">{q.title} · {q.customers?.company_name||"—"}</p><p className="mt-1 text-xs text-slate-500">{q.currency} {money.format(Number(q.total_amount||0))} · Margin {Number(q.margin_percent||0).toFixed(1)}%</p></div><div className="flex flex-wrap gap-2"><Link href="/quotations" className={btn}>Open</Link>{["draft","rejected"].includes(q.status)&&<button disabled={!!busy} onClick={()=>void run(`submit-${q.id}`,()=>submitQuotationForReview(q.id,"Commercial review"),"Quotation submitted for review.")} className={btn}>Submit Review</button>}{q.status==="review"&&data.permissions.canControl&&<><button disabled={!!busy} onClick={()=>void run(`approve-${q.id}`,()=>decideQuotation(q.id,"approved","Commercial approval"),"Quotation approved.")} className={btn}>Approve</button><button disabled={!!busy} onClick={()=>{const reason=window.prompt("Rejection reason");if(reason)void run(`reject-${q.id}`,()=>decideQuotation(q.id,"rejected",reason),"Quotation rejected for revision.")}} className={btn}>Reject</button></>}{q.status==="approved"&&!deal&&<button disabled={!!busy} onClick={()=>void run(`deal-${q.id}`,()=>convertQuotationToDeal(q.id),"Deal created from approved quotation.")} className={btn}>Convert to Deal</button>}{deal&&<Link href="/deals" className={btn}>Deal {deal.deal_no}</Link>}</div></div></div>})}{!data.quotations.length&&<Empty t="No quotations yet."/>}</div></div>
  </section>

  <section className={`${card} mt-6 overflow-hidden`}><Head title="Deal → Shipment → Invoice" sub="Operational handover and receivable generation from approved commercial commitments"/><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-slate-950/60 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Deal</th><th>Customer</th><th>Status</th><th>GP</th><th>Shipment</th><th>Invoice</th><th>Next action</th><th className="p-4 text-right">Control</th></tr></thead><tbody>{data.deals.map(d=>{const ships=shipsForDeal(d.id),invs=invoicesForDeal(d.id),ship=ships[0];const next=d.status!=="approved"?"Deal approval":!ships.length?"Create shipment":!invs.length?"Generate invoice":"Execution / collection";return <tr key={d.id} className="border-t border-slate-800"><td className="p-4 font-semibold">{d.deal_no}</td><td>{d.customers?.company_name||"—"}</td><td><Badge v={d.status}/></td><td>AED {money.format(Number(d.profit_aed||0))}</td><td>{ships.length?`${ships.length} · ${ship.status}`:"—"}</td><td>{invs.length?`${invs.length} · ${invs[0].status}`:"—"}</td><td className="text-slate-400">{next}</td><td className="p-4"><div className="flex justify-end gap-2"><Link href="/deals" className={btn}>Open Deal</Link>{d.status==="approved"&&!ships.length&&<button disabled={!!busy} onClick={()=>void run(`ship-${d.id}`,()=>createShipmentFromCommercialDeal(d.id,"sea"),"Planning shipment created and linked.")} className={btn}>Create Shipment</button>}{d.status==="approved"&&ships.length&&!invs.length&&<button disabled={!!busy} onClick={()=>void run(`inv-${d.id}`,()=>generateReceivableInvoice(d.id,ship.id,null),"Draft receivable invoice generated.")} className={btn}>Generate Invoice</button>}</div></td></tr>})}{!data.deals.length&&<tr><td colSpan={8}><Empty t="No Deals yet."/></td></tr>}</tbody></table></div></section>

  <section className={`${card} mt-6 p-5`}><div className="flex items-center justify-between"><div><h2 className="font-semibold">Commercial Audit Stream</h2><p className="mt-1 text-xs text-slate-500">Latest controlled cross-module conversions</p></div><span className="text-xs text-slate-500">{data.events.length} events loaded</span></div><div className="mt-4 grid gap-2 lg:grid-cols-2">{data.events.slice(0,12).map(e=><div key={e.id} className="rounded-xl border border-slate-800 bg-slate-950/40 p-3"><div className="flex items-center justify-between gap-3"><b className="text-sm">{String(e.action).replaceAll("_"," ")}</b><span className="text-[11px] text-slate-500">{new Date(e.created_at).toLocaleString()}</span></div><p className="mt-1 text-xs text-slate-400">{e.source_type} → {e.target_type||"workflow"}</p></div>)}{!data.events.length&&<p className="text-sm text-slate-500">Audit events will appear after controlled conversions.</p>}</div></section>
 </main>
}
function Head({title,sub}:{title:string;sub:string}){return <div className="border-b border-slate-800 p-5"><h2 className="font-semibold">{title}</h2><p className="mt-1 text-xs text-slate-500">{sub}</p></div>}
function K({l,v,warn=false}:{l:string;v:string;warn?:boolean}){return <div className={`${card} p-4`}><p className="text-[11px] uppercase tracking-wider text-slate-500">{l}</p><p className={`mt-2 text-xl font-bold ${warn?"text-amber-300":"text-white"}`}>{v}</p></div>}
function Badge({v}:{v:string}){const good=["approved","won","completed","paid","delivered"].includes(v);const bad=["rejected","lost","cancelled","expired","blocked"].includes(v);return <span className={`rounded-full border px-2 py-1 text-[10px] font-bold uppercase ${good?"border-emerald-500/30 bg-emerald-500/10 text-emerald-300":bad?"border-red-500/30 bg-red-500/10 text-red-300":"border-slate-700 bg-slate-900 text-slate-300"}`}>{v}</span>}
function Empty({t}:{t:string}){return <div className="p-8 text-center text-sm text-slate-500">{t}</div>}
