"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {assignCustomerOwner,createCustomer,deleteCustomer,getCustomerAccess,getCustomerEvents,getCustomerSnapshot,getCustomers,setCustomerCredit,setCustomerStatus,updateCustomer,type Customer,type CustomerAccess,type CustomerEvent,type CustomerSnapshot,type CustomerStatus} from "@/lib/customers";

const input="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500";
const currencies=["AED","USD","EUR","GBP","CNY","INR"];
const types=["customer","supplier","both","agent","shipping_line","warehouse"];
const statuses:CustomerStatus[]=["lead","active","inactive","blocked"];
const money=(n:number,c="AED")=>`${c} ${new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(Number(n||0))}`;
const tone=(s:string)=>s==="active"?"border-emerald-700 bg-emerald-950/40 text-emerald-300":s==="blocked"?"border-red-800 bg-red-950/40 text-red-300":s==="inactive"?"border-slate-700 bg-slate-900 text-slate-300":"border-blue-800 bg-blue-950/40 text-blue-300";
const empty:any={customer_code:"",company_name:"",customer_type:"customer",contact_person:"",email:"",phone:"",mobile:"",website:"",country:"",city:"",address:"",tax_number:"",registration_number:"",industry:"",source:"",notes:""};

type Owner={id:string;full_name:string|null};
function Card({label,value,sub}:{label:string,value:any,sub?:string}){return <div className="rounded-2xl border border-slate-800 bg-[#0d1423] p-4"><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p>{sub&&<p className="mt-1 text-xs text-slate-500">{sub}</p>}</div>}
function Field({label,value,onChange}:{label:string,value:any,onChange:(v:string)=>void}){return <label className="text-xs text-slate-400">{label}<input value={value??""} onChange={e=>onChange(e.target.value)} className={`${input} mt-2`}/></label>}

export function CustomerControlCenter(){
 const[rows,setRows]=useState<Customer[]>([]),[owners,setOwners]=useState<Owner[]>([]),[access,setAccess]=useState<CustomerAccess|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[q,setQ]=useState(""),[statusFilter,setStatusFilter]=useState("all"),[typeFilter,setTypeFilter]=useState("all"),[form,setForm]=useState<any|null>(null),[editing,setEditing]=useState<Customer|null>(null),[selected,setSelected]=useState<Customer|null>(null),[snapshot,setSnapshot]=useState<CustomerSnapshot|null>(null),[events,setEvents]=useState<CustomerEvent[]>([]),[busy,setBusy]=useState(false),[action,setAction]=useState<any|null>(null);
 const load=async()=>{setLoading(true);setError(null);try{const db=createClient();const[c,a,p]=await Promise.all([getCustomers(),getCustomerAccess(),db.from("profiles").select("id,full_name").eq("active",true).order("full_name")]);setRows(c);setAccess(a);setOwners((p.data??[]) as Owner[])}catch(e:any){setError(e.message||"Could not load customer control center.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const ownerName=(id:string|null)=>owners.find(o=>o.id===id)?.full_name||"Unassigned";
 const filtered=useMemo(()=>rows.filter(c=>(statusFilter==="all"||c.status===statusFilter)&&(typeFilter==="all"||c.customer_type===typeFilter)&&`${c.company_name} ${c.customer_code||""} ${c.contact_person||""} ${c.email||""} ${c.phone||""} ${c.country||""} ${c.city||""}`.toLowerCase().includes(q.toLowerCase())),[rows,q,statusFilter,typeFilter]);
 const kpi=useMemo(()=>({total:rows.length,active:rows.filter(x=>x.status==="active").length,lead:rows.filter(x=>x.status==="lead").length,blocked:rows.filter(x=>x.status==="blocked").length,credit:rows.reduce((n,x)=>n+Number(x.credit_limit||0),0),unassigned:rows.filter(x=>!x.assigned_to).length}),[rows]);
 const open360=async(c:Customer)=>{setSelected(c);setSnapshot(null);setEvents([]);try{const[s,e]=await Promise.all([getCustomerSnapshot(c.id),getCustomerEvents(c.id)]);setSnapshot(s);setEvents(e)}catch(x:any){setError(x.message)}};
 const startForm=(c?:Customer)=>{setEditing(c||null);setForm(c?{...empty,...c}:structuredClone(empty));setNotice(null)};
 const saveMaster=async()=>{if(!form?.company_name?.trim())return setError("Company name is required.");setBusy(true);setError(null);try{if(editing)await updateCustomer(editing.id,form);else await createCustomer(form);setForm(null);setEditing(null);setNotice(editing?"Customer master updated.":"Customer created as Lead with zero credit exposure.");await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const refreshSelected=async()=>{if(!selected)return;const fresh=(await getCustomers()).find(x=>x.id===selected.id);if(fresh)setSelected(fresh);const[s,e]=await Promise.all([getCustomerSnapshot(selected.id),getCustomerEvents(selected.id)]);setSnapshot(s);setEvents(e);await load()};
 const runAction=async()=>{if(!action||!selected)return;setBusy(true);setError(null);try{if(action.kind==="status")await setCustomerStatus(selected.id,action.status,action.reason);if(action.kind==="credit")await setCustomerCredit(selected.id,Number(action.limit||0),action.currency,action.reason);if(action.kind==="owner")await assignCustomerOwner(selected.id,action.owner_id||null,action.reason);if(action.kind==="delete"){await deleteCustomer(selected.id,action.reason);setSelected(null);setSnapshot(null);setEvents([])}setAction(null);setNotice("Customer control action completed and audited.");await refreshSelected().catch(()=>load())}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 return <main className="p-5 text-white md:p-8"><header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-blue-400">VTC ONE · Commercial Master Data</p><h1 className="mt-2 text-3xl font-bold">Customer Control Center</h1><p className="mt-2 max-w-4xl text-sm text-slate-400">Controlled customer master, commercial ownership, credit governance, operational exposure and account history in one workspace.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-xl border border-slate-700 px-4 py-3 text-sm">Refresh</button>{access?.canWrite&&<button onClick={()=>startForm()} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold">+ New Customer</button>}</div></header>
 {access&&<div className="mt-4 flex flex-wrap items-center gap-2 text-xs"><span className="rounded-full border border-slate-700 px-3 py-1 text-slate-300">Role: {access.role}</span><span className={`rounded-full border px-3 py-1 ${access.canWrite?"border-emerald-800 text-emerald-300":"border-slate-700 text-slate-400"}`}>{access.canWrite?"Operational Access":"Read Only"}</span>{access.canControlCredit&&<span className="rounded-full border border-amber-800 px-3 py-1 text-amber-300">Credit Controller</span>}</div>}
 {notice&&<div className="mt-4 rounded-xl border border-blue-800 bg-blue-950/30 p-3 text-sm text-blue-200">{notice}</div>}{error&&<div className="mt-4 rounded-xl border border-red-800 bg-red-950/30 p-3 text-sm text-red-200">{error}</div>}
 <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Card label="Accounts" value={kpi.total}/><Card label="Active" value={kpi.active}/><Card label="Leads" value={kpi.lead}/><Card label="Blocked" value={kpi.blocked}/><Card label="Credit Capacity" value={money(kpi.credit)} sub="Across all customer currencies, nominal view"/><Card label="Unassigned" value={kpi.unassigned}/></section>
 <section className="mt-5 rounded-2xl border border-slate-800 bg-[#0d1423] p-4"><div className="grid gap-3 lg:grid-cols-[1fr_180px_200px]"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customer, code, contact, email, city or country..." className={input}/><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className={input}><option value="all">All statuses</option>{statuses.map(x=><option key={x}>{x}</option>)}</select><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)} className={input}><option value="all">All account types</option>{types.map(x=><option key={x}>{x}</option>)}</select></div></section>
 <section className="mt-5 overflow-hidden rounded-2xl border border-slate-800 bg-[#0d1423]"><div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-left text-sm"><thead className="border-b border-slate-800 text-xs uppercase text-slate-500"><tr><th className="p-4">Account</th><th>Contact</th><th>Location</th><th>Owner</th><th>Credit Control</th><th>Status</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="p-12 text-center text-slate-500">Loading customer master...</td></tr>:filtered.length?filtered.map(c=><tr key={c.id} className="border-b border-slate-800/80"><td className="p-4"><button onClick={()=>void open360(c)} className="font-semibold text-blue-400">{c.company_name}</button><p className="mt-1 text-xs text-slate-500">{c.customer_code||"No code"} · {c.customer_type}</p></td><td>{c.contact_person||"—"}<p className="text-xs text-slate-500">{c.email||c.mobile||c.phone||"No contact details"}</p></td><td>{[c.city,c.country].filter(Boolean).join(", ")||"—"}</td><td>{ownerName(c.assigned_to)}</td><td><b>{money(c.credit_limit,c.currency||"AED")}</b></td><td><span className={`rounded-lg border px-2 py-1 text-xs capitalize ${tone(c.status)}`}>{c.status}</span></td><td className="p-4"><div className="flex justify-end gap-2"><button onClick={()=>void open360(c)} className="rounded-lg border border-blue-900 px-3 py-2 text-xs text-blue-300">Open 360</button>{access?.canWrite&&<button onClick={()=>startForm(c)} className="rounded-lg border border-slate-700 px-3 py-2 text-xs">Edit Master</button>}</div></td></tr>):<tr><td colSpan={7} className="p-12 text-center text-slate-500">No customers match the current filters.</td></tr>}</tbody></table></div></section>
 {form&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/80 p-4 md:p-8"><div className="mx-auto max-w-5xl rounded-3xl border border-slate-700 bg-[#0b1120] p-6"><div className="flex justify-between"><div><p className="text-xs uppercase tracking-wider text-blue-400">Customer Master</p><h2 className="mt-1 text-2xl font-bold">{editing?`Edit ${editing.company_name}`:"Create Customer"}</h2><p className="mt-1 text-xs text-slate-500">Status, credit and owner are controlled separately and are not editable here.</p></div><button onClick={()=>setForm(null)} className="text-2xl">×</button></div><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><Field label="Customer Code" value={form.customer_code} onChange={v=>setForm({...form,customer_code:v})}/><Field label="Company Name *" value={form.company_name} onChange={v=>setForm({...form,company_name:v})}/><label className="text-xs text-slate-400">Account Type<select value={form.customer_type} onChange={e=>setForm({...form,customer_type:e.target.value})} className={`${input} mt-2`}>{types.map(x=><option key={x}>{x}</option>)}</select></label><Field label="Contact Person" value={form.contact_person} onChange={v=>setForm({...form,contact_person:v})}/><Field label="Email" value={form.email} onChange={v=>setForm({...form,email:v})}/><Field label="Phone" value={form.phone} onChange={v=>setForm({...form,phone:v})}/><Field label="Mobile" value={form.mobile} onChange={v=>setForm({...form,mobile:v})}/><Field label="Website" value={form.website} onChange={v=>setForm({...form,website:v})}/><Field label="Country" value={form.country} onChange={v=>setForm({...form,country:v})}/><Field label="City" value={form.city} onChange={v=>setForm({...form,city:v})}/><Field label="Industry" value={form.industry} onChange={v=>setForm({...form,industry:v})}/><Field label="Lead Source" value={form.source} onChange={v=>setForm({...form,source:v})}/><Field label="Tax / VAT Number" value={form.tax_number} onChange={v=>setForm({...form,tax_number:v})}/><Field label="Registration Number" value={form.registration_number} onChange={v=>setForm({...form,registration_number:v})}/><Field label="Address" value={form.address} onChange={v=>setForm({...form,address:v})}/></div><textarea value={form.notes||""} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Internal commercial notes" className={`${input} mt-4 min-h-28`}/><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setForm(null)} className="rounded-xl border border-slate-700 px-5 py-2.5">Cancel</button><button disabled={busy} onClick={()=>void saveMaster()} className="rounded-xl bg-blue-600 px-6 py-2.5 font-semibold disabled:opacity-50">{busy?"Saving...":editing?"Save Master":"Create Lead"}</button></div></div></div>}
 {selected&&<div className="fixed inset-0 z-40 overflow-y-auto bg-black/80 p-4 md:p-8"><div className="mx-auto max-w-7xl rounded-3xl border border-slate-700 bg-[#0b1120] p-6"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><p className="text-xs uppercase tracking-wider text-blue-400">Customer 360</p><h2 className="mt-1 text-2xl font-bold">{selected.company_name}</h2><div className="mt-2 flex flex-wrap gap-2"><span className={`rounded-full border px-3 py-1 text-xs capitalize ${tone(selected.status)}`}>{selected.status}</span><span className="rounded-full border border-slate-700 px-3 py-1 text-xs text-slate-300">{selected.customer_type}</span><span className="rounded-full border border-slate-700 px-3 py-1 text-xs text-slate-300">Owner: {ownerName(selected.assigned_to)}</span></div></div><button onClick={()=>setSelected(null)} className="self-start text-2xl">×</button></div>
 <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Card label="Open Exposure" value={snapshot?money(snapshot.open_invoice_value,selected.currency):"—"} sub={`${snapshot?.open_invoices??0} open invoices`}/><Card label="Active Shipments" value={snapshot?.active_shipments??"—"}/><Card label="Deals" value={snapshot?.deals??"—"}/><Card label="Quotations" value={snapshot?.quotations??"—"}/><Card label="Inventory On Hand" value={snapshot?.inventory_on_hand??"—"}/></section>
 <div className="mt-6 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border border-slate-800 bg-slate-950/30 p-5"><div className="flex items-center justify-between"><h3 className="font-semibold">Controlled Actions</h3><span className="text-xs text-slate-500">Audited workflows</span></div><div className="mt-4 grid gap-3 md:grid-cols-2"><button disabled={!access?.canWrite} onClick={()=>setAction({kind:"status",status:selected.status,reason:""})} className="rounded-xl border border-slate-700 p-4 text-left disabled:opacity-40"><b>Account Status</b><p className="mt-1 text-xs text-slate-500">Activate, inactivate or block with control rules.</p></button><button disabled={!access?.canControlCredit} onClick={()=>setAction({kind:"credit",limit:selected.credit_limit,currency:selected.currency||"AED",reason:""})} className="rounded-xl border border-amber-900 p-4 text-left disabled:opacity-40"><b className="text-amber-300">Credit Control</b><p className="mt-1 text-xs text-slate-500">Current: {money(selected.credit_limit,selected.currency)}</p></button><button disabled={!access?.canControlCredit} onClick={()=>setAction({kind:"owner",owner_id:selected.assigned_to||"",reason:""})} className="rounded-xl border border-slate-700 p-4 text-left disabled:opacity-40"><b>Account Ownership</b><p className="mt-1 text-xs text-slate-500">Current: {ownerName(selected.assigned_to)}</p></button><button disabled={!access?.canDelete} onClick={()=>setAction({kind:"delete",reason:""})} className="rounded-xl border border-red-900 p-4 text-left disabled:opacity-40"><b className="text-red-300">Delete Account</b><p className="mt-1 text-xs text-slate-500">Allowed only when no linked business records exist.</p></button></div></section>
 <section className="rounded-2xl border border-slate-800 bg-slate-950/30 p-5"><h3 className="font-semibold">Account Master</h3><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-slate-500">Contact</p><p>{selected.contact_person||"—"}</p></div><div><p className="text-xs text-slate-500">Email / Phone</p><p>{selected.email||selected.mobile||selected.phone||"—"}</p></div><div><p className="text-xs text-slate-500">Location</p><p>{[selected.city,selected.country].filter(Boolean).join(", ")||"—"}</p></div><div><p className="text-xs text-slate-500">Industry</p><p>{selected.industry||"—"}</p></div><div><p className="text-xs text-slate-500">VAT / Tax</p><p>{selected.tax_number||"—"}</p></div><div><p className="text-xs text-slate-500">Registration</p><p>{selected.registration_number||"—"}</p></div></div></section></div>
 <section className="mt-5 rounded-2xl border border-slate-800 bg-slate-950/30 p-5"><div className="flex items-center justify-between"><h3 className="font-semibold">Account Activity Timeline</h3><span className="text-xs text-slate-500">{events.length} audited events</span></div><div className="mt-4 space-y-2">{events.length?events.map(e=><div key={e.id} className="rounded-xl border border-slate-800 p-4"><div className="flex flex-col justify-between gap-1 md:flex-row"><div><b className="capitalize">{e.event_type.replaceAll("_"," ")}</b><p className="mt-1 text-xs text-slate-500">{e.actor?.full_name||"System"} · {new Date(e.created_at).toLocaleString()}</p></div><p className="text-sm text-slate-300">{e.from_value||"—"} → {e.to_value||"—"}</p></div>{e.reason&&<p className="mt-2 text-sm text-slate-400">{e.reason}</p>}</div>):<p className="text-sm text-slate-500">No controlled account actions recorded yet.</p>}</div></section></div></div>}
 {action&&selected&&<div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/80 p-4"><div className="w-full max-w-lg rounded-3xl border border-slate-700 bg-[#0b1120] p-6"><div className="flex justify-between"><div><p className="text-xs uppercase tracking-wider text-blue-400">Controlled Action</p><h3 className="mt-1 text-xl font-bold capitalize">{action.kind} · {selected.company_name}</h3></div><button onClick={()=>setAction(null)} className="text-2xl">×</button></div>{action.kind==="status"&&<div className="mt-5"><label className="text-xs text-slate-400">New Status<select value={action.status} onChange={e=>setAction({...action,status:e.target.value})} className={`${input} mt-2`}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label></div>}{action.kind==="credit"&&<div className="mt-5 grid grid-cols-[1fr_140px] gap-3"><label className="text-xs text-slate-400">Credit Limit<input type="number" min="0" value={action.limit} onChange={e=>setAction({...action,limit:Number(e.target.value)})} className={`${input} mt-2`}/></label><label className="text-xs text-slate-400">Currency<select value={action.currency} onChange={e=>setAction({...action,currency:e.target.value})} className={`${input} mt-2`}>{currencies.map(x=><option key={x}>{x}</option>)}</select></label></div>}{action.kind==="owner"&&<div className="mt-5"><label className="text-xs text-slate-400">Account Owner<select value={action.owner_id} onChange={e=>setAction({...action,owner_id:e.target.value})} className={`${input} mt-2`}><option value="">Unassigned</option>{owners.map(o=><option key={o.id} value={o.id}>{o.full_name}</option>)}</select></label></div>}<label className="mt-5 block text-xs text-slate-400">Reason / Control Note<textarea value={action.reason} onChange={e=>setAction({...action,reason:e.target.value})} className={`${input} mt-2 min-h-24`} placeholder={action.kind==="delete"?"Required deletion justification":"Reason for this controlled change"}/></label><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setAction(null)} className="rounded-xl border border-slate-700 px-5 py-2.5">Cancel</button><button disabled={busy} onClick={()=>void runAction()} className={`rounded-xl px-6 py-2.5 font-semibold disabled:opacity-50 ${action.kind==="delete"?"bg-red-700":"bg-blue-600"}`}>{busy?"Processing...":"Confirm Action"}</button></div></div></div>}
 </main>}
