"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {createQuotationFromOpportunity} from "@/lib/commercial-flow";

const field="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500";
const btn="rounded-xl border border-slate-700 px-3 py-2 text-xs font-semibold text-slate-200 hover:border-blue-500 hover:text-blue-300 disabled:opacity-40";
const money=new Intl.NumberFormat("en-US",{maximumFractionDigits:0});
export function OpportunitiesFlowPageV2(){
 const[rows,setRows]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[suppliers,setSuppliers]=useState<any[]>([]),[profiles,setProfiles]=useState<any[]>([]),[search,setSearch]=useState(""),[busy,setBusy]=useState(""),[notice,setNotice]=useState("");
 const[show,setShow]=useState(false),[form,setForm]=useState({title:"",customer_id:"",currency:"AED",estimated_value:"",probability:"50",priority:"medium",expected_close_date:"",next_action:"Confirm customer requirement and commercial scope"});
 const load=async()=>{setBusy("load");try{const s=createClient();const[o,c,su,p]=await Promise.all([s.from("opportunities").select("*,customers(company_name,status),profiles:owner_id(full_name),quotations:quotation_id(id,quotation_no,status,title)").order("updated_at",{ascending:false}),s.from("customers").select("id,company_name,status,customer_type").eq("status","active").order("company_name"),s.from("suppliers").select("id,company_name,status,kyc_status,kyc_expiry_date").order("company_name"),s.from("profiles").select("id,full_name,role,active").eq("active",true).order("full_name")]);for(const r of[o,c,su,p])if(r.error)throw r.error;setRows(o.data??[]);setCustomers(c.data??[]);setSuppliers(su.data??[]);setProfiles(p.data??[])}catch(e:any){setNotice(e?.message||"Unable to load opportunities.")}finally{setBusy("")}};
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>`${r.opportunity_no} ${r.title} ${r.customers?.company_name||""} ${r.profiles?.full_name||""}`.toLowerCase().includes(search.toLowerCase())),[rows,search]);
 const stats=useMemo(()=>{const open=rows.filter(r=>!["won","lost"].includes(r.stage));return{open:open.length,pipeline:open.reduce((n,r)=>n+Number(r.estimated_value||0),0),weighted:open.reduce((n,r)=>n+Number(r.estimated_value||0)*Number(r.probability||0)/100,0),won:rows.filter(r=>r.stage==="won").length,quotation:rows.filter(r=>r.stage==="quotation").length,approval:rows.filter(r=>r.stage==="approval").length}},[rows]);
 async function create(){if(!form.title.trim()||!form.customer_id){setNotice("Customer and title are required.");return}setBusy("create");try{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)throw new Error("Authentication required.");const no=`OPP-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`;const{error}=await s.from("opportunities").insert({opportunity_no:no,customer_id:form.customer_id,title:form.title.trim(),currency:form.currency,estimated_value:Number(form.estimated_value||0),stage:"lead",probability:Number(form.probability||0),expected_close_date:form.expected_close_date||null,owner_id:user.id,created_by:user.id,priority:form.priority,next_action:form.next_action.trim()});if(error)throw error;setShow(false);setForm({title:"",customer_id:"",currency:"AED",estimated_value:"",probability:"50",priority:"medium",expected_close_date:"",next_action:"Confirm customer requirement and commercial scope"});setNotice("Opportunity created.");await load()}catch(e:any){setNotice(e?.message||"Could not create opportunity.")}finally{setBusy("")}}
 async function quote(r:any){setBusy(r.id);try{await createQuotationFromOpportunity(r.id,null);setNotice("Draft quotation created and linked through Commercial Flow.");await load()}catch(e:any){setNotice(e?.message||"Could not create quotation.")}finally{setBusy("")}}
 return <main className="min-h-screen bg-[#070b14] p-5 text-white md:p-8"><header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-blue-400">VTC ONE · Commercial Origination</p><h1 className="mt-2 text-3xl font-bold">Opportunity Control Center</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">Qualify opportunities and hand them into the controlled quotation workflow. Quotation linkage and advanced stages are system-controlled.</p></div><div className="flex flex-wrap gap-2"><Link href="/commercial" className={btn}>Commercial Flow</Link><button onClick={()=>void load()} className={btn}>{busy==="load"?"Refreshing...":"Refresh"}</button><button onClick={()=>setShow(v=>!v)} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold">{show?"Close":"+ New Opportunity"}</button></div></header>
 {notice&&<div className="mt-5 rounded-xl border border-blue-500/30 bg-blue-500/10 p-3 text-sm text-blue-100">{notice}</div>}
 <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><K l="Open" v={String(stats.open)}/><K l="Pipeline" v={`AED ${money.format(stats.pipeline)}`}/><K l="Weighted" v={`AED ${money.format(stats.weighted)}`}/><K l="Quotation Stage" v={String(stats.quotation)}/><K l="Approval Stage" v={String(stats.approval)}/><K l="Won" v={String(stats.won)}/></section>
 {show&&<section className="mt-6 rounded-2xl border border-blue-500/30 bg-[#0d1423] p-5"><h2 className="font-semibold">Create Opportunity</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Opportunity title *" className={field}/><select value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})} className={field}><option value="">Active customer *</option>{customers.filter(c=>["customer","both"].includes(c.customer_type)).map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select><div className="grid grid-cols-[1fr_90px] gap-2"><input type="number" min="0" value={form.estimated_value} onChange={e=>setForm({...form,estimated_value:e.target.value})} placeholder="Estimated value" className={field}/><select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})} className={field}>{["AED","USD","EUR","GBP","CNY","INR"].map(x=><option key={x}>{x}</option>)}</select></div><input type="number" min="0" max="100" value={form.probability} onChange={e=>setForm({...form,probability:e.target.value})} placeholder="Probability %" className={field}/><input type="date" value={form.expected_close_date} onChange={e=>setForm({...form,expected_close_date:e.target.value})} className={field}/><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})} className={field}><option>low</option><option>medium</option><option>high</option><option>critical</option></select><input value={form.next_action} onChange={e=>setForm({...form,next_action:e.target.value})} placeholder="Next action" className={`${field} md:col-span-2`}/></div><div className="mt-4 flex justify-end"><button disabled={busy==="create"} onClick={()=>void create()} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold disabled:opacity-40">{busy==="create"?"Creating...":"Create Opportunity"}</button></div></section>}
 <section className="mt-6 rounded-2xl border border-slate-800 bg-[#0d1423] p-4"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search opportunity, customer or owner..." className={field}/></section>
 <section className="mt-4 overflow-hidden rounded-2xl border border-slate-800 bg-[#0d1423]"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-slate-950/50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Opportunity</th><th>Customer</th><th>Owner</th><th>Stage</th><th>Value</th><th>Probability</th><th>Next Action</th><th className="p-4 text-right">Control</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t border-slate-800"><td className="p-4"><b>{r.opportunity_no}</b><div className="text-xs text-slate-500">{r.title}</div></td><td>{r.customers?.company_name||"—"}</td><td>{r.profiles?.full_name||"—"}</td><td><Badge v={r.stage}/></td><td>{r.currency} {money.format(Number(r.estimated_value||0))}</td><td>{r.probability}%</td><td className="max-w-64 text-xs text-slate-400">{r.next_action||"—"}</td><td className="p-4 text-right">{r.quotations?<Link className={btn} href="/quotations">Open {r.quotations.quotation_no||"Draft Quote"}</Link>:!["won","lost"].includes(r.stage)?<button disabled={!!busy} onClick={()=>void quote(r)} className={btn}>{busy===r.id?"Creating...":"Create Quotation"}</button>:<span className="text-xs text-slate-500">Closed</span>}</td></tr>)}{!filtered.length&&<tr><td colSpan={8} className="p-10 text-center text-slate-500">No opportunities found.</td></tr>}</tbody></table></div></section>
 </main>
}
function K({l,v}:{l:string;v:string}){return <div className="rounded-2xl border border-slate-800 bg-[#0d1423] p-4"><p className="text-[11px] uppercase tracking-wider text-slate-500">{l}</p><p className="mt-2 text-xl font-bold">{v}</p></div>}
function Badge({v}:{v:string}){return <span className={`rounded-full border px-2 py-1 text-[10px] font-bold uppercase ${v==="won"?"border-emerald-500/30 bg-emerald-500/10 text-emerald-300":v==="lost"?"border-red-500/30 bg-red-500/10 text-red-300":"border-slate-700 bg-slate-900 text-slate-300"}`}>{v}</span>}
