"use client";

import { useMemo, useState } from "react";
import { commercialStages, type CommercialOpportunity, type CommercialPriority, type CommercialStage } from "@/lib/commercial-data";
import { useCommercialStore } from "@/hooks/useCommercialStore";

const money = new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 });

export function OpportunitiesPage() {
  const { opportunities, updateOpportunity, addOpportunity } = useCommercialStore();
  const [search, setSearch] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ title: "", company: "", value: "", currency: "AED", probability: "50", margin: "10", dueDate: "2026-08-10", priority: "medium" as CommercialPriority });

  const filtered = useMemo(() => opportunities.filter((item) => `${item.reference} ${item.title} ${item.company}`.toLowerCase().includes(search.toLowerCase())), [opportunities, search]);

  function create() {
    if (!form.title.trim() || !form.company.trim()) return;
    addOpportunity({ reference: `VTC-${new Date().getFullYear()}-${String(opportunities.length + 1).padStart(3, "0")}`, title: form.title.trim(), company: form.company.trim(), owner: "Massih Chitsaz", stage: "lead", value: Number(form.value) || 0, currency: form.currency, probability: Number(form.probability) || 0, marginPercent: Number(form.margin) || 0, nextAction: "Qualify opportunity and confirm requirements", dueDate: form.dueDate, priority: form.priority });
    setShowForm(false);
    setForm({ title: "", company: "", value: "", currency: "AED", probability: "50", margin: "10", dueDate: "2026-08-10", priority: "medium" });
  }

  return <main className="p-5 text-white md:p-8">
    <header className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-blue-400">Commercial Pipeline</p><h2 className="mt-2 text-3xl font-bold">Opportunities</h2><p className="mt-2 text-sm text-slate-400">Move commercial cases through qualification, quotation, negotiation and award.</p></div><button onClick={() => setShowForm(!showForm)} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold hover:bg-blue-500">{showForm ? "Close" : "+ New Opportunity"}</button></header>
    {showForm && <section className="mt-6 rounded-2xl border border-blue-500/30 bg-blue-500/5 p-6"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><input value={form.title} onChange={(e) => setForm({...form,title:e.target.value})} placeholder="Opportunity title" className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 outline-none focus:border-blue-500"/><input value={form.company} onChange={(e) => setForm({...form,company:e.target.value})} placeholder="Company" className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 outline-none focus:border-blue-500"/><input type="number" value={form.value} onChange={(e) => setForm({...form,value:e.target.value})} placeholder="Value" className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 outline-none focus:border-blue-500"/><select value={form.currency} onChange={(e) => setForm({...form,currency:e.target.value})} className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3"><option>AED</option><option>USD</option><option>EUR</option><option>IRR</option></select><input type="number" value={form.probability} onChange={(e)=>setForm({...form,probability:e.target.value})} placeholder="Probability %" className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3"/><input type="number" value={form.margin} onChange={(e)=>setForm({...form,margin:e.target.value})} placeholder="Margin %" className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3"/><input type="date" value={form.dueDate} onChange={(e)=>setForm({...form,dueDate:e.target.value})} className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3"/><select value={form.priority} onChange={(e)=>setForm({...form,priority:e.target.value as CommercialPriority})} className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></div><button onClick={create} className="mt-4 rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold">Create Opportunity</button></section>}
    <div className="mt-6"><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search reference, opportunity or company..." className="w-full rounded-xl border border-slate-800 bg-[#0d1423] px-4 py-3 outline-none focus:border-blue-500"/></div>
    <section className="mt-5 grid gap-4 2xl:grid-cols-4">{filtered.map((item: CommercialOpportunity) => <article key={item.id} className="rounded-2xl border border-slate-800 bg-[#0d1423] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-blue-400">{item.reference}</p><h3 className="mt-2 text-lg font-semibold">{item.title}</h3><p className="mt-1 text-sm text-slate-500">{item.company}</p></div><span className="rounded-full border border-slate-700 px-2 py-1 text-[10px] uppercase text-slate-400">{item.priority}</span></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-950/50 p-3"><p className="text-xs text-slate-500">Value</p><p className="mt-1 font-semibold">{item.currency} {money.format(item.value)}</p></div><div className="rounded-xl bg-slate-950/50 p-3"><p className="text-xs text-slate-500">Probability</p><p className="mt-1 font-semibold text-emerald-400">{item.probability}%</p></div></div><label className="mt-4 block text-xs text-slate-500">Stage<select value={item.stage} onChange={(e)=>updateOpportunity(item.id,{stage:e.target.value as CommercialStage})} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm capitalize">{commercialStages.map((stage)=><option key={stage.id} value={stage.id}>{stage.label}</option>)}</select></label><p className="mt-4 text-xs text-slate-500">Next action</p><p className="mt-1 text-sm text-slate-300">{item.nextAction}</p><p className="mt-4 text-xs text-slate-500">Due {item.dueDate} · Margin {item.marginPercent}%</p></article>)}</section>
  </main>;
}
