"use client";

import { useEffect, useMemo, useState } from "react";
import { listQuotationWorkspace, saveQuotation, type QuoteLine } from "@/lib/quotations";

type Kind = "trading" | "logistics";
const input = "w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500";
const line = (description = ""): QuoteLine => ({ description, qty: 1, unit: "Unit", cost: 0, sell: 0 });
const empty = () => ({ id:"", quotation_no:"", quotation_type:"trading" as Kind, customer_id:"", supplier_id:"", opportunity_id:"", title:"", contact_person:"", currency:"AED", valid_until:"", incoterm:"EXW", payment_terms:"As agreed", origin:"", destination:"", mode:"Sea", commodity:"", hs_code:"", packing_details:"", gross_weight:"", volume_details:"", notes:"", status:"draft", lines:[line()] });
const logisticsCharges = ["OCEAN FREIGHT","AIR FREIGHT","LAND TRANSPORT","THC / TERMINAL HANDLING","DELIVERY ORDER","BILL OF LADING FEE","CUSTOMS CLEARANCE","CUSTOMS INSPECTION","CUSTOMS DEPOSIT FEE","DOCUMENTATION","CROSS STUFFING","STORAGE","LIFT TRUCK / CRANE","PACKING / PALLETIZING","RE-PACKING","TRANSIT","VGM","SEAL SERVICE","GATE PASS","REEFER PLUG-IN","SERVICE CHARGES"];
const money = new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 });

export function QuotationWorkspaceV2(){
 const [data,setData]=useState<any>({quotations:[],customers:[],suppliers:[],opportunities:[]});
 const [f,setF]=useState<any>(empty());
 const [busy,setBusy]=useState(false);
 const [message,setMessage]=useState<{type:"ok"|"error"|"info",text:string}|null>(null);
 const [tab,setTab]=useState<"builder"|"saved">("builder");
 const [search,setSearch]=useState("");
 const load=async()=>{try{setData(await listQuotationWorkspace())}catch(e:any){setMessage({type:"error",text:e?.message||"Unable to load quotations."})}};
 useEffect(()=>{void load()},[]);
 const patch=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));
 const patchLine=(i:number,p:Partial<QuoteLine>)=>setF((x:any)=>({...x,lines:x.lines.map((r:QuoteLine,j:number)=>j===i?{...r,...p}:r)}));
 const totals=useMemo(()=>{const cost=f.lines.reduce((n:number,r:QuoteLine)=>n+Number(r.qty||0)*Number(r.cost||0),0);const sell=f.lines.reduce((n:number,r:QuoteLine)=>n+Number(r.qty||0)*Number(r.sell||0),0);return {cost,sell,profit:sell-cost,margin:sell?((sell-cost)/sell)*100:0}},[f.lines]);
 const save=async()=>{
  setBusy(true);setMessage({type:"info",text:"Saving quotation..."});
  try{
   const isDraft=f.status==="draft";
   const payload={...f,
    title:(f.title||"").trim() || (isDraft?"Untitled quotation":""),
    quotation_no:(f.quotation_no||"").trim()||null,
    customer_id:f.customer_id||null,supplier_id:f.supplier_id||null,opportunity_id:f.opportunity_id||null,
    lines:(f.lines||[]).filter((r:QuoteLine)=>r.description.trim()).length?f.lines:[line("Draft line")]
   };
   if(!isDraft){
    if(!payload.quotation_no) throw new Error("Quotation number is required before the quotation leaves Draft status.");
    if(!payload.customer_id) throw new Error("Customer is required before the quotation leaves Draft status.");
    if(!payload.title) throw new Error("Quotation title is required before the quotation leaves Draft status.");
    if(!payload.lines.some((r:QuoteLine)=>r.description.trim())) throw new Error("At least one quotation line is required.");
   }
   const q:any=await saveQuotation(payload as any);
   setF((x:any)=>({...x,id:q.id,quotation_no:q.quotation_no||"",title:q.title||payload.title}));
   await load();
   setMessage({type:"ok",text:q.quotation_no?`Quotation ${q.quotation_no} saved successfully.`:"Draft saved successfully without a quotation number."});
  }catch(e:any){setMessage({type:"error",text:e?.message||"Quotation could not be saved."})}finally{setBusy(false)}
 };
 const open=(q:any)=>{setF({id:q.id,quotation_no:q.quotation_no||"",quotation_type:q.quotation_type||"trading",customer_id:q.customer_id||"",supplier_id:q.supplier_id||"",opportunity_id:q.opportunity_id||"",title:q.title||"",contact_person:q.contact_person||"",currency:q.currency||"AED",valid_until:q.valid_until||"",incoterm:q.incoterm||"EXW",payment_terms:q.payment_terms||"As agreed",origin:q.origin||"",destination:q.destination||"",mode:q.mode||"Sea",commodity:q.commodity||"",hs_code:q.hs_code||"",packing_details:q.packing_details||"",gross_weight:q.gross_weight||"",volume_details:q.volume_details||"",notes:q.notes||"",status:q.status||"draft",lines:(q.quotation_items?.length?q.quotation_items.sort((a:any,b:any)=>a.line_no-b.line_no).map((r:any)=>({description:r.description,qty:Number(r.quantity),unit:r.unit||"Unit",cost:Number(r.unit_cost),sell:Number(r.unit_sell)})):[line()])});setTab("builder");setMessage({type:"info",text:`Editing ${q.quotation_no||"unnumbered draft"} · Rev ${q.revision||1}`})};
 const saved=(data.quotations||[]).filter((q:any)=>`${q.quotation_no||""} ${q.title||""} ${q.customers?.company_name||""}`.toLowerCase().includes(search.toLowerCase()));
 return <main className="p-5 text-white md:p-8 print:bg-white print:p-0 print:text-black">
  <div className="print:hidden">
   <header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.24em] text-blue-400">VTC Commercial</p><h1 className="mt-2 text-3xl font-bold">Quotation Management</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">Trading and logistics quotations with manual numbering, draft control, costing, margin and revision history.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>{setF(empty());setTab("builder");setMessage(null)}} className="rounded-xl border border-slate-700 px-4 py-3 text-sm">+ New Quotation</button><button onClick={()=>window.print()} className="rounded-xl border border-slate-700 px-4 py-3 text-sm">Export PDF</button></div></header>
   <div className="mt-6 flex gap-2"><button onClick={()=>setTab("builder")} className={`rounded-xl px-4 py-2 text-sm ${tab==="builder"?"bg-blue-600":"bg-slate-900"}`}>Builder</button><button onClick={()=>setTab("saved")} className={`rounded-xl px-4 py-2 text-sm ${tab==="saved"?"bg-blue-600":"bg-slate-900"}`}>Saved Quotations ({data.quotations?.length||0})</button></div>
   {message&&<div className={`mt-4 rounded-xl border px-4 py-3 text-sm ${message.type==="ok"?"border-emerald-800 bg-emerald-950/30 text-emerald-300":message.type==="error"?"border-red-800 bg-red-950/30 text-red-300":"border-blue-900 bg-blue-950/20 text-blue-300"}`}>{message.text}</div>}
   {tab==="saved"?<section className="mt-5 overflow-hidden rounded-2xl border border-slate-800 bg-[#0d1423]"><div className="border-b border-slate-800 p-4"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search quotation, customer or title" className={input}/></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Quotation</th><th>Customer</th><th>Type</th><th>Value</th><th>Margin</th><th>Status</th><th>Revision</th><th className="p-4 text-right">Action</th></tr></thead><tbody>{saved.map((q:any)=><tr key={q.id} className="border-t border-slate-800"><td className="p-4"><b>{q.quotation_no||"UNNUMBERED DRAFT"}</b><div className="text-xs text-slate-500">{q.title}</div></td><td>{q.customers?.company_name||"—"}</td><td className="capitalize">{q.quotation_type}</td><td>{q.currency} {money.format(Number(q.total_amount||0))}</td><td>{Number(q.margin_percent||0).toFixed(2)}%</td><td className="capitalize">{q.status}</td><td>Rev {q.revision||1}</td><td className="p-4 text-right"><button onClick={()=>open(q)} className="rounded-lg border border-slate-700 px-3 py-2">Open</button></td></tr>)}{!saved.length&&<tr><td colSpan={8} className="p-10 text-center text-slate-500">No quotations found.</td></tr>}</tbody></table></div></section>:
   <>
    <section className="mt-5 grid gap-3 sm:grid-cols-2"><button onClick={()=>patch("quotation_type","trading")} className={`rounded-2xl border p-5 text-left ${f.quotation_type==="trading"?"border-blue-500 bg-blue-500/10":"border-slate-800 bg-[#0d1423]"}`}><b>Trading Quotation</b><p className="mt-1 text-xs text-slate-400">Purchase and sale of goods</p></button><button onClick={()=>patch("quotation_type","logistics")} className={`rounded-2xl border p-5 text-left ${f.quotation_type==="logistics"?"border-blue-500 bg-blue-500/10":"border-slate-800 bg-[#0d1423]"}`}><b>Shipping & Logistics Quotation</b><p className="mt-1 text-xs text-slate-400">Freight, customs, transport and logistics services</p></button></section>
    <section className="mt-5 rounded-2xl border border-slate-800 bg-[#0d1423] p-5"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input value={f.quotation_no} onChange={e=>patch("quotation_no",e.target.value.toUpperCase())} placeholder="Quotation No. (manual / optional in draft)" className={`${input} font-mono`}/><select value={f.customer_id} onChange={e=>{patch("customer_id",e.target.value);const c=data.customers?.find((x:any)=>x.id===e.target.value);if(c)patch("contact_person",c.contact_person||"")}} className={input}><option value="">Customer</option>{data.customers?.map((x:any)=><option key={x.id} value={x.id}>{x.company_name}</option>)}</select><input value={f.contact_person} onChange={e=>patch("contact_person",e.target.value)} placeholder="Attention / Contact" className={input}/><input value={f.title} onChange={e=>patch("title",e.target.value)} placeholder="Quotation title / subject" className={input}/><select value={f.currency} onChange={e=>patch("currency",e.target.value)} className={input}>{["AED","USD","EUR","GBP","CNY","INR"].map(x=><option key={x}>{x}</option>)}</select><select value={f.status} onChange={e=>patch("status",e.target.value)} className={input}>{["draft","sent","review","accepted","rejected","expired","awarded"].map(x=><option key={x}>{x}</option>)}</select><input value={f.origin} onChange={e=>patch("origin",e.target.value)} placeholder="Origin" className={input}/><input value={f.destination} onChange={e=>patch("destination",e.target.value)} placeholder="Destination" className={input}/><input value={f.incoterm} onChange={e=>patch("incoterm",e.target.value)} placeholder="Incoterm" className={input}/><input value={f.payment_terms} onChange={e=>patch("payment_terms",e.target.value)} placeholder="Payment terms" className={input}/><input type="date" value={f.valid_until} onChange={e=>patch("valid_until",e.target.value)} className={input}/>{f.quotation_type==="logistics"?<select value={f.mode} onChange={e=>patch("mode",e.target.value)} className={input}>{["Sea","Air","Road","Rail","Multimodal","Courier"].map(x=><option key={x}>{x}</option>)}</select>:<input value={f.hs_code} onChange={e=>patch("hs_code",e.target.value)} placeholder="HS Code" className={input}/>}</div><div className="mt-3 grid gap-3 md:grid-cols-3"><input value={f.commodity} onChange={e=>patch("commodity",e.target.value)} placeholder="Commodity / Product" className={input}/><input value={f.gross_weight} onChange={e=>patch("gross_weight",e.target.value)} placeholder="Gross weight" className={input}/><input value={f.volume_details} onChange={e=>patch("volume_details",e.target.value)} placeholder="CBM / Container / Package details" className={input}/></div></section>
    {f.quotation_type==="logistics"&&<section className="mt-5 rounded-2xl border border-slate-800 bg-[#0d1423] p-5"><h3 className="font-semibold">Optional Logistics Charges</h3><div className="mt-4 flex flex-wrap gap-2">{logisticsCharges.map(c=>{const on=f.lines.some((r:QuoteLine)=>r.description===c);return <button key={c} disabled={on} onClick={()=>!on&&patch("lines",[...f.lines,line(c)])} className={`rounded-lg border px-3 py-2 text-xs ${on?"border-emerald-900 bg-emerald-950/30 text-emerald-400":"border-slate-700 text-slate-300 hover:border-blue-500"}`}>{on?"✓ ":"+ "}{c}</button>})}</div></section>}
    <section className="mt-5 rounded-2xl border border-slate-800 bg-[#0d1423] p-5"><div className="flex items-center justify-between"><h3 className="font-semibold">Quotation Lines</h3><button onClick={()=>patch("lines",[...f.lines,line()])} className="text-sm text-blue-400">+ Custom Line</button></div><div className="mt-4 space-y-3">{f.lines.map((r:QuoteLine,i:number)=><div key={i} className="grid gap-2 lg:grid-cols-[2fr_.55fr_.65fr_1fr_1fr_auto]"><input value={r.description} onChange={e=>patchLine(i,{description:e.target.value})} placeholder="Description" className={input}/><input type="number" min="0" value={r.qty} onChange={e=>patchLine(i,{qty:Number(e.target.value)})} className={input}/><input value={r.unit} onChange={e=>patchLine(i,{unit:e.target.value})} className={input}/><input type="number" min="0" value={r.cost} onChange={e=>patchLine(i,{cost:Number(e.target.value)})} placeholder="Internal cost" className={input}/><input type="number" min="0" value={r.sell} onChange={e=>patchLine(i,{sell:Number(e.target.value)})} placeholder="Selling rate" className={input}/><button onClick={()=>patch("lines",f.lines.filter((_:QuoteLine,j:number)=>j!==i))} className="px-3 text-red-400">×</button></div>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-4">{[["Internal Cost",totals.cost],["Selling Total",totals.sell],["Gross Profit",totals.profit],["Margin %",totals.margin]].map(([l,v])=><div key={String(l)} className="rounded-xl bg-slate-950 p-4"><p className="text-xs text-slate-500">{l}</p><b className={l==="Gross Profit"||l==="Margin %"?"text-emerald-400":""}>{l==="Margin %"?Number(v).toFixed(2):`${f.currency} ${money.format(Number(v))}`}</b></div>)}</div><textarea value={f.notes} onChange={e=>patch("notes",e.target.value)} placeholder="Terms, exclusions and commercial notes" className={`${input} mt-4 min-h-28`}/><div className="mt-5 flex flex-col items-stretch gap-2 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-slate-500">Drafts can be saved incomplete and without a quotation number. Formal statuses require the key commercial fields.</p><button type="button" disabled={busy} onClick={()=>void save()} className="rounded-xl bg-blue-600 px-7 py-3 font-semibold hover:bg-blue-500 disabled:opacity-50">{busy?"Saving...":f.id?"Save New Revision":"Save Quotation"}</button></div></section>
   </>}
  </div>
  <section className="hidden print:block"><div className="flex justify-between border-b pb-5"><div><img src="/vtc-group-logo.svg" alt="VTC Group" className="h-16"/></div><div className="text-right"><h1 className="text-2xl font-bold">QUOTATION</h1><p>{f.quotation_no||"DRAFT"}</p></div></div><h2 className="mt-6 text-lg font-semibold">{f.title||"Quotation"}</h2><table className="mt-5 w-full text-sm"><thead><tr className="border-y"><th className="py-3 text-left">Description</th><th>Qty</th><th>Unit</th><th className="text-right">Rate</th><th className="text-right">Total</th></tr></thead><tbody>{f.lines.filter((r:QuoteLine)=>r.description.trim()).map((r:QuoteLine,i:number)=><tr key={i} className="border-b"><td className="py-3">{r.description}</td><td className="text-center">{r.qty}</td><td className="text-center">{r.unit}</td><td className="text-right">{money.format(r.sell)}</td><td className="text-right">{money.format(r.qty*r.sell)}</td></tr>)}</tbody></table><div className="mt-5 text-right text-lg font-bold">Grand Total: {f.currency} {money.format(totals.sell)}</div><div className="mt-8 whitespace-pre-wrap text-sm">{f.notes}</div><div className="mt-16 flex justify-end"><div className="w-72 border-t pt-3 text-center"><b>Commercial Manager</b><br/>VTC Group</div></div></section>
 </main>
}
