"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {listQuotationWorkspace,saveQuotation,type QuoteLine} from "@/lib/quotations";
import {convertQuotationToDeal,decideQuotation,getCommercialFlowPermissions,submitQuotationForReview} from "@/lib/commercial-flow";

const field="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500 disabled:opacity-60";
const btn="rounded-xl border border-slate-700 px-3 py-2 text-xs font-semibold text-slate-200 hover:border-blue-500 hover:text-blue-300 disabled:opacity-40";
const money=new Intl.NumberFormat("en-US",{maximumFractionDigits:2});
const line=():QuoteLine=>({description:"",qty:1,unit:"Unit",cost:0,sell:0});
const empty=()=>({id:"",quotation_no:"",quotation_type:"trading",customer_id:"",supplier_id:"",opportunity_id:"",title:"",contact_person:"",currency:"AED",valid_until:"",incoterm:"EXW",payment_terms:"As agreed",origin:"",destination:"",mode:"Sea",commodity:"",hs_code:"",packing_details:"",gross_weight:"",volume_details:"",notes:"",status:"draft",revision:1,lines:[line()]});

export function QuotationWorkspaceV4(){
 const[data,setData]=useState<any>({quotations:[],customers:[],suppliers:[],opportunities:[]}),[f,setF]=useState<any>(empty()),[busy,setBusy]=useState(""),[notice,setNotice]=useState(""),[tab,setTab]=useState<"builder"|"saved">("builder"),[search,setSearch]=useState(""),[permissions,setPermissions]=useState({role:"unknown",canControl:false,canWrite:false});
 const load=async()=>{setBusy("load");try{const[d,p]=await Promise.all([listQuotationWorkspace(),getCommercialFlowPermissions()]);setData(d);setPermissions(p)}catch(e:any){setNotice(e?.message||"Unable to load quotations.")}finally{setBusy("")}};
 useEffect(()=>{void load()},[]);
 const patch=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));const patchLine=(i:number,p:Partial<QuoteLine>)=>setF((x:any)=>({...x,lines:x.lines.map((r:QuoteLine,n:number)=>n===i?{...r,...p}:r)}));
 const totals=useMemo(()=>{const cost=f.lines.reduce((n:number,r:QuoteLine)=>n+Number(r.qty||0)*Number(r.cost||0),0),sell=f.lines.reduce((n:number,r:QuoteLine)=>n+Number(r.qty||0)*Number(r.sell||0),0);return{cost,sell,profit:sell-cost,margin:sell?((sell-cost)/sell)*100:0}},[f.lines]);
 const editable=["draft","rejected"].includes(f.status);const approvedDeal=data.quotations.find((q:any)=>q.id===f.id)?.deals?.[0];
 const validSuppliers=data.suppliers.filter((x:any)=>x.status==="active"&&x.kyc_status==="approved"&&(!x.kyc_expiry_date||x.kyc_expiry_date>=new Date().toISOString().slice(0,10)));
 async function save(){if(!editable){setNotice("This quotation is workflow-controlled and cannot be edited in its current status.");return}setBusy("save");try{const q:any=await saveQuotation({...f,quotation_no:f.quotation_no||null,customer_id:f.customer_id||null,supplier_id:f.supplier_id||null,opportunity_id:f.opportunity_id||null,valid_until:f.valid_until||null});setF((x:any)=>({...x,id:q.id,status:q.status,revision:q.revision,quotation_no:q.quotation_no||""}));setNotice(q.quotation_no?`Quotation ${q.quotation_no} saved · Rev ${q.revision}.`:"Draft saved.");await load()}catch(e:any){setNotice(e?.message||"Could not save quotation.")}finally{setBusy("")}}
 async function action(key:string,fn:()=>Promise<any>,ok:string){setBusy(key);try{const q:any=await fn();if(q?.id&&q?.status)setF((x:any)=>({...x,status:q.status,revision:q.revision??x.revision}));setNotice(ok);await load()}catch(e:any){setNotice(e?.message||"Action failed.")}finally{setBusy("")}}
 function open(q:any){setF({id:q.id,quotation_no:q.quotation_no||"",quotation_type:q.quotation_type||"trading",customer_id:q.customer_id||"",supplier_id:q.supplier_id||"",opportunity_id:q.opportunity_id||"",title:q.title||"",contact_person:q.contact_person||"",currency:q.currency||"AED",valid_until:q.valid_until||"",incoterm:q.incoterm||"EXW",payment_terms:q.payment_terms||"As agreed",origin:q.origin||"",destination:q.destination||"",mode:q.mode||"Sea",commodity:q.commodity||"",hs_code:q.hs_code||"",packing_details:q.packing_details||"",gross_weight:q.gross_weight||"",volume_details:q.volume_details||"",notes:q.notes||"",status:q.status||"draft",revision:q.revision||1,lines:q.quotation_items?.length?q.quotation_items.sort((a:any,b:any)=>a.line_no-b.line_no).map((r:any)=>({description:r.description,qty:Number(r.quantity),unit:r.unit||"Unit",cost:Number(r.unit_cost),sell:Number(r.unit_sell)})):[line()]});setTab("builder");setNotice(`Opened ${q.quotation_no||"draft"} · Rev ${q.revision||1}`)}
 const saved=data.quotations.filter((q:any)=>`${q.quotation_no||""} ${q.title||""} ${q.customers?.company_name||""}`.toLowerCase().includes(search.toLowerCase()));
 return <main className="min-h-screen bg-[#070b14] p-5 text-white md:p-8 print:bg-white print:text-black"><header className="print:hidden flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-blue-400">VTC ONE · Controlled Quotation</p><h1 className="mt-2 text-3xl font-bold">Quotation Workspace V4</h1><p className="mt-2 max-w-4xl text-sm text-slate-400">Draft and revision saving is separate from commercial approval. Status cannot be edited manually; every transition is controlled and audited.</p></div><div className="flex flex-wrap gap-2"><Link href="/commercial" className={btn}>Commercial Flow</Link><button onClick={()=>{setF(empty());setTab("builder");setNotice("")}} className={btn}>+ New Quotation</button><button onClick={()=>window.print()} className={btn}>Print / PDF</button><button onClick={()=>void load()} className={btn}>{busy==="load"?"Refreshing...":"Refresh"}</button></div></header>
 {notice&&<div className="print:hidden mt-5 rounded-xl border border-blue-500/30 bg-blue-500/10 p-3 text-sm text-blue-100">{notice}</div>}
 <div className="print:hidden mt-5 flex gap-2"><button onClick={()=>setTab("builder")} className={tab==="builder"?"rounded-xl bg-blue-600 px-4 py-2 text-sm":btn}>Builder</button><button onClick={()=>setTab("saved")} className={tab==="saved"?"rounded-xl bg-blue-600 px-4 py-2 text-sm":btn}>Saved ({data.quotations.length})</button></div>
 {tab==="saved"?<section className="print:hidden mt-5 overflow-hidden rounded-2xl border border-slate-800 bg-[#0d1423]"><div className="p-4"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search quotation, customer or title" className={field}/></div><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead className="bg-slate-950/50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Quotation</th><th>Customer</th><th>Supplier</th><th>Value</th><th>Margin</th><th>Status</th><th>Revision</th><th className="p-4 text-right">Action</th></tr></thead><tbody>{saved.map((q:any)=><tr key={q.id} className="border-t border-slate-800"><td className="p-4"><b>{q.quotation_no||"Unnumbered Draft"}</b><div className="text-xs text-slate-500">{q.title}</div></td><td>{q.customers?.company_name||"—"}</td><td>{q.suppliers?.company_name||"—"}</td><td>{q.currency} {money.format(Number(q.total_amount||0))}</td><td>{Number(q.margin_percent||0).toFixed(1)}%</td><td><Badge v={q.status}/></td><td>Rev {q.revision||1}</td><td className="p-4 text-right"><button onClick={()=>open(q)} className={btn}>Open</button></td></tr>)}{!saved.length&&<tr><td colSpan={8} className="p-10 text-center text-slate-500">No quotations found.</td></tr>}</tbody></table></div></section>:<>
 <section className="mt-5 rounded-2xl border border-slate-800 bg-[#0d1423] p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs uppercase tracking-wider text-slate-500">Workflow Status</p><div className="mt-2 flex items-center gap-3"><Badge v={f.status}/><span className="text-xs text-slate-500">Rev {f.revision||1} · Role {permissions.role}</span></div></div><div className="print:hidden flex flex-wrap gap-2"><button disabled={!editable||busy==="save"} onClick={()=>void save()} className={btn}>{busy==="save"?"Saving...":f.id?"Save Revision":"Save Draft"}</button>{f.id&&editable&&<button disabled={!!busy} onClick={()=>void action("submit",()=>submitQuotationForReview(f.id,"Commercial review"),"Submitted for commercial review.")} className={btn}>Submit Review</button>}{f.id&&f.status==="review"&&permissions.canControl&&<><button disabled={!!busy} onClick={()=>void action("approve",()=>decideQuotation(f.id,"approved","Commercial approval"),"Quotation approved.")} className={btn}>Approve</button><button disabled={!!busy} onClick={()=>{const r=window.prompt("Rejection reason");if(r)void action("reject",()=>decideQuotation(f.id,"rejected",r),"Quotation rejected for revision.")}} className={btn}>Reject</button></>}{f.id&&f.status==="approved"&&!approvedDeal&&<button disabled={!!busy} onClick={()=>void action("deal",()=>convertQuotationToDeal(f.id),"Draft Deal created from approved quotation.")} className={btn}>Convert to Deal</button>}{approvedDeal&&<Link href="/deals" className={btn}>Open Deal</Link>}</div></div></section>
 <section className="mt-5 rounded-2xl border border-slate-800 bg-[#0d1423] p-5"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input disabled={!editable} value={f.quotation_no} onChange={e=>patch("quotation_no",e.target.value.toUpperCase())} placeholder="Quotation No. * before review" className={field}/><select disabled={!editable} value={f.customer_id} onChange={e=>patch("customer_id",e.target.value)} className={field}><option value="">Customer</option>{data.customers.filter((x:any)=>x.status==="active").map((x:any)=><option key={x.id} value={x.id}>{x.company_name}</option>)}</select><select disabled={!editable} value={f.supplier_id} onChange={e=>patch("supplier_id",e.target.value)} className={field}><option value="">Supplier optional</option>{validSuppliers.map((x:any)=><option key={x.id} value={x.id}>{x.company_name}</option>)}</select><input disabled={!editable} value={f.title} onChange={e=>patch("title",e.target.value)} placeholder="Title / subject" className={field}/><select disabled={!editable} value={f.quotation_type} onChange={e=>patch("quotation_type",e.target.value)} className={field}><option value="trading">Trading</option><option value="logistics">Logistics</option></select><select disabled={!editable} value={f.currency} onChange={e=>patch("currency",e.target.value)} className={field}>{["AED","USD","EUR","GBP","CNY","INR"].map(x=><option key={x}>{x}</option>)}</select><input disabled={!editable} type="date" value={f.valid_until} onChange={e=>patch("valid_until",e.target.value)} className={field}/><input disabled={!editable} value={f.contact_person} onChange={e=>patch("contact_person",e.target.value)} placeholder="Contact / attention" className={field}/><input disabled={!editable} value={f.origin} onChange={e=>patch("origin",e.target.value)} placeholder="Origin" className={field}/><input disabled={!editable} value={f.destination} onChange={e=>patch("destination",e.target.value)} placeholder="Destination" className={field}/><input disabled={!editable} value={f.incoterm} onChange={e=>patch("incoterm",e.target.value)} placeholder="Incoterm" className={field}/><input disabled={!editable} value={f.payment_terms} onChange={e=>patch("payment_terms",e.target.value)} placeholder="Payment terms" className={field}/><input disabled={!editable} value={f.commodity} onChange={e=>patch("commodity",e.target.value)} placeholder="Commodity" className={field}/><select disabled={!editable} value={f.mode} onChange={e=>patch("mode",e.target.value)} className={field}>{["Sea","Air","Road","Rail","Multimodal","Courier"].map(x=><option key={x}>{x}</option>)}</select><input disabled={!editable} value={f.gross_weight} onChange={e=>patch("gross_weight",e.target.value)} placeholder="Gross weight" className={field}/><input disabled={!editable} value={f.volume_details} onChange={e=>patch("volume_details",e.target.value)} placeholder="CBM / containers / packages" className={field}/></div></section>
 <section className="mt-5 rounded-2xl border border-slate-800 bg-[#0d1423] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Quotation Lines</h2>{editable&&<button onClick={()=>patch("lines",[...f.lines,line()])} className={btn}>+ Add Line</button>}</div><div className="mt-4 space-y-3">{f.lines.map((r:QuoteLine,i:number)=><div key={i} className="grid gap-2 rounded-xl border border-slate-800 p-3 md:grid-cols-[2fr_.55fr_.7fr_.8fr_.8fr_auto]"><input disabled={!editable} value={r.description} onChange={e=>patchLine(i,{description:e.target.value})} placeholder="Description" className={field}/><input disabled={!editable} type="number" min="0" step="any" value={r.qty} onChange={e=>patchLine(i,{qty:Number(e.target.value)})} className={field}/><input disabled={!editable} value={r.unit} onChange={e=>patchLine(i,{unit:e.target.value})} className={field}/><input disabled={!editable} type="number" min="0" step="any" value={r.cost} onChange={e=>patchLine(i,{cost:Number(e.target.value)})} placeholder="Cost" className={field}/><input disabled={!editable} type="number" min="0" step="any" value={r.sell} onChange={e=>patchLine(i,{sell:Number(e.target.value)})} placeholder="Sell" className={field}/>{editable&&<button disabled={f.lines.length===1} onClick={()=>patch("lines",f.lines.filter((_:any,n:number)=>n!==i))} className={btn}>Remove</button>}</div>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-4"><K l="Cost" v={`${f.currency} ${money.format(totals.cost)}`}/><K l="Sell" v={`${f.currency} ${money.format(totals.sell)}`}/><K l="Gross Profit" v={`${f.currency} ${money.format(totals.profit)}`}/><K l="Margin" v={`${totals.margin.toFixed(2)}%`}/></div></section>
 <section className="mt-5 rounded-2xl border border-slate-800 bg-[#0d1423] p-5"><textarea disabled={!editable} value={f.notes} onChange={e=>patch("notes",e.target.value)} placeholder="Commercial notes, exclusions, assumptions and commitments" className={`${field} min-h-28`}/></section>
 </>}
 </main>
}
function Badge({v}:{v:string}){const good=v==="approved",bad=["rejected","expired"].includes(v);return <span className={`rounded-full border px-3 py-1 text-[10px] font-bold uppercase ${good?"border-emerald-500/30 bg-emerald-500/10 text-emerald-300":bad?"border-red-500/30 bg-red-500/10 text-red-300":"border-slate-700 bg-slate-900 text-slate-300"}`}>{v}</span>}
function K({l,v}:{l:string;v:string}){return <div className="rounded-xl border border-slate-800 bg-slate-950/40 p-3"><p className="text-xs text-slate-500">{l}</p><p className="mt-1 font-semibold">{v}</p></div>}
