"use client";

import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {assignSupplierManager,createSupplier,deleteSupplier,getSupplierAccess,getSupplierEvents,getSupplierSnapshot,getSuppliers,rateSupplier,setSupplierKyc,setSupplierStatus,setSupplierTerms,updateSupplier,type KycStatus,type Supplier,type SupplierAccess,type SupplierEvent,type SupplierSnapshot,type SupplierStatus} from "@/lib/suppliers";

type Owner={id:string;full_name:string|null};
const field="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500";
const currencies=["AED","USD","EUR","GBP","CNY","INR","IRR"];
const empty={supplier_code:"",company_name:"",contact_person:"",email:"",phone:"",website:"",country:"",city:"",address:"",tax_number:"",registration_number:"",category:"",notes:""};
const fmt=(n:number,c="AED")=>`${c} ${new Intl.NumberFormat("en-US",{maximumFractionDigits:0}).format(Number(n||0))}`;
const days=(d:string|null)=>d?Math.ceil((new Date(d).getTime()-Date.now())/86400000):null;
const risk=(s:Supplier)=>{let x=0;if(s.status==="blocked")x+=45;else if(s.status==="inactive")x+=15;else if(s.status==="pending")x+=10;if(s.kyc_status==="rejected")x+=45;else if(s.kyc_status==="expired")x+=30;else if(s.kyc_status!=="approved")x+=15;const k=days(s.kyc_expiry_date);if(k!==null&&k<=30)x+=20;if(Number(s.rating||0)>0&&Number(s.rating)<3)x+=20;if(!s.registration_number)x+=5;if(!s.tax_number)x+=5;return Math.min(100,x)};
const badge=(v:string)=>v==="active"||v==="approved"?"border-emerald-700 bg-emerald-950/40 text-emerald-300":v==="blocked"||v==="rejected"||v==="expired"?"border-red-800 bg-red-950/40 text-red-300":v==="pending"?"border-amber-800 bg-amber-950/40 text-amber-300":"border-slate-700 bg-slate-900 text-slate-300";
function Stat({label,value,sub}:{label:string;value:any;sub?:string}){return <div className="rounded-2xl border border-slate-800 bg-[#0d1423] p-4"><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p>{sub&&<p className="mt-1 text-xs text-slate-500">{sub}</p>}</div>}
function Input({label,value,onChange}:{label:string;value:any;onChange:(v:string)=>void}){return <label className="text-xs text-slate-400">{label}<input value={value??""} onChange={e=>onChange(e.target.value)} className={`${field} mt-2`}/></label>}

export function SupplierControlCenter(){
 const[rows,setRows]=useState<Supplier[]>([]),[owners,setOwners]=useState<Owner[]>([]),[access,setAccess]=useState<SupplierAccess|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[q,setQ]=useState(""),[status,setStatus]=useState("all"),[kyc,setKyc]=useState("all"),[riskBand,setRiskBand]=useState("all"),[form,setForm]=useState<any|null>(null),[editing,setEditing]=useState<Supplier|null>(null),[selected,setSelected]=useState<Supplier|null>(null),[snapshot,setSnapshot]=useState<SupplierSnapshot|null>(null),[events,setEvents]=useState<SupplierEvent[]>([]),[action,setAction]=useState<any|null>(null);
 const load=async()=>{setLoading(true);setError(null);try{const s=createClient();const[a,r,p]=await Promise.all([getSupplierAccess(),getSuppliers(),s.from("profiles").select("id,full_name").eq("active",true).order("full_name")]);setAccess(a);setRows(r);setOwners((p.data??[]) as Owner[])}catch(e:any){setError(e.message||"Could not load supplier control center.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const owner=(id:string|null)=>owners.find(x=>x.id===id)?.full_name||"Unassigned";
 const filtered=useMemo(()=>rows.filter(s=>{const rb=risk(s)>=60?"high":risk(s)>=30?"watch":"normal";return(status==="all"||s.status===status)&&(kyc==="all"||s.kyc_status===kyc)&&(riskBand==="all"||rb===riskBand)&&`${s.company_name} ${s.supplier_code||""} ${s.contact_person||""} ${s.country||""} ${s.category||""}`.toLowerCase().includes(q.toLowerCase())}),[rows,q,status,kyc,riskBand]);
 const stats=useMemo(()=>({total:rows.length,active:rows.filter(x=>x.status==="active").length,approved:rows.filter(x=>x.kyc_status==="approved").length,expiring:rows.filter(x=>{const d=days(x.kyc_expiry_date);return d!==null&&d>=0&&d<=30}).length,blocked:rows.filter(x=>x.status==="blocked").length,high:rows.filter(x=>risk(x)>=60).length,unassigned:rows.filter(x=>!x.account_manager_id).length}),[rows]);
 const open360=async(s:Supplier)=>{setSelected(s);setSnapshot(null);setEvents([]);setError(null);try{const[sn,ev]=await Promise.all([getSupplierSnapshot(s.id),getSupplierEvents(s.id)]);setSnapshot(sn);setEvents(ev)}catch(e:any){setError(e.message)}};
 const refreshSelected=async()=>{if(!selected)return;const all=await getSuppliers();setRows(all);const fresh=all.find(x=>x.id===selected.id)||null;setSelected(fresh);if(fresh){const[sn,ev]=await Promise.all([getSupplierSnapshot(fresh.id),getSupplierEvents(fresh.id)]);setSnapshot(sn);setEvents(ev)}};
 const startForm=(s?:Supplier)=>{setEditing(s||null);setForm(s?{...empty,...s}:structuredClone(empty));setNotice(null);setError(null)};
 const save=async()=>{if(!form?.company_name?.trim())return setError("Company name is required.");setBusy(true);setError(null);try{editing?await updateSupplier(editing.id,form):await createSupplier(form);setForm(null);setEditing(null);setNotice(editing?"Supplier master updated.":"Supplier created in Pending KYC status.");await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const run=async()=>{if(!selected||!action)return;setBusy(true);setError(null);try{if(action.kind==="status")await setSupplierStatus(selected.id,action.value,action.reason);if(action.kind==="kyc")await setSupplierKyc(selected.id,action.value,action.expiry||null,action.reason);if(action.kind==="terms")await setSupplierTerms(selected.id,action.currency,action.terms,action.reason);if(action.kind==="owner")await assignSupplierManager(selected.id,action.owner_id||null,action.reason);if(action.kind==="rating")await rateSupplier(selected.id,Number(action.rating),action.reason);if(action.kind==="delete"){await deleteSupplier(selected.id,action.reason);setSelected(null);setSnapshot(null);setEvents([])}setAction(null);setNotice("Supplier control action completed and audited.");await refreshSelected().catch(()=>load())}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 return <main className="p-5 text-white md:p-8">
  <header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-blue-400">VTC ONE · Vendor Governance</p><h1 className="mt-2 text-3xl font-bold">Supplier Control Center</h1><p className="mt-2 max-w-4xl text-sm text-slate-400">KYC, commercial terms, ownership, supplier performance, operational exposure and controlled vendor lifecycle in one workspace.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-xl border border-slate-700 px-4 py-3 text-sm">Refresh</button>{access?.canWrite&&<button onClick={()=>startForm()} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold">+ New Supplier</button>}</div></header>
  {access&&<div className="mt-4 flex flex-wrap gap-2 text-xs"><span className="rounded-full border border-slate-700 px-3 py-1">Role: {access.role}</span><span className={`rounded-full border px-3 py-1 ${access.canWrite?"border-emerald-800 text-emerald-300":"border-slate-700 text-slate-400"}`}>{access.canWrite?"Operational Access":"Read Only"}</span>{access.canControl&&<span className="rounded-full border border-blue-800 px-3 py-1 text-blue-300">Vendor Controller</span>}{access.canControlTerms&&<span className="rounded-full border border-amber-800 px-3 py-1 text-amber-300">Commercial Terms</span>}</div>}
  {notice&&<div className="mt-4 rounded-xl border border-blue-800 bg-blue-950/30 p-3 text-sm text-blue-200">{notice}</div>}{error&&<div className="mt-4 rounded-xl border border-red-800 bg-red-950/30 p-3 text-sm text-red-200">{error}</div>}
  <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-7"><Stat label="Suppliers" value={stats.total}/><Stat label="Active" value={stats.active}/><Stat label="KYC Approved" value={stats.approved}/><Stat label="KYC ≤30 Days" value={stats.expiring}/><Stat label="Blocked" value={stats.blocked}/><Stat label="High Risk" value={stats.high}/><Stat label="Unassigned" value={stats.unassigned}/></section>
  <section className="mt-5 rounded-2xl border border-slate-800 bg-[#0d1423] p-4"><div className="grid gap-3 xl:grid-cols-[1fr_180px_180px_180px]"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search supplier, code, contact, country or category..." className={field}/><select value={status} onChange={e=>setStatus(e.target.value)} className={field}><option value="all">All statuses</option>{["pending","active","inactive","blocked"].map(x=><option key={x}>{x}</option>)}</select><select value={kyc} onChange={e=>setKyc(e.target.value)} className={field}><option value="all">All KYC</option>{["pending","approved","expired","rejected"].map(x=><option key={x}>{x}</option>)}</select><select value={riskBand} onChange={e=>setRiskBand(e.target.value)} className={field}><option value="all">All risk levels</option><option value="normal">Normal</option><option value="watch">Watch</option><option value="high">High</option></select></div></section>
  <section className="mt-5 overflow-hidden rounded-2xl border border-slate-800 bg-[#0d1423]"><div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-left text-sm"><thead className="border-b border-slate-800 text-xs uppercase text-slate-500"><tr><th className="p-4">Supplier</th><th>Category</th><th>Manager</th><th>KYC</th><th>Terms</th><th>Risk</th><th>Status</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={8} className="p-12 text-center text-slate-500">Loading supplier master...</td></tr>:filtered.length?filtered.map(s=><tr key={s.id} className="border-b border-slate-800/80"><td className="p-4"><button onClick={()=>void open360(s)} className="font-semibold text-blue-400">{s.company_name}</button><p className="mt-1 text-xs text-slate-500">{s.supplier_code||"No code"} · {[s.city,s.country].filter(Boolean).join(", ")||"No location"}</p></td><td>{s.category||"—"}</td><td>{owner(s.account_manager_id)}</td><td><span className={`rounded-lg border px-2 py-1 text-xs capitalize ${badge(s.kyc_status||"pending")}`}>{s.kyc_status||"pending"}</span><p className="mt-1 text-xs text-slate-500">{s.kyc_expiry_date?`Exp ${s.kyc_expiry_date}`:"No expiry"}</p></td><td>{s.currency||"AED"}<p className="text-xs text-slate-500">{s.payment_terms||"Not set"}</p></td><td><b className={risk(s)>=60?"text-red-300":risk(s)>=30?"text-amber-300":"text-emerald-300"}>{risk(s)}/100</b></td><td><span className={`rounded-lg border px-2 py-1 text-xs capitalize ${badge(s.status)}`}>{s.status}</span></td><td className="p-4"><div className="flex justify-end gap-2"><button onClick={()=>void open360(s)} className="rounded-lg border border-blue-900 px-3 py-2 text-xs text-blue-300">Open 360</button>{access?.canWrite&&<button onClick={()=>startForm(s)} className="rounded-lg border border-slate-700 px-3 py-2 text-xs">Edit Master</button>}</div></td></tr>):<tr><td colSpan={8} className="p-12 text-center text-slate-500">No suppliers match the current filters.</td></tr>}</tbody></table></div></section>
  {form&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/80 p-4 md:p-8"><div className="mx-auto max-w-5xl rounded-3xl border border-slate-700 bg-[#0b1120] p-6"><div className="flex justify-between"><div><p className="text-xs uppercase tracking-wider text-blue-400">Supplier Master</p><h2 className="mt-1 text-2xl font-bold">{editing?`Edit ${editing.company_name}`:"Create Supplier"}</h2><p className="mt-1 text-xs text-slate-500">Status, KYC, commercial terms, rating and account manager are controlled separately.</p></div><button onClick={()=>setForm(null)} className="text-2xl">×</button></div><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><Input label="Supplier Code" value={form.supplier_code} onChange={v=>setForm({...form,supplier_code:v})}/><Input label="Company Name *" value={form.company_name} onChange={v=>setForm({...form,company_name:v})}/><Input label="Category / Service" value={form.category} onChange={v=>setForm({...form,category:v})}/><Input label="Contact Person" value={form.contact_person} onChange={v=>setForm({...form,contact_person:v})}/><Input label="Email" value={form.email} onChange={v=>setForm({...form,email:v})}/><Input label="Phone" value={form.phone} onChange={v=>setForm({...form,phone:v})}/><Input label="Website" value={form.website} onChange={v=>setForm({...form,website:v})}/><Input label="Country" value={form.country} onChange={v=>setForm({...form,country:v})}/><Input label="City" value={form.city} onChange={v=>setForm({...form,city:v})}/><Input label="Registration No." value={form.registration_number} onChange={v=>setForm({...form,registration_number:v})}/><Input label="Tax / VAT No." value={form.tax_number} onChange={v=>setForm({...form,tax_number:v})}/><Input label="Address" value={form.address} onChange={v=>setForm({...form,address:v})}/></div><textarea value={form.notes||""} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Internal vendor notes" className={`${field} mt-4 min-h-28`}/><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setForm(null)} className="rounded-xl border border-slate-700 px-5 py-2.5">Cancel</button><button disabled={busy} onClick={()=>void save()} className="rounded-xl bg-blue-600 px-6 py-2.5 font-semibold disabled:opacity-50">{busy?"Saving...":editing?"Save Master":"Create Pending Supplier"}</button></div></div></div>}
  {selected&&<div className="fixed inset-0 z-40 overflow-y-auto bg-black/80 p-4 md:p-8"><div className="mx-auto max-w-7xl rounded-3xl border border-slate-700 bg-[#0b1120] p-6"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><p className="text-xs uppercase tracking-wider text-blue-400">Supplier 360</p><h2 className="mt-1 text-2xl font-bold">{selected.company_name}</h2><div className="mt-2 flex flex-wrap gap-2"><span className={`rounded-full border px-3 py-1 text-xs capitalize ${badge(selected.status)}`}>{selected.status}</span><span className={`rounded-full border px-3 py-1 text-xs capitalize ${badge(selected.kyc_status||"pending")}`}>KYC {selected.kyc_status||"pending"}</span><span className="rounded-full border border-slate-700 px-3 py-1 text-xs">Manager: {owner(selected.account_manager_id)}</span></div></div><button onClick={()=>setSelected(null)} className="self-start text-2xl">×</button></div>
   <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Stat label="Risk Score" value={snapshot?`${snapshot.risk_score}/100`:"—"} sub={snapshot?.risk_band}/><Stat label="Open Payables" value={snapshot?fmt(snapshot.open_payable_value,selected.currency||"AED"):"—"} sub={`${snapshot?.open_payables??0} invoices`}/><Stat label="Shipments" value={snapshot?.shipments??"—"}/><Stat label="Deals" value={snapshot?.deals??"—"}/><Stat label="Quotations" value={snapshot?.quotations??"—"}/><Stat label="Inventory Items" value={snapshot?.inventory_items??"—"}/></section>
   <div className="mt-6 grid gap-5 xl:grid-cols-[1fr_.9fr]"><section className="rounded-2xl border border-slate-800 bg-[#0d1423] p-5"><h3 className="font-semibold">Controlled Actions</h3><div className="mt-4 grid gap-2 sm:grid-cols-2">{access?.canControl&&<><button onClick={()=>setAction({kind:"kyc",value:selected.kyc_status||"pending",expiry:selected.kyc_expiry_date||"",reason:""})} className="rounded-xl border border-blue-800 px-4 py-3 text-left text-sm">KYC Review</button><button onClick={()=>setAction({kind:"status",value:selected.status,reason:""})} className="rounded-xl border border-blue-800 px-4 py-3 text-left text-sm">Change Status</button><button onClick={()=>setAction({kind:"owner",owner_id:selected.account_manager_id||"",reason:""})} className="rounded-xl border border-blue-800 px-4 py-3 text-left text-sm">Assign Manager</button></>}{access?.canControlTerms&&<button onClick={()=>setAction({kind:"terms",currency:selected.currency||"AED",terms:selected.payment_terms||"",reason:""})} className="rounded-xl border border-amber-800 px-4 py-3 text-left text-sm">Commercial Terms</button>}{access?.canRate&&<button onClick={()=>setAction({kind:"rating",rating:Number(selected.rating||0),reason:""})} className="rounded-xl border border-slate-700 px-4 py-3 text-left text-sm">Rate Supplier</button>}{access?.canDelete&&<button onClick={()=>setAction({kind:"delete",reason:""})} className="rounded-xl border border-red-900 px-4 py-3 text-left text-sm text-red-300">Delete Supplier</button>}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-slate-800 p-4 text-sm"><p className="text-xs text-slate-500">KYC Expiry</p><p className="mt-1 font-medium">{selected.kyc_expiry_date||"Not approved"}</p></div><div className="rounded-xl border border-slate-800 p-4 text-sm"><p className="text-xs text-slate-500">Rating</p><p className="mt-1 font-medium">{Number(selected.rating||0)?`${selected.rating} / 5`:"Not rated"}</p></div><div className="rounded-xl border border-slate-800 p-4 text-sm"><p className="text-xs text-slate-500">Currency</p><p className="mt-1 font-medium">{selected.currency||"AED"}</p></div><div className="rounded-xl border border-slate-800 p-4 text-sm"><p className="text-xs text-slate-500">Payment Terms</p><p className="mt-1 font-medium">{selected.payment_terms||"Not set"}</p></div></div></section>
    <section className="rounded-2xl border border-slate-800 bg-[#0d1423] p-5"><div className="flex items-center justify-between"><h3 className="font-semibold">Vendor Activity Timeline</h3><button onClick={()=>void refreshSelected()} className="text-xs text-blue-400">Refresh</button></div><div className="mt-4 max-h-[420px] space-y-3 overflow-y-auto">{events.length?events.map(e=><div key={e.id} className="rounded-xl border border-slate-800 p-3"><div className="flex justify-between gap-3"><b className="text-sm">{e.event_type.replaceAll("_"," ")}</b><span className="text-[11px] text-slate-500">{new Date(e.created_at).toLocaleString()}</span></div><p className="mt-1 text-xs text-slate-400">{e.from_value||"—"} → {e.to_value||"—"}</p>{e.reason&&<p className="mt-1 text-xs text-slate-500">{e.reason}</p>}</div>):<p className="py-10 text-center text-sm text-slate-500">No controlled events recorded yet.</p>}</div></section></div>
  </div></div>}
  {action&&selected&&<div className="fixed inset-0 z-[60] grid place-items-center bg-black/80 p-4"><div className="w-full max-w-xl rounded-3xl border border-slate-700 bg-[#0b1120] p-6"><div className="flex justify-between"><div><p className="text-xs uppercase tracking-wider text-blue-400">Controlled Vendor Action</p><h3 className="mt-1 text-xl font-bold capitalize">{action.kind.replaceAll("_"," ")}</h3></div><button onClick={()=>setAction(null)} className="text-2xl">×</button></div><div className="mt-5 space-y-3">{action.kind==="status"&&<select value={action.value} onChange={e=>setAction({...action,value:e.target.value as SupplierStatus})} className={field}>{["pending","active","inactive","blocked"].map(x=><option key={x}>{x}</option>)}</select>}{action.kind==="kyc"&&<><select value={action.value} onChange={e=>setAction({...action,value:e.target.value as KycStatus})} className={field}>{["pending","approved","expired","rejected"].map(x=><option key={x}>{x}</option>)}</select>{action.value==="approved"&&<input type="date" value={action.expiry} onChange={e=>setAction({...action,expiry:e.target.value})} className={field}/>}</>}{action.kind==="terms"&&<><select value={action.currency} onChange={e=>setAction({...action,currency:e.target.value})} className={field}>{currencies.map(x=><option key={x}>{x}</option>)}</select><input value={action.terms} onChange={e=>setAction({...action,terms:e.target.value})} placeholder="Payment terms" className={field}/></>}{action.kind==="owner"&&<select value={action.owner_id} onChange={e=>setAction({...action,owner_id:e.target.value})} className={field}><option value="">Unassigned</option>{owners.map(x=><option key={x.id} value={x.id}>{x.full_name||x.id}</option>)}</select>}{action.kind==="rating"&&<select value={action.rating} onChange={e=>setAction({...action,rating:Number(e.target.value)})} className={field}>{[0,1,2,3,4,5].map(x=><option key={x} value={x}>{x?`${x} / 5`:"Not rated"}</option>)}</select>}<textarea value={action.reason||""} onChange={e=>setAction({...action,reason:e.target.value})} placeholder={action.kind==="delete"?"Deletion reason (minimum 8 characters)":"Reason / review note"} className={`${field} min-h-24`}/></div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setAction(null)} className="rounded-xl border border-slate-700 px-5 py-2.5">Cancel</button><button disabled={busy} onClick={()=>void run()} className={`rounded-xl px-6 py-2.5 font-semibold disabled:opacity-50 ${action.kind==="delete"?"bg-red-700":"bg-blue-600"}`}>{busy?"Processing...":"Confirm & Audit"}</button></div></div></div>}
 </main>
}
