"use client";
import { useMemo, useState } from "react";
import { useCommercialStore } from "@/hooks/useCommercialStore";

export function SuppliersDirectory() {
  const { suppliers } = useCommercialStore();
  const [search,setSearch]=useState("");
  const rows=useMemo(()=>suppliers.filter((s)=>`${s.name} ${s.country} ${s.category}`.toLowerCase().includes(search.toLowerCase())),[suppliers,search]);
  return <main className="p-5 text-white md:p-8"><header className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-blue-400">Counterparty Management</p><h2 className="mt-2 text-3xl font-bold">Suppliers & Agents</h2><p className="mt-2 text-sm text-slate-400">Performance, KYC and issue control for approved counterparties.</p></div><div className="rounded-xl border border-slate-800 bg-[#0d1423] px-5 py-3 text-sm"><span className="text-slate-500">Strategic partners </span><strong>{suppliers.filter((s)=>s.strategic).length}</strong></div></header><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search supplier, country or category..." className="mt-6 w-full rounded-xl border border-slate-800 bg-[#0d1423] px-4 py-3 outline-none focus:border-blue-500"/><section className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map((s)=><article key={s.id} className="rounded-2xl border border-slate-800 bg-[#0d1423] p-5"><div className="flex items-start justify-between"><div><h3 className="text-lg font-semibold">{s.name}</h3><p className="mt-1 text-sm text-slate-500">{s.category} · {s.country}</p></div>{s.strategic&&<span className="rounded-full bg-blue-500/10 px-2 py-1 text-[10px] font-bold text-blue-300">STRATEGIC</span>}</div><div className="mt-5 grid grid-cols-3 gap-3"><div className="rounded-xl bg-slate-950/50 p-3"><p className="text-xs text-slate-500">Performance</p><p className="mt-1 font-bold text-emerald-400">{s.performance}%</p></div><div className="rounded-xl bg-slate-950/50 p-3"><p className="text-xs text-slate-500">Open Items</p><p className="mt-1 font-bold">{s.openItems}</p></div><div className="rounded-xl bg-slate-950/50 p-3"><p className="text-xs text-slate-500">KYC</p><p className="mt-1 text-xs font-bold uppercase text-amber-300">{s.kycStatus}</p></div></div><p className="mt-4 text-xs text-slate-500">Primary contact</p><p className="mt-1 text-sm text-slate-300">{s.contact}</p></article>)}</section></main>;
}
