"use client";
import { useMemo, useState } from "react";
import { useCommercialStore } from "@/hooks/useCommercialStore";
import type { CommercialTaskStatus } from "@/lib/commercial-data";

export function TasksPage() {
  const { tasks, updateTask } = useCommercialStore();
  const [filter, setFilter] = useState<"all" | CommercialTaskStatus>("all");
  const filtered = useMemo(() => filter === "all" ? tasks : tasks.filter((task) => task.status === filter), [tasks, filter]);
  return <main className="p-5 text-white md:p-8"><header><p className="text-xs font-semibold uppercase tracking-[0.24em] text-blue-400">Execution Control</p><h2 className="mt-2 text-3xl font-bold">Commercial Tasks</h2><p className="mt-2 text-sm text-slate-400">Track follow-ups, deadlines and dependencies across the commercial workflow.</p></header><div className="mt-6 flex flex-wrap gap-2">{(["all","open","in-progress","completed"] as const).map((value)=><button key={value} onClick={()=>setFilter(value)} className={`rounded-xl px-4 py-2 text-sm capitalize ${filter===value?"bg-blue-600":"border border-slate-800 bg-slate-900 text-slate-400"}`}>{value}</button>)}</div><section className="mt-5 overflow-hidden rounded-2xl border border-slate-800 bg-[#0d1423]"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-slate-800 text-xs uppercase text-slate-500"><tr><th className="px-5 py-4">Task</th><th className="px-5 py-4">Related To</th><th className="px-5 py-4">Assignee</th><th className="px-5 py-4">Due</th><th className="px-5 py-4">Priority</th><th className="px-5 py-4">Status</th></tr></thead><tbody>{filtered.map((task)=><tr key={task.id} className="border-b border-slate-800/80 last:border-0"><td className="px-5 py-4 font-semibold text-white">{task.title}</td><td className="px-5 py-4 text-blue-300">{task.relatedTo}</td><td className="px-5 py-4 text-slate-300">{task.assignee}</td><td className="px-5 py-4 text-slate-300">{task.dueDate}</td><td className="px-5 py-4 uppercase text-slate-400">{task.priority}</td><td className="px-5 py-4"><select value={task.status} onChange={(e)=>updateTask(task.id,{status:e.target.value as CommercialTaskStatus})} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 capitalize"><option value="open">Open</option><option value="in-progress">In Progress</option><option value="completed">Completed</option></select></td></tr>)}</tbody></table></div></section></main>;
}
