"use client";

import {useEffect,useMemo,useState} from "react";
import {getDocumentAccess,type DocumentAccess} from "@/lib/document-center";
import {getReadinessWorkspace,registerMissingRequirement,saveRequirementRule,setRequirementRuleActive,type DocumentReadiness,type ReadinessItem,type RequirementRule} from "@/lib/document-readiness";

const input="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20";
const btn="rounded-xl border border-slate-700 bg-slate-950/40 px-4 py-2.5 text-sm font-medium text-slate-200 transition hover:border-blue-500 hover:text-white disabled:cursor-not-allowed disabled:opacity-40";
const primary="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-blue-500 disabled:cursor-not-allowed disabled:opacity-40";
const panel="rounded-2xl border border-slate-800 bg-[#0d1423]";
const gates=["commercial","booking","dispatch","customs","delivery","finance","operational","deal_execution"];
const documentTypes=["Bill of Lading","Air Waybill","Commercial Invoice","Packing List","Certificate of Origin","Customs Declaration","Delivery Order","DG Declaration","MSDS/SDS","Insurance Certificate","Inspection Certificate","Health/Phytosanitary Certificate","Import/Export Permit","Delivery Note / POD","KYC Document","Contract / Agreement","Bank / Payment Document","Other"];
const pretty=(v:string)=>v.replaceAll("_"," ");

type Workspace={shipments:DocumentReadiness[];deals:DocumentReadiness[];rules:RequirementRule[]};
type RegisterState={readiness:DocumentReadiness;item:ReadinessItem}|null;
const blankRule:any={entity_type:"shipment",document_type:"Commercial Invoice",gate:"operational",modes:[],requires_dg:false,requires_temperature_controlled:false,is_required:true,active:true,sort_order:100,notes:""};

function statusTone(status:string){return status==="ready"?"border-emerald-800 bg-emerald-950/40 text-emerald-300":status==="not_configured"?"border-slate-700 bg-slate-900 text-slate-400":"border-red-900 bg-red-950/40 text-red-300"}
function itemTone(state:string){return state==="ready"?"text-emerald-300":state==="under_review"?"text-amber-300":state==="missing"?"text-red-300":"text-orange-300"}

export function DocumentReadinessControl(){
  const[data,setData]=useState<Workspace>({shipments:[],deals:[],rules:[]});
  const[access,setAccess]=useState<DocumentAccess|null>(null);
  const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
  const[view,setView]=useState<"readiness"|"matrix">("readiness"),[entityTab,setEntityTab]=useState<"shipment"|"deal">("shipment"),[query,setQuery]=useState("");
  const[selected,setSelected]=useState<DocumentReadiness|null>(null),[editingRule,setEditingRule]=useState<any|null>(null),[registering,setRegistering]=useState<RegisterState>(null);
  const[file,setFile]=useState<File|null>(null),[reference,setReference]=useState(""),[notes,setNotes]=useState("");

  const load=async()=>{setLoading(true);setError(null);try{const[a,w]=await Promise.all([getDocumentAccess(),getReadinessWorkspace()]);setAccess(a);setData(w);if(selected){const list=selected.entity_type==="shipment"?w.shipments:w.deals;setSelected(list.find(x=>x.entity_id===selected.entity_id)??null)}}catch(e:any){setError(e.message||"Unable to load document readiness.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);

  const entities=entityTab==="shipment"?data.shipments:data.deals;
  const filtered=useMemo(()=>entities.filter(x=>!query||x.label.toLowerCase().includes(query.toLowerCase())),[entities,query]);
  const combined=[...data.shipments,...data.deals];
  const ready=combined.filter(x=>x.gate_status==="ready").length;
  const blocked=combined.filter(x=>x.gate_status==="blocked").length;
  const notConfigured=combined.filter(x=>x.gate_status==="not_configured").length;
  const avg=combined.length?Math.round(combined.reduce((s,x)=>s+Number(x.completion_percent||0),0)/combined.length):0;

  const saveRule=async()=>{if(!editingRule)return;setSaving(true);setError(null);try{const modes=String(editingRule.modes_text??(editingRule.modes||[]).join(",")).split(",").map((x:string)=>x.trim().toLowerCase()).filter(Boolean);await saveRequirementRule({...editingRule,modes});setEditingRule(null);setMessage("Requirement matrix updated.");await load()}catch(e:any){setError(e.message||"Unable to save requirement rule.")}finally{setSaving(false)}};
  const toggleRule=async(r:RequirementRule)=>{setSaving(true);setError(null);try{await setRequirementRuleActive(r.id,!r.active);setMessage(r.active?"Requirement rule deactivated.":"Requirement rule activated.");await load()}catch(e:any){setError(e.message||"Unable to update requirement rule.")}finally{setSaving(false)}};
  const uploadMissing=async()=>{if(!registering||!file)return setError("Select the required document file.");setSaving(true);setError(null);try{await registerMissingRequirement(registering.readiness,registering.item,file,reference,notes);setRegistering(null);setFile(null);setReference("");setNotes("");setMessage("Required document registered as Draft. Submit it for approval to clear the readiness gate.");await load()}catch(e:any){setError(e.message||"Unable to register required document.")}finally{setSaving(false)}};

  return <section className="px-5 pt-5 text-white md:px-8 md:pt-8">
    <div className={`${panel} overflow-hidden`}>
      <div className="flex flex-col justify-between gap-4 border-b border-slate-800 p-5 xl:flex-row xl:items-end">
        <div><div className="text-[10px] font-semibold uppercase tracking-[.18em] text-cyan-300">Document Readiness Engine</div><h2 className="mt-2 text-2xl font-bold">Operational Document Readiness</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-400">Live readiness gates for shipments and deals. A requirement clears only when the matching controlled document is approved and valid.</p></div>
        <div className="flex flex-wrap gap-2"><button className={btn} disabled={loading||saving} onClick={()=>void load()}>Refresh Readiness</button><button className={view==="readiness"?primary:btn} onClick={()=>setView("readiness")}>Readiness</button>{access?.canApprove&&<button className={view==="matrix"?primary:btn} onClick={()=>setView("matrix")}>Requirement Matrix</button>}</div>
      </div>

      {error&&<div className="m-5 rounded-xl border border-red-900 bg-red-950/30 px-4 py-3 text-sm text-red-300">{error}</div>}
      {message&&<div className="m-5 rounded-xl border border-emerald-900 bg-emerald-950/30 px-4 py-3 text-sm text-emerald-300">{message}</div>}

      {view==="readiness"?<>
        <div className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-5">
          <Metric label="Monitored Records" value={combined.length}/><Metric label="Ready" value={ready} tone="green"/><Metric label="Blocked" value={blocked} tone={blocked?"red":"default"}/><Metric label="Not Configured" value={notConfigured}/><Metric label="Average Completion" value={`${avg}%`} tone={avg===100?"green":avg<70?"red":"default"}/>
        </div>
        <div className="border-t border-slate-800 p-5">
          <div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div className="flex gap-2"><button className={entityTab==="shipment"?primary:btn} onClick={()=>{setEntityTab("shipment");setSelected(null)}}>Shipments</button><button className={entityTab==="deal"?primary:btn} onClick={()=>{setEntityTab("deal");setSelected(null)}}>Deals</button></div><input className={`${input} md:max-w-sm`} value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${entityTab}s...`}/></div>
          {loading?<div className="py-12 text-center text-sm text-slate-500">Loading readiness engine...</div>:filtered.length===0?<div className="py-12 text-center text-sm text-slate-500">No {entityTab} records are available yet.</div>:<div className="mt-4 grid gap-4 2xl:grid-cols-[1.15fr_.85fr]">
            <div className="overflow-hidden rounded-xl border border-slate-800"><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-slate-950/50 text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3">Reference</th><th className="px-4 py-3">Completion</th><th className="px-4 py-3">Ready / Required</th><th className="px-4 py-3">Missing</th><th className="px-4 py-3">Gate</th><th className="px-4 py-3"></th></tr></thead><tbody>{filtered.map(x=><tr key={x.entity_id} className="border-t border-slate-800"><td className="px-4 py-3 font-semibold">{x.label}<div className="mt-1 text-xs font-normal text-slate-500">{x.mode||pretty(x.entity_type)}{x.is_dg?" · DG":""}{x.temperature_controlled?" · Temp Controlled":""}</div></td><td className="px-4 py-3"><div className="flex items-center gap-3"><div className="h-2 w-28 overflow-hidden rounded-full bg-slate-800"><div className="h-full bg-blue-500" style={{width:`${Math.min(100,Number(x.completion_percent||0))}%`}}/></div><span>{x.completion_percent}%</span></div></td><td className="px-4 py-3">{x.ready_count} / {x.required_count}</td><td className="px-4 py-3">{x.missing_count}</td><td className="px-4 py-3"><span className={`rounded-full border px-2.5 py-1 text-[11px] font-semibold capitalize ${statusTone(x.gate_status)}`}>{pretty(x.gate_status)}</span></td><td className="px-4 py-3 text-right"><button className={btn} onClick={()=>setSelected(x)}>Inspect</button></td></tr>)}</tbody></table></div></div>
            <div className="rounded-xl border border-slate-800 bg-slate-950/20 p-4">{selected?<ReadinessDetail value={selected} canWrite={!!access?.canWrite} onRegister={(item)=>{setRegistering({readiness:selected,item});setFile(null);setReference("");setNotes("")}}/>:<div className="flex min-h-64 items-center justify-center text-center text-sm text-slate-500">Select a record to inspect its gate-by-gate document status.</div>}</div>
          </div>}
        </div>
      </>:<Matrix rules={data.rules} saving={saving} onNew={()=>setEditingRule({...blankRule,modes_text:""})} onEdit={r=>setEditingRule({...r,modes_text:(r.modes||[]).join(", ")})} onToggle={r=>void toggleRule(r)}/>} 
    </div>

    {editingRule&&<Modal title={editingRule.id?"Edit Requirement Rule":"Add Requirement Rule"} onClose={()=>setEditingRule(null)}><div className="grid gap-3 md:grid-cols-2"><Field label="Entity Type"><select className={input} value={editingRule.entity_type} onChange={e=>setEditingRule({...editingRule,entity_type:e.target.value})}><option value="shipment">Shipment</option><option value="deal">Deal</option></select></Field><Field label="Document Type"><select className={input} value={editingRule.document_type} onChange={e=>setEditingRule({...editingRule,document_type:e.target.value})}>{documentTypes.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Readiness Gate"><select className={input} value={editingRule.gate} onChange={e=>setEditingRule({...editingRule,gate:e.target.value})}>{gates.map(x=><option key={x} value={x}>{pretty(x)}</option>)}</select></Field><Field label="Modes"><input className={input} value={editingRule.modes_text||""} onChange={e=>setEditingRule({...editingRule,modes_text:e.target.value})} placeholder="air, sea, ocean (blank = all)"/></Field><Field label="Sort Order"><input type="number" className={input} value={editingRule.sort_order} onChange={e=>setEditingRule({...editingRule,sort_order:Number(e.target.value)})}/></Field><div className="grid grid-cols-2 gap-2 pt-6"><Check label="DG only" checked={!!editingRule.requires_dg} onChange={v=>setEditingRule({...editingRule,requires_dg:v})}/><Check label="Temperature only" checked={!!editingRule.requires_temperature_controlled} onChange={v=>setEditingRule({...editingRule,requires_temperature_controlled:v})}/></div></div><Field label="Notes"><textarea className={`${input} min-h-24`} value={editingRule.notes||""} onChange={e=>setEditingRule({...editingRule,notes:e.target.value})}/></Field><div className="mt-4 flex justify-end gap-2"><button className={btn} onClick={()=>setEditingRule(null)}>Cancel</button><button className={primary} disabled={saving} onClick={()=>void saveRule()}>{saving?"Saving...":"Save Rule"}</button></div></Modal>}

    {registering&&<Modal title={`Register: ${registering.item.document_type}`} onClose={()=>setRegistering(null)}><p className="mb-4 text-sm text-slate-400">{registering.readiness.label} · {pretty(registering.item.gate)} gate</p><Field label="File"><input type="file" className={input} onChange={e=>setFile(e.target.files?.[0]||null)}/></Field><Field label="Reference No"><input className={input} value={reference} onChange={e=>setReference(e.target.value)}/></Field><Field label="Notes"><textarea className={`${input} min-h-24`} value={notes} onChange={e=>setNotes(e.target.value)}/></Field><div className="mt-4 flex justify-end gap-2"><button className={btn} onClick={()=>setRegistering(null)}>Cancel</button><button className={primary} disabled={saving||!file} onClick={()=>void uploadMissing()}>{saving?"Registering...":"Register Required Document"}</button></div></Modal>}
  </section>;
}

function ReadinessDetail({value,canWrite,onRegister}:{value:DocumentReadiness;canWrite:boolean;onRegister:(item:ReadinessItem)=>void}){return <><div className="flex items-start justify-between gap-3"><div><div className="text-lg font-semibold">{value.label}</div><div className="mt-1 text-xs text-slate-500">{value.ready_count} of {value.required_count} requirements cleared</div></div><span className={`rounded-full border px-2.5 py-1 text-[11px] font-semibold capitalize ${statusTone(value.gate_status)}`}>{pretty(value.gate_status)}</span></div><div className="mt-4 space-y-2">{value.items.length===0?<div className="rounded-lg border border-slate-800 p-4 text-sm text-slate-500">No requirement rules apply to this record.</div>:value.items.map(item=><div key={item.rule_id} className="rounded-xl border border-slate-800 p-3"><div className="flex items-start justify-between gap-3"><div><div className="font-medium">{item.document_type}</div><div className="mt-1 text-xs text-slate-500">Gate: {pretty(item.gate)}{item.version?` · Version ${item.version}`:""}{item.expiry_date?` · Expires ${item.expiry_date}`:""}</div></div><span className={`text-xs font-semibold capitalize ${itemTone(item.state)}`}>{pretty(item.state)}</span></div>{canWrite&&item.state!=="ready"&&item.state!=="under_review"&&<button className={`${btn} mt-3`} onClick={()=>onRegister(item)}>Register Document</button>}</div>)}</div></>}

function Matrix({rules,saving,onNew,onEdit,onToggle}:{rules:RequirementRule[];saving:boolean;onNew:()=>void;onEdit:(r:RequirementRule)=>void;onToggle:(r:RequirementRule)=>void}){return <div className="border-t border-slate-800 p-5"><div className="flex items-start justify-between gap-4"><div><h3 className="font-semibold">Required Document Matrix</h3><p className="mt-1 text-xs text-slate-500">Controllers define which controlled documents are required for each operational condition.</p></div><button className={primary} onClick={onNew}>+ Add Requirement</button></div><div className="mt-4 overflow-x-auto rounded-xl border border-slate-800"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-950/50 text-[10px] uppercase tracking-wider text-slate-500"><tr>{["Entity","Document","Gate","Modes","Conditions","Order","Status","Actions"].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{rules.map(r=><tr key={r.id} className="border-t border-slate-800"><td className="px-4 py-3 capitalize">{r.entity_type}</td><td className="px-4 py-3 font-medium">{r.document_type}</td><td className="px-4 py-3 capitalize">{pretty(r.gate)}</td><td className="px-4 py-3 text-slate-400">{r.modes?.length?r.modes.join(", "):"All"}</td><td className="px-4 py-3 text-slate-400">{[r.requires_dg?"DG":null,r.requires_temperature_controlled?"Temperature":null].filter(Boolean).join(" + ")||"Standard"}</td><td className="px-4 py-3">{r.sort_order}</td><td className="px-4 py-3"><span className={r.active?"text-emerald-300":"text-slate-500"}>{r.active?"Active":"Inactive"}</span></td><td className="px-4 py-3"><div className="flex gap-2"><button className={btn} disabled={saving} onClick={()=>onEdit(r)}>Edit</button><button className={btn} disabled={saving} onClick={()=>onToggle(r)}>{r.active?"Deactivate":"Activate"}</button></div></td></tr>)}</tbody></table></div></div>}
function Metric({label,value,tone="default"}:{label:string;value:string|number;tone?:string}){const c=tone==="green"?"text-emerald-300":tone==="red"?"text-red-300":"text-white";return <div className="rounded-xl border border-slate-800 bg-slate-950/30 p-4"><div className="text-[10px] uppercase tracking-wider text-slate-500">{label}</div><div className={`mt-2 text-2xl font-bold ${c}`}>{value}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mb-3 block"><span className="mb-1.5 block text-xs font-medium text-slate-400">{label}</span>{children}</label>}
function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center gap-2 rounded-xl border border-slate-800 px-3 py-2 text-sm text-slate-300"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/>{label}</label>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/70 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-slate-700 bg-[#0d1423] shadow-2xl"><div className="flex items-center justify-between border-b border-slate-800 p-5"><h3 className="text-lg font-semibold">{title}</h3><button className={btn} onClick={onClose}>Close</button></div><div className="p-5">{children}</div></div></div>}
