"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {approveFinancePayment,cancelFinanceInvoice,cancelFinancePayment,createFinanceInvoice,createFinancePayment,getFinanceLookups,getFinanceSnapshot,issueFinanceInvoice,setInvoiceCollection,setInvoiceDispute,settleFinancePayment,type FinanceSnapshot} from "@/lib/finance-control";

const field="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500 disabled:opacity-50";
const btn="rounded-xl border border-slate-700 px-3 py-2 text-xs font-semibold text-slate-200 hover:border-blue-500 hover:text-blue-300 disabled:cursor-not-allowed disabled:opacity-40";
const card="rounded-2xl border border-slate-800 bg-[#0d1423]";
const money=new Intl.NumberFormat("en-US",{maximumFractionDigits:2});
const today=()=>new Date().toISOString().slice(0,10);

export function FinanceControlCenterV2(){
 const[data,setData]=useState<FinanceSnapshot|null>(null),[lookups,setLookups]=useState<any>({customers:[],suppliers:[],deals:[],shipments:[],profiles:[]}),[busy,setBusy]=useState(""),[notice,setNotice]=useState("");
 const[showInvoice,setShowInvoice]=useState(false),[showPayment,setShowPayment]=useState(false);
 const[invoice,setInvoice]=useState<any>({invoice_type:"receivable",invoice_no:"",customer_id:"",supplier_id:"",deal_id:"",shipment_id:"",currency:"AED",amount:"",tax_amount:"0",due_date:"",payment_terms:"",vendor_reference:"",notes:""});
 const[payment,setPayment]=useState<any>({payment_type:"receipt",payment_no:"",invoice_id:"",deal_id:"",customer_id:"",supplier_id:"",currency:"AED",amount:"",payment_date:today(),method:"bank_transfer",purpose:"",priority:"normal",notes:""});
 const load=async()=>{setBusy("load");setNotice("");try{const[d,l]=await Promise.all([getFinanceSnapshot(),getFinanceLookups()]);setData(d);setLookups(l)}catch(e:any){setNotice(e?.message||"Unable to load Finance Control Center.")}finally{setBusy("")}};
 useEffect(()=>{void load()},[]);
 async function run(key:string,fn:()=>Promise<any>,ok:string){setBusy(key);setNotice("");try{await fn();setNotice(ok);await load()}catch(e:any){setNotice(e?.message||"Action failed.")}finally{setBusy("")}}
 const model=useMemo(()=>{if(!data)return{ar:0,ap:0,overdue:0,pending:0,approved:0,failed:0};const paid=new Map<string,number>();for(const p of data.payments){if(p.status==="completed"&&p.invoice_id)paid.set(p.invoice_id,(paid.get(p.invoice_id)||0)+Number(p.amount||0))}const out=(i:any)=>Math.max(0,Number(i.total_amount||0)-(paid.get(i.id)||0));const now=new Date(`${today()}T23:59:59`).getTime();return{ar:data.receivables.filter(i=>i.status!=="cancelled").reduce((n,i)=>n+out(i),0),ap:data.payables.filter(i=>i.status!=="cancelled").reduce((n,i)=>n+out(i),0),overdue:data.receivables.filter(i=>i.status!=="cancelled"&&i.due_date&&new Date(`${i.due_date}T23:59:59`).getTime()<now&&out(i)>0).reduce((n,i)=>n+out(i),0),pending:data.payments.filter(p=>p.status==="pending").length,approved:data.payments.filter(p=>p.status==="approved").length,failed:data.payments.filter(p=>p.status==="failed").length}},[data]);
 if(!data)return <main className="min-h-screen bg-[#070b14] p-6 text-white"><div className={`${card} p-8`}>{notice||"Loading Finance Control Center..."}</div></main>;
 const invoices=[...data.receivables,...data.payables];
 async function createInvoice(){if(Number(invoice.amount||0)<=0){setNotice("Invoice amount must be greater than zero.");return}if(invoice.invoice_type==="receivable"&&!invoice.customer_id){setNotice("Customer is required for a receivable invoice.");return}if(invoice.invoice_type==="payable"&&!invoice.supplier_id){setNotice("Supplier is required for a payable invoice.");return}await run("create-invoice",()=>createFinanceInvoice(invoice),"Draft invoice created.");setShowInvoice(false)}
 async function createPayment(){if(Number(payment.amount||0)<=0){setNotice("Payment amount must be greater than zero.");return}await run("create-payment",()=>createFinancePayment(payment),"Payment instruction created and sent to approval workflow.");setShowPayment(false)}
 return <main className="min-h-screen bg-[#070b14] p-5 text-white md:p-8"><header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-blue-400">VTC ONE · Financial Execution</p><h1 className="mt-2 text-3xl font-bold">Finance Control Center V2</h1><p className="mt-2 max-w-4xl text-sm text-slate-400">Controlled invoicing, collections, payment instructions, maker-checker approval and settlement. Status changes are backend-enforced and audited.</p></div><div className="flex flex-wrap gap-2"><span className="rounded-xl border border-slate-800 bg-slate-950 px-3 py-2 text-xs text-slate-400">Role: {data.role}</span><button onClick={()=>void load()} className={btn}>{busy==="load"?"Refreshing...":"Refresh"}</button><Link href="/commercial" className={btn}>Commercial Flow</Link><Link href="/treasury" className={btn}>Treasury</Link></div></header>
 {notice&&<div className="mt-5 rounded-xl border border-blue-500/30 bg-blue-500/10 p-3 text-sm text-blue-100">{notice}</div>}
 <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><K l="Open Receivables" v={`AED ${money.format(model.ar)}`}/><K l="Open Payables" v={`AED ${money.format(model.ap)}`}/><K l="Overdue A/R" v={`AED ${money.format(model.overdue)}`} warn={model.overdue>0}/><K l="Pending Approval" v={String(model.pending)} warn={model.pending>0}/><K l="Approved to Settle" v={String(model.approved)}/><K l="Failed Payments" v={String(model.failed)} warn={model.failed>0}/></section>
 <section className="mt-6 grid gap-5 2xl:grid-cols-[1.1fr_.9fr]"><div className={`${card} p-5`}><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">Invoice Origination</h2><p className="mt-1 text-xs text-slate-500">Create controlled receivable or payable drafts. Issuing is a separate workflow action.</p></div>{data.can_write&&<button onClick={()=>setShowInvoice(v=>!v)} className={btn}>{showInvoice?"Close":"+ New Invoice"}</button>}</div>{showInvoice&&<div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><select value={invoice.invoice_type} onChange={e=>setInvoice({...invoice,invoice_type:e.target.value,customer_id:"",supplier_id:""})} className={field}><option value="receivable">Receivable</option><option value="payable">Payable</option></select><input value={invoice.invoice_no} onChange={e=>setInvoice({...invoice,invoice_no:e.target.value})} placeholder="Invoice No. (auto if blank)" className={field}/>{invoice.invoice_type==="receivable"?<select value={invoice.customer_id} onChange={e=>setInvoice({...invoice,customer_id:e.target.value})} className={field}><option value="">Customer *</option>{lookups.customers.map((x:any)=><option key={x.id} value={x.id}>{x.company_name}</option>)}</select>:<select value={invoice.supplier_id} onChange={e=>setInvoice({...invoice,supplier_id:e.target.value})} className={field}><option value="">Supplier *</option>{lookups.suppliers.map((x:any)=><option key={x.id} value={x.id}>{x.company_name}</option>)}</select>}<input type="number" min="0" step="any" value={invoice.amount} onChange={e=>setInvoice({...invoice,amount:e.target.value})} placeholder="Net amount *" className={field}/><input type="number" min="0" step="any" value={invoice.tax_amount} onChange={e=>setInvoice({...invoice,tax_amount:e.target.value})} placeholder="Tax amount" className={field}/><select value={invoice.currency} onChange={e=>setInvoice({...invoice,currency:e.target.value})} className={field}>{["AED","USD","EUR","GBP","CNY","INR"].map(x=><option key={x}>{x}</option>)}</select><input type="date" value={invoice.due_date} onChange={e=>setInvoice({...invoice,due_date:e.target.value})} className={field}/><input value={invoice.payment_terms} onChange={e=>setInvoice({...invoice,payment_terms:e.target.value})} placeholder="Payment terms" className={field}/><input value={invoice.vendor_reference} onChange={e=>setInvoice({...invoice,vendor_reference:e.target.value})} placeholder="External reference" className={field}/><textarea value={invoice.notes} onChange={e=>setInvoice({...invoice,notes:e.target.value})} placeholder="Invoice notes" className={`${field} min-h-24 md:col-span-2`}/><div className="flex items-end"><button disabled={busy==="create-invoice"} onClick={()=>void createInvoice()} className="w-full rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold disabled:opacity-40">{busy==="create-invoice"?"Creating...":"Create Draft Invoice"}</button></div></div>}</div>
 <div className={`${card} p-5`}><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">Payment Instruction</h2><p className="mt-1 text-xs text-slate-500">Finance creates; Manager/Admin/CEO approves; Finance settles after approval.</p></div>{data.can_write&&<button onClick={()=>setShowPayment(v=>!v)} className={btn}>{showPayment?"Close":"+ New Payment"}</button>}</div>{showPayment&&<div className="mt-4 grid gap-3 md:grid-cols-2"><select value={payment.payment_type} onChange={e=>setPayment({...payment,payment_type:e.target.value})} className={field}><option value="receipt">Customer Receipt</option><option value="payment">Supplier Payment</option></select><select value={payment.invoice_id} onChange={e=>{const id=e.target.value;const inv=invoices.find((x:any)=>x.id===id);setPayment({...payment,invoice_id:id,deal_id:inv?.deal_id||"",customer_id:inv?.customer_id||"",supplier_id:inv?.supplier_id||"",currency:inv?.currency||payment.currency})}} className={field}><option value="">Invoice optional</option>{invoices.filter((x:any)=>x.status!=="cancelled").map((x:any)=><option key={x.id} value={x.id}>{x.invoice_no} · {x.currency} {money.format(Number(x.total_amount||0))}</option>)}</select><input type="number" min="0" step="any" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})} placeholder="Amount *" className={field}/><select value={payment.currency} onChange={e=>setPayment({...payment,currency:e.target.value})} className={field}>{["AED","USD","EUR","GBP","CNY","INR"].map(x=><option key={x}>{x}</option>)}</select><input type="date" value={payment.payment_date} onChange={e=>setPayment({...payment,payment_date:e.target.value})} className={field}/><select value={payment.priority} onChange={e=>setPayment({...payment,priority:e.target.value})} className={field}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select><input value={payment.purpose} onChange={e=>setPayment({...payment,purpose:e.target.value})} placeholder="Purpose" className={field}/><input value={payment.notes} onChange={e=>setPayment({...payment,notes:e.target.value})} placeholder="Internal notes" className={field}/><button disabled={busy==="create-payment"} onClick={()=>void createPayment()} className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold disabled:opacity-40 md:col-span-2">{busy==="create-payment"?"Creating...":"Create Payment Instruction"}</button></div>}</div></section>
 <section className={`${card} mt-6 overflow-hidden`}><Head t="Invoice Control" s="Issue, collections, disputes and cancellation from one operational register"/><div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-sm"><thead className="bg-slate-950/50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Invoice</th><th>Counterparty</th><th>Type</th><th>Status</th><th>Total</th><th>Due</th><th>Collection</th><th>Dispute</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{invoices.map((i:any)=><tr key={i.id} className="border-t border-slate-800"><td className="p-4"><b>{i.invoice_no}</b><div className="text-xs text-slate-500">{i.deal_no||"No deal"}</div></td><td>{i.customer_name||i.supplier_name||"—"}</td><td className="capitalize">{i.invoice_type}</td><td><Badge v={i.status}/></td><td>{i.currency} {money.format(Number(i.total_amount||0))}</td><td>{i.due_date||"—"}</td><td><Badge v={i.collection_status||"open"}/></td><td><Badge v={i.dispute_status||"clear"}/></td><td className="p-4"><div className="flex justify-end gap-2">{i.status==="draft"&&data.can_write&&<button disabled={!!busy} onClick={()=>void run(`issue-${i.id}`,()=>issueFinanceInvoice(i.id,i.due_date),"Invoice issued.")} className={btn}>Issue</button>}{i.invoice_type==="receivable"&&!["paid","cancelled"].includes(i.status)&&data.can_write&&<button disabled={!!busy} onClick={()=>{const st=(window.prompt("Collection status: open / contacted / promised / escalated / closed",i.collection_status||"contacted")||"") as any;if(st)void run(`collection-${i.id}`,()=>setInvoiceCollection(i.id,st,null,null,null,"Updated from Finance Control Center"),"Collection status updated.")}} className={btn}>Collection</button>}{!["paid","cancelled"].includes(i.status)&&data.can_write&&<button disabled={!!busy} onClick={()=>{const reason=window.prompt("Dispute reason");if(reason)void run(`dispute-${i.id}`,()=>setInvoiceDispute(i.id,"disputed",reason),"Invoice marked disputed and credit hold enabled.")}} className={btn}>Dispute</button>}{data.can_approve&&!["paid","cancelled"].includes(i.status)&&<button disabled={!!busy} onClick={()=>{const reason=window.prompt("Cancellation reason");if(reason)void run(`cancel-inv-${i.id}`,()=>cancelFinanceInvoice(i.id,reason),"Invoice cancelled.")}} className={btn}>Cancel</button>}</div></td></tr>)}{!invoices.length&&<tr><td colSpan={9} className="p-10 text-center text-slate-500">No invoices found.</td></tr>}</tbody></table></div></section>
 <section className={`${card} mt-6 overflow-hidden`}><Head t="Payment Workflow" s="Maker-checker approval and settlement queue"/><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-slate-950/50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Payment</th><th>Type</th><th>Status</th><th>Amount</th><th>Date</th><th>Approval</th><th>Settlement</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{data.payments.map((p:any)=><tr key={p.id} className="border-t border-slate-800"><td className="p-4"><b>{p.payment_no}</b><div className="text-xs text-slate-500">{p.purpose||p.invoice_id||"Unallocated"}</div></td><td className="capitalize">{p.payment_type}</td><td><Badge v={p.status}/></td><td>{p.currency} {money.format(Number(p.amount||0))}</td><td>{p.payment_date||"—"}</td><td><Badge v={p.approval_status||"pending"}/></td><td><Badge v={p.settlement_status||"unsettled"}/></td><td className="p-4"><div className="flex justify-end gap-2">{p.status==="pending"&&data.can_approve&&<button disabled={!!busy} onClick={()=>void run(`approve-pay-${p.id}`,()=>approveFinancePayment(p.id,"Approved from Finance Control Center"),"Payment approved.")} className={btn}>Approve</button>}{p.status==="approved"&&data.can_write&&<><button disabled={!!busy} onClick={()=>void run(`complete-${p.id}`,()=>settleFinancePayment(p.id,"completed",null,null),"Payment settled and invoice balance updated.")} className={btn}>Complete</button><button disabled={!!busy} onClick={()=>{const reason=window.prompt("Failure reason");if(reason)void run(`fail-${p.id}`,()=>settleFinancePayment(p.id,"failed",null,reason),"Payment marked failed.")}} className={btn}>Fail</button></>}{["pending","approved"].includes(p.status)&&data.can_write&&<button disabled={!!busy} onClick={()=>{const reason=window.prompt("Cancellation reason");if(reason)void run(`cancel-pay-${p.id}`,()=>cancelFinancePayment(p.id,reason),"Payment cancelled.")}} className={btn}>Cancel</button>}</div></td></tr>)}{!data.payments.length&&<tr><td colSpan={8} className="p-10 text-center text-slate-500">No payment instructions found.</td></tr>}</tbody></table></div></section>
 <section className={`${card} mt-6 p-5`}><div className="flex items-center justify-between"><div><h2 className="font-semibold">Finance Audit Stream</h2><p className="mt-1 text-xs text-slate-500">Latest controlled invoice and payment actions</p></div><span className="text-xs text-slate-500">{data.events.length} events</span></div><div className="mt-4 grid gap-2 lg:grid-cols-2">{data.events.slice(0,12).map((e:any)=><div key={e.id} className="rounded-xl border border-slate-800 bg-slate-950/40 p-3"><div className="flex justify-between gap-3"><b className="text-sm">{String(e.event_type).replaceAll("_"," ")}</b><span className="text-[11px] text-slate-500">{new Date(e.created_at).toLocaleString()}</span></div><p className="mt-1 text-xs text-slate-400">{e.entity_type} · {e.from_status||"—"} → {e.to_status||"—"}</p></div>)}</div></section>
 </main>
}
function Head({t,s}:{t:string;s:string}){return <div className="border-b border-slate-800 p-5"><h2 className="font-semibold">{t}</h2><p className="mt-1 text-xs text-slate-500">{s}</p></div>}
function K({l,v,warn=false}:{l:string;v:string;warn?:boolean}){return <div className={`${card} p-4`}><p className="text-[11px] uppercase tracking-wider text-slate-500">{l}</p><p className={`mt-2 text-xl font-bold ${warn?"text-amber-300":"text-white"}`}>{v}</p></div>}
function Badge({v}:{v:string}){const good=["paid","completed","approved","clear","closed","settled"].includes(v);const bad=["failed","cancelled","overdue","disputed","escalated"].includes(v);return <span className={`rounded-full border px-2 py-1 text-[10px] font-bold uppercase ${good?"border-emerald-500/30 bg-emerald-500/10 text-emerald-300":bad?"border-red-500/30 bg-red-500/10 text-red-300":"border-slate-700 bg-slate-900 text-slate-300"}`}>{String(v).replaceAll("_"," ")}</span>}
