"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {addCollectionActivityV2,allocateReceiptV2,cancelReceivableV2,createReceivableV2,getReceivablesControlData,issueReceivableV2,setReceivableDisputeV2,updateCollectionV2} from "@/lib/receivables-control";

const field="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500 disabled:opacity-50";
const btn="rounded-xl border border-slate-700 px-3 py-2 text-xs font-semibold text-slate-200 hover:border-blue-500 hover:text-blue-300 disabled:cursor-not-allowed disabled:opacity-40";
const card="rounded-2xl border border-slate-800 bg-[#0d1423]";
const money=new Intl.NumberFormat("en-US",{maximumFractionDigits:2});
const today=()=>new Date().toISOString().slice(0,10);
const date=(v?:string|null)=>v?new Date(v).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"}):"—";

export function ReceivablesControlCenterV2(){
 const[data,setData]=useState<any>(null),[busy,setBusy]=useState(""),[notice,setNotice]=useState(""),[search,setSearch]=useState(""),[currency,setCurrency]=useState("all"),[filter,setFilter]=useState("open"),[selected,setSelected]=useState<any>(null),[panel,setPanel]=useState<"new"|"follow"|"allocate"|null>(null);
 const[newInv,setNewInv]=useState<any>({invoice_no:"",customer_id:"",currency:"AED",amount:"",tax_amount:"0",due_date:"",payment_terms:"",notes:""});
 const[follow,setFollow]=useState<any>({activity_type:"follow_up",channel:"email",contact_person:"",notes:"",outcome:"",collection_status:"contacted",promised_payment_date:"",next_follow_up_at:""});
 const[alloc,setAlloc]=useState<any>({payment_id:"",amount:"",notes:""});
 const load=async()=>{setBusy("load");setNotice("");try{const d=await getReceivablesControlData();setData(d);if(selected){const fresh=d.invoices.find((x:any)=>x.id===selected.id);setSelected(fresh||null)}}catch(e:any){setNotice(e?.message||"Unable to load receivables.")}finally{setBusy("")}};
 useEffect(()=>{void load()},[]);
 async function run(key:string,fn:()=>Promise<any>,ok:string){setBusy(key);setNotice("");try{await fn();setNotice(ok);await load()}catch(e:any){setNotice(e?.message||"Action failed.")}finally{setBusy("")}}
 const model=useMemo(()=>{if(!data)return null;const direct=new Map<string,number>(),allocated=new Map<string,number>(),receiptUsed=new Map<string,number>();for(const p of data.receipts){if(p.status==="completed"&&p.invoice_id)direct.set(p.invoice_id,(direct.get(p.invoice_id)||0)+Number(p.amount||0))}for(const a of data.allocations){allocated.set(a.invoice_id,(allocated.get(a.invoice_id)||0)+Number(a.amount||0));receiptUsed.set(a.payment_id,(receiptUsed.get(a.payment_id)||0)+Number(a.amount||0))}const now=new Date(`${today()}T23:59:59`).getTime();const rows=data.invoices.map((i:any)=>{const paid=(direct.get(i.id)||0)+(allocated.get(i.id)||0),outstanding=Math.max(0,Number(i.total_amount||0)-paid),due=i.due_date?new Date(`${i.due_date}T23:59:59`).getTime():null,days=due&&due<now?Math.floor((now-due)/86400000):0,promiseBreach=!!i.promised_payment_date&&new Date(`${i.promised_payment_date}T23:59:59`).getTime()<now&&outstanding>0;return{...i,paid,outstanding,days_overdue:days,promise_breach:promiseBreach}});const currencies=[...new Set(rows.map((x:any)=>x.currency).filter(Boolean))].sort();const visible=rows.filter((r:any)=>{const text=`${r.invoice_no} ${r.customer?.company_name||""} ${r.notes||""}`.toLowerCase();const f=filter==="all"||filter==="open"&&r.outstanding>0&&r.status!=="cancelled"||filter==="overdue"&&r.days_overdue>0&&r.outstanding>0||filter==="disputed"&&r.dispute_status==="disputed"||filter==="promise"&&r.collection_status==="promised"||filter==="paid"&&r.status==="paid";return text.includes(search.toLowerCase())&&(currency==="all"||r.currency===currency)&&f});const scoped=rows.filter((r:any)=>currency==="all"||r.currency===currency);const open=scoped.filter((r:any)=>r.outstanding>0&&r.status!=="cancelled");const sum=(a:any[])=>a.reduce((n,x)=>n+Number(x.outstanding||0),0);return{rows,visible,currencies,outstanding:sum(open),overdue:sum(open.filter((x:any)=>x.days_overdue>0)),disputed:sum(open.filter((x:any)=>x.dispute_status==="disputed")),promiseBreach:sum(open.filter((x:any)=>x.promise_breach)),bucket30:sum(open.filter((x:any)=>x.days_overdue>0&&x.days_overdue<=30)),bucket60:sum(open.filter((x:any)=>x.days_overdue>30&&x.days_overdue<=60)),bucket90:sum(open.filter((x:any)=>x.days_overdue>60&&x.days_overdue<=90)),bucket90p:sum(open.filter((x:any)=>x.days_overdue>90)),receiptUsed}},[data,search,currency,filter]);
 if(!data||!model)return <main className="min-h-screen bg-[#070b14] p-6 text-white"><div className={`${card} p-8`}>{notice||"Loading Receivables Control Center..."}</div></main>;
 const selectedRow=selected?model.rows.find((x:any)=>x.id===selected.id):null;
 const receipts=data.receipts.map((p:any)=>({...p,available:Math.max(0,Number(p.amount||0)-Number(model.receiptUsed.get(p.id)||0))})).filter((p:any)=>p.status==="completed"&&!p.invoice_id&&p.available>0&&(!selectedRow||p.currency===selectedRow.currency));
 const displayCurrency=currency==="all"?"Mixed":currency;
 async function create(issue:boolean){if(!newInv.customer_id||Number(newInv.amount||0)<=0){setNotice("Customer and a positive invoice amount are required.");return}await run("create",()=>createReceivableV2(newInv,issue),issue?"Receivable created and issued.":"Receivable draft created.");setPanel(null);setNewInv({invoice_no:"",customer_id:"",currency:"AED",amount:"",tax_amount:"0",due_date:"",payment_terms:"",notes:""})}
 async function saveFollow(){if(!selectedRow)return;if(!follow.notes.trim()){setNotice("Collection note is required.");return}await run("follow",()=>addCollectionActivityV2({...follow,invoice_id:selectedRow.id,owner_id:selectedRow.collection_owner_id||null,next_follow_up_at:follow.next_follow_up_at?new Date(follow.next_follow_up_at).toISOString():null}),"Collection activity recorded.");setPanel(null);setFollow({activity_type:"follow_up",channel:"email",contact_person:"",notes:"",outcome:"",collection_status:"contacted",promised_payment_date:"",next_follow_up_at:""})}
 async function saveAllocation(){if(!selectedRow||!alloc.payment_id||Number(alloc.amount||0)<=0){setNotice("Completed receipt and allocation amount are required.");return}await run("allocate",()=>allocateReceiptV2(selectedRow.id,alloc.payment_id,Number(alloc.amount),alloc.notes),"Receipt allocated and invoice balance recalculated.");setPanel(null);setAlloc({payment_id:"",amount:"",notes:""})}
 return <main className="min-h-screen bg-[#070b14] p-5 text-white md:p-8"><header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-blue-400">VTC ONE · Finance Collections</p><h1 className="mt-2 text-3xl font-bold">Receivables Control Center V2</h1><p className="mt-2 max-w-4xl text-sm text-slate-400">Controlled customer invoicing, aging, collection commitments, disputes, credit hold and allocation of completed receipts. Operational writes are RPC-enforced and audited.</p></div><div className="flex flex-wrap gap-2"><span className="rounded-xl border border-slate-800 bg-slate-950 px-3 py-2 text-xs text-slate-400">Role: {data.role}</span><button onClick={()=>void load()} className={btn}>{busy==="load"?"Refreshing...":"Refresh"}</button><Link href="/finance" className={btn}>Finance</Link>{data.can_write&&<button onClick={()=>setPanel("new")} className="rounded-xl bg-blue-600 px-4 py-2 text-xs font-semibold">+ New Receivable</button>}</div></header>
 {notice&&<div className="mt-5 rounded-xl border border-blue-500/30 bg-blue-500/10 p-3 text-sm text-blue-100">{notice}</div>}
 <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><K l="Outstanding" v={`${displayCurrency} ${money.format(model.outstanding)}`}/><K l="Overdue" v={`${displayCurrency} ${money.format(model.overdue)}`} warn={model.overdue>0}/><K l="Disputed" v={`${displayCurrency} ${money.format(model.disputed)}`} warn={model.disputed>0}/><K l="Broken Promises" v={`${displayCurrency} ${money.format(model.promiseBreach)}`} warn={model.promiseBreach>0}/></section>
 <section className={`${card} mt-5 p-5`}><div className="flex items-center justify-between gap-4"><div><h2 className="font-semibold">Aging Exposure</h2><p className="mt-1 text-xs text-slate-500">Outstanding overdue balance by aging bucket.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-4"><K l="1–30 Days" v={`${displayCurrency} ${money.format(model.bucket30)}`}/><K l="31–60 Days" v={`${displayCurrency} ${money.format(model.bucket60)}`}/><K l="61–90 Days" v={`${displayCurrency} ${money.format(model.bucket90)}`}/><K l="90+ Days" v={`${displayCurrency} ${money.format(model.bucket90p)}`} warn={model.bucket90p>0}/></div></section>
 <section className={`${card} mt-5 grid gap-3 p-4 lg:grid-cols-[1fr_180px_180px]`}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search invoice, customer or notes" className={field}/><select value={filter} onChange={e=>setFilter(e.target.value)} className={field}><option value="open">Open</option><option value="overdue">Overdue</option><option value="disputed">Disputed</option><option value="promise">Promise to Pay</option><option value="paid">Paid</option><option value="all">All</option></select><select value={currency} onChange={e=>setCurrency(e.target.value)} className={field}><option value="all">All currencies</option>{model.currencies.map((c:string)=><option key={c}>{c}</option>)}</select></section>
 <section className={`${card} mt-5 overflow-hidden`}><div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-sm"><thead className="bg-slate-950/50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Invoice</th><th>Customer</th><th>Total</th><th>Paid</th><th>Outstanding</th><th>Due</th><th>Aging</th><th>Collection</th><th>Dispute</th><th className="p-4 text-right">Action</th></tr></thead><tbody>{model.visible.map((r:any)=><tr key={r.id} className="border-t border-slate-800"><td className="p-4"><b>{r.invoice_no}</b><div className="text-xs text-slate-500">{r.status}</div></td><td>{r.customer?.company_name||"—"}</td><td>{r.currency} {money.format(Number(r.total_amount||0))}</td><td className="text-emerald-300">{r.currency} {money.format(r.paid)}</td><td className="font-semibold">{r.currency} {money.format(r.outstanding)}</td><td>{date(r.due_date)}</td><td className={r.days_overdue>0?"text-red-300":"text-slate-400"}>{r.days_overdue>0?`${r.days_overdue} days`:"Current"}</td><td><Badge v={r.collection_status||"open"}/>{r.promise_breach&&<div className="mt-1 text-[10px] font-bold uppercase text-red-300">Promise breached</div>}</td><td><Badge v={r.dispute_status||"clear"}/></td><td className="p-4 text-right"><button onClick={()=>{setSelected(r);setPanel(null)}} className={btn}>Open File</button></td></tr>)}{!model.visible.length&&<tr><td colSpan={10} className="p-10 text-center text-slate-500">No receivables match this view.</td></tr>}</tbody></table></div></section>
 {selectedRow&&<section className={`${card} mt-5 p-5`}><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-400">Receivable File</p><h2 className="mt-1 text-xl font-semibold">{selectedRow.invoice_no} · {selectedRow.customer?.company_name||"Customer"}</h2><p className="mt-2 text-sm text-slate-400">Outstanding {selectedRow.currency} {money.format(selectedRow.outstanding)} · Due {date(selectedRow.due_date)}</p></div><div className="flex flex-wrap gap-2">{selectedRow.status==="draft"&&data.can_write&&<button disabled={!!busy} onClick={()=>void run("issue",()=>issueReceivableV2(selectedRow.id,selectedRow.due_date),"Receivable issued.")} className={btn}>Issue</button>}{data.can_write&&!["paid","cancelled"].includes(selectedRow.status)&&<button onClick={()=>setPanel("follow")} className={btn}>Log Follow-up</button>}{data.can_write&&selectedRow.outstanding>0&&<button onClick={()=>setPanel("allocate")} className={btn}>Allocate Receipt</button>}{data.can_write&&selectedRow.dispute_status!=="disputed"&&!["paid","cancelled"].includes(selectedRow.status)&&<button onClick={()=>{const reason=window.prompt("Dispute reason");if(reason)void run("dispute",()=>setReceivableDisputeV2(selectedRow.id,"disputed",reason),"Invoice disputed and credit hold enabled.")}} className={btn}>Dispute</button>}{data.can_write&&selectedRow.dispute_status==="disputed"&&<button onClick={()=>{const reason=window.prompt("Resolution note");if(reason)void run("resolve",()=>setReceivableDisputeV2(selectedRow.id,"resolved",reason),"Dispute resolved and credit hold released.")}} className={btn}>Resolve</button>}{data.can_approve&&!["paid","cancelled"].includes(selectedRow.status)&&<button onClick={()=>{const reason=window.prompt("Cancellation reason");if(reason)void run("cancel",()=>cancelReceivableV2(selectedRow.id,reason),"Receivable cancelled.")}} className={btn}>Cancel</button>}<button onClick={()=>{setSelected(null);setPanel(null)}} className={btn}>Close</button></div></div>
 <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><K l="Status" v={selectedRow.status}/><K l="Collection" v={selectedRow.collection_status||"open"}/><K l="Dispute" v={selectedRow.dispute_status||"clear"} warn={selectedRow.dispute_status==="disputed"}/><K l="Credit Hold" v={selectedRow.credit_hold?"YES":"NO"} warn={selectedRow.credit_hold}/><K l="Promise Date" v={date(selectedRow.promised_payment_date)} warn={selectedRow.promise_breach}/></div>
 {data.can_write&&!["paid","cancelled"].includes(selectedRow.status)&&<div className="mt-5 grid gap-3 md:grid-cols-[180px_1fr_auto]"><select value={selectedRow.collection_status||"open"} onChange={e=>void run("collection",()=>updateCollectionV2(selectedRow.id,e.target.value as any,selectedRow.collection_owner_id,selectedRow.promised_payment_date,selectedRow.next_follow_up_at,"Collection stage updated"),"Collection stage updated.")} className={field}>{["open","contacted","promised","escalated","closed"].map(x=><option key={x}>{x}</option>)}</select><select value={selectedRow.collection_owner_id||""} onChange={e=>void run("owner",()=>updateCollectionV2(selectedRow.id,selectedRow.collection_status||"open",e.target.value||null,selectedRow.promised_payment_date,selectedRow.next_follow_up_at,"Collection owner updated"),"Collection owner updated.")} className={field}><option value="">Auto assign current user</option>{data.profiles.map((p:any)=><option key={p.id} value={p.id}>{p.full_name} · {p.role}</option>)}</select><span className="rounded-xl border border-slate-800 px-3 py-2 text-xs text-slate-500">Next: {selectedRow.next_follow_up_at?new Date(selectedRow.next_follow_up_at).toLocaleString():"Not scheduled"}</span></div>}
 <div className="mt-5"><h3 className="font-semibold">Collection History</h3><div className="mt-3 space-y-2">{data.activities.filter((a:any)=>a.invoice_id===selectedRow.id).slice(0,12).map((a:any)=><div key={a.id} className="rounded-xl border border-slate-800 bg-slate-950/30 p-3"><div className="flex justify-between gap-3 text-sm"><span className="font-medium">{a.activity_type} · {a.channel||"—"}</span><span className="text-xs text-slate-500">{new Date(a.activity_at).toLocaleString()}</span></div><p className="mt-1 text-sm text-slate-400">{a.notes||a.outcome||"No note"}</p><p className="mt-1 text-xs text-slate-600">{a.creator?.full_name||"Finance"}</p></div>)}{!data.activities.some((a:any)=>a.invoice_id===selectedRow.id)&&<p className="text-sm text-slate-500">No collection activity recorded.</p>}</div></div>
 </section>}
 {panel&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className={`${card} max-h-[90vh] w-full max-w-2xl overflow-auto p-6`}><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{panel==="new"?"New Receivable":panel==="follow"?"Collection Follow-up":"Allocate Completed Receipt"}</h2><button onClick={()=>setPanel(null)} className={btn}>Close</button></div>
 {panel==="new"&&<div className="mt-5 grid gap-3 md:grid-cols-2"><select value={newInv.customer_id} onChange={e=>setNewInv({...newInv,customer_id:e.target.value})} className={field}><option value="">Customer *</option>{data.customers.map((c:any)=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select><input value={newInv.invoice_no} onChange={e=>setNewInv({...newInv,invoice_no:e.target.value})} placeholder="Invoice No. (auto if blank)" className={field}/><input type="number" min="0" step="any" value={newInv.amount} onChange={e=>setNewInv({...newInv,amount:e.target.value})} placeholder="Net amount *" className={field}/><input type="number" min="0" step="any" value={newInv.tax_amount} onChange={e=>setNewInv({...newInv,tax_amount:e.target.value})} placeholder="Tax amount" className={field}/><select value={newInv.currency} onChange={e=>setNewInv({...newInv,currency:e.target.value})} className={field}>{["AED","USD","EUR","GBP","CNY","INR"].map(x=><option key={x}>{x}</option>)}</select><input type="date" value={newInv.due_date} onChange={e=>setNewInv({...newInv,due_date:e.target.value})} className={field}/><input value={newInv.payment_terms} onChange={e=>setNewInv({...newInv,payment_terms:e.target.value})} placeholder="Payment terms" className={field}/><textarea value={newInv.notes} onChange={e=>setNewInv({...newInv,notes:e.target.value})} placeholder="Notes" className={`${field} min-h-24`}/><button disabled={!!busy} onClick={()=>void create(false)} className={btn}>Create Draft</button><button disabled={!!busy} onClick={()=>void create(true)} className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold disabled:opacity-40">Create & Issue</button></div>}
 {panel==="follow"&&selectedRow&&<div className="mt-5 grid gap-3 md:grid-cols-2"><select value={follow.collection_status} onChange={e=>setFollow({...follow,collection_status:e.target.value})} className={field}>{["contacted","promised","escalated","open"].map(x=><option key={x}>{x}</option>)}</select><select value={follow.channel} onChange={e=>setFollow({...follow,channel:e.target.value})} className={field}>{["email","phone","whatsapp","meeting","letter"].map(x=><option key={x}>{x}</option>)}</select><input value={follow.contact_person} onChange={e=>setFollow({...follow,contact_person:e.target.value})} placeholder="Contact person" className={field}/><input value={follow.outcome} onChange={e=>setFollow({...follow,outcome:e.target.value})} placeholder="Outcome" className={field}/><input type="date" value={follow.promised_payment_date} onChange={e=>setFollow({...follow,promised_payment_date:e.target.value,collection_status:e.target.value?"promised":follow.collection_status})} className={field}/><input type="datetime-local" value={follow.next_follow_up_at} onChange={e=>setFollow({...follow,next_follow_up_at:e.target.value})} className={field}/><textarea value={follow.notes} onChange={e=>setFollow({...follow,notes:e.target.value})} placeholder="Collection note *" className={`${field} min-h-28 md:col-span-2`}/><button disabled={!!busy} onClick={()=>void saveFollow()} className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold disabled:opacity-40 md:col-span-2">Record Follow-up</button></div>}
 {panel==="allocate"&&selectedRow&&<div className="mt-5 space-y-3"><select value={alloc.payment_id} onChange={e=>{const p=receipts.find((x:any)=>x.id===e.target.value);setAlloc({...alloc,payment_id:e.target.value,amount:p?Math.min(p.available,selectedRow.outstanding):""})}} className={field}><option value="">Completed unapplied receipt *</option>{receipts.map((p:any)=><option key={p.id} value={p.id}>{p.payment_no} · {p.currency} {money.format(p.available)} available · {date(p.payment_date)}</option>)}</select><input type="number" min="0" step="any" value={alloc.amount} onChange={e=>setAlloc({...alloc,amount:e.target.value})} placeholder="Allocation amount *" className={field}/><input value={alloc.notes} onChange={e=>setAlloc({...alloc,notes:e.target.value})} placeholder="Allocation note" className={field}/><p className="text-xs text-slate-500">Only completed, unapplied receipts in {selectedRow.currency} are shown. Over-allocation is blocked by the database.</p><button disabled={!!busy} onClick={()=>void saveAllocation()} className="w-full rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold disabled:opacity-40">Allocate Receipt</button></div>}
 </div></div>}
 </main>
}
function Badge({v}:{v:string}){const bad=["disputed","escalated","cancelled","overdue","failed"].includes(v),good=["paid","closed","resolved","clear","completed"].includes(v);return <span className={`rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase ${bad?"border-red-500/30 bg-red-500/10 text-red-300":good?"border-emerald-500/30 bg-emerald-500/10 text-emerald-300":"border-slate-700 bg-slate-900 text-slate-300"}`}>{v}</span>}
function K({l,v,warn=false}:{l:string;v:string;warn?:boolean}){return <div className="rounded-xl border border-slate-800 bg-slate-950/40 p-4"><p className="text-xs text-slate-500">{l}</p><p className={`mt-1 font-semibold ${warn?"text-red-300":"text-white"}`}>{v}</p></div>}
