"use client";

import { useEffect,useMemo,useState } from "react";
import { addCollectionActivity,allocateReceipt,createReceivable,deleteReceivable,getReceivablesWorkspace,updateReceivable } from "@/lib/receivables-workspace";

const money=(n:number)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(n||0);
const d=(v?:string)=>v?new Date(v).toLocaleDateString("en-GB"):"—";

export function ReceivablesWorkspace(){
 const [data,setData]=useState<any>({invoices:[],payments:[],allocations:[],activities:[],customers:[],profiles:[],deals:[],shipments:[]});
 const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [q,setQ]=useState(""); const [status,setStatus]=useState("all"); const [currency,setCurrency]=useState("all"); const [selected,setSelected]=useState<any>(null); const [panel,setPanel]=useState<"invoice"|"followup"|"allocate"|null>(null);
 const [form,setForm]=useState<any>({customer_id:"",invoice_no:"",currency:"AED",amount:"",tax_amount:"0",issue_date:new Date().toISOString().slice(0,10),due_date:"",deal_id:"",shipment_id:"",collection_owner_id:"",notes:""});
 const [follow,setFollow]=useState<any>({activity_type:"follow_up",channel:"email",contact_person:"",notes:"",outcome:"",next_follow_up_at:"",promised_payment_date:""});
 const [alloc,setAlloc]=useState<any>({payment_id:"",amount:"",notes:""});
 async function load(){try{setLoading(true);setError("");setData(await getReceivablesWorkspace())}catch(e:any){setError(e.message||"Unable to load receivables")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const allocByInv=useMemo(()=>Object.fromEntries(data.invoices.map((i:any)=>[i.id,data.allocations.filter((a:any)=>a.invoice_id===i.id).reduce((s:number,a:any)=>s+Number(a.amount||0),0)])),[data]);
 const rows=useMemo(()=>data.invoices.map((i:any)=>{const paid=Number(allocByInv[i.id]||0),total=Number(i.total_amount||0),out=Math.max(0,total-paid),age=i.due_date?Math.floor((Date.now()-new Date(i.due_date).getTime())/86400000):0;return {...i,paid,outstanding:out,days_overdue:Math.max(0,age)}}).filter((i:any)=>{const text=`${i.invoice_no} ${i.customer?.company_name||""} ${i.notes||""}`.toLowerCase();return text.includes(q.toLowerCase())&&(status==="all"||String(i.status).toLowerCase()===status)&&(currency==="all"||i.currency===currency)}),[data,allocByInv,q,status,currency]);
 const totals=useMemo(()=>{const open=rows.filter((r:any)=>r.outstanding>0);return {outstanding:open.reduce((s:number,r:any)=>s+r.outstanding,0),overdue:open.filter((r:any)=>r.days_overdue>0).reduce((s:number,r:any)=>s+r.outstanding,0),disputed:open.filter((r:any)=>r.dispute_status!=="clear").reduce((s:number,r:any)=>s+r.outstanding,0),promises:open.filter((r:any)=>r.promised_payment_date).reduce((s:number,r:any)=>s+r.outstanding,0)}},[rows]);
 const currencies=[...new Set(data.invoices.map((x:any)=>x.currency).filter(Boolean))] as string[];
 const activeCurrency=currency==="all"?(currencies.length===1?currencies[0]:"Mixed"):currency;
 async function saveInvoice(){try{if(!form.customer_id||!form.amount||!form.issue_date||!form.due_date)throw new Error("Customer, amount, issue date and due date are required");await createReceivable(form);setPanel(null);setForm({...form,customer_id:"",invoice_no:"",amount:"",tax_amount:"0",due_date:"",deal_id:"",shipment_id:"",notes:""});await load()}catch(e:any){setError(e.message)}}
 async function saveFollow(){try{if(!selected) return;await addCollectionActivity({...follow,invoice_id:selected.id});setPanel(null);setFollow({activity_type:"follow_up",channel:"email",contact_person:"",notes:"",outcome:"",next_follow_up_at:"",promised_payment_date:""});await load()}catch(e:any){setError(e.message)}}
 async function saveAlloc(){try{if(!selected||!alloc.payment_id||!alloc.amount)throw new Error("Receipt and amount are required");await allocateReceipt({...alloc,invoice_id:selected.id});setPanel(null);setAlloc({payment_id:"",amount:"",notes:""});await load()}catch(e:any){setError(e.message)}}
 async function patch(id:string,p:any){try{await updateReceivable(id,p);await load(); if(selected?.id===id)setSelected({...selected,...p})}catch(e:any){setError(e.message)}}
 const availableReceipts=data.payments.map((p:any)=>{const used=data.allocations.filter((a:any)=>a.payment_id===p.id).reduce((s:number,a:any)=>s+Number(a.amount||0),0);return {...p,available:Math.max(0,Number(p.amount||0)-used)}}).filter((p:any)=>p.available>0);
 return <main className="min-h-screen bg-[#060a12] p-5 text-white md:p-8"><div className="mx-auto max-w-[1700px]">
  <header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.24em] text-blue-400">Finance Operations</p><h1 className="mt-2 text-3xl font-bold">Accounts Receivable Control</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">Invoice control, collections, partial receipts, allocation, aging, disputes, credit hold and customer follow-up in one workspace.</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border border-slate-700 px-4 py-3 text-sm font-semibold">Refresh</button><button onClick={()=>{setSelected(null);setPanel("invoice")}} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold">+ New Receivable</button></div></header>
  {error&&<div className="mt-4 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">{error}<button onClick={()=>setError("")} className="float-right">×</button></div>}
  <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Outstanding",totals.outstanding],["Overdue",totals.overdue],["Disputed",totals.disputed],["Promise to Pay",totals.promises]].map(([l,v])=><article key={String(l)} className="rounded-2xl border border-slate-800 bg-[#0d1423] p-5"><p className="text-sm text-slate-400">{l}</p><p className="mt-3 text-2xl font-bold">{activeCurrency} {money(Number(v))}</p></article>)}</section>
  <section className="mt-5 flex flex-col gap-3 rounded-2xl border border-slate-800 bg-[#0d1423] p-4 lg:flex-row"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search invoice, customer or notes..." className="min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 outline-none"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3"><option value="all">All status</option><option value="draft">Draft</option><option value="issued">Issued</option><option value="partially_paid">Partially paid</option><option value="paid">Paid</option><option value="cancelled">Cancelled</option></select><select value={currency} onChange={e=>setCurrency(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3"><option value="all">All currencies</option>{currencies.map(c=><option key={c}>{c}</option>)}</select></section>
  <section className="mt-5 overflow-hidden rounded-2xl border border-slate-800 bg-[#0d1423]"><div className="overflow-x-auto"><table className="min-w-[1250px] w-full text-left text-sm"><thead className="bg-slate-950/70 text-xs uppercase text-slate-500"><tr>{["Invoice","Customer","Total","Paid","Outstanding","Due","Aging","Collection","Dispute","Actions"].map(h=><th key={h} className="px-4 py-4">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-800">{loading?<tr><td colSpan={10} className="p-8 text-center text-slate-500">Loading...</td></tr>:rows.length===0?<tr><td colSpan={10} className="p-8 text-center text-slate-500">No receivables found.</td></tr>:rows.map((r:any)=><tr key={r.id} className="align-top hover:bg-slate-900/50"><td className="px-4 py-4"><button onClick={()=>setSelected(r)} className="font-mono text-xs text-blue-300 hover:underline">{r.invoice_no}</button><div className="mt-1 text-xs text-slate-500">{r.currency} · {r.status}</div></td><td className="px-4 py-4 font-semibold">{r.customer?.company_name||"—"}</td><td className="px-4 py-4">{money(Number(r.total_amount))}</td><td className="px-4 py-4 text-emerald-300">{money(r.paid)}</td><td className="px-4 py-4 font-semibold">{money(r.outstanding)}</td><td className="px-4 py-4">{d(r.due_date)}</td><td className={`px-4 py-4 ${r.days_overdue>0?"text-red-300":"text-slate-400"}`}>{r.days_overdue>0?`${r.days_overdue} days overdue":"Current"}</td><td className="px-4 py-4"><select value={r.collection_status||"open"} onChange={e=>patch(r.id,{collection_status:e.target.value})} className="rounded-lg border border-slate-700 bg-slate-950 px-2 py-1 text-xs"><option value="open">Open</option><option value="follow_up">Follow-up</option><option value="promise">Promise</option><option value="escalated">Escalated</option><option value="closed">Closed</option></select></td><td className="px-4 py-4"><select value={r.dispute_status||"clear"} onChange={e=>patch(r.id,{dispute_status:e.target.value})} className="rounded-lg border border-slate-700 bg-slate-950 px-2 py-1 text-xs"><option value="clear">Clear</option><option value="query">Query</option><option value="disputed">Disputed</option><option value="resolved">Resolved</option></select></td><td className="px-4 py-4"><div className="flex flex-wrap gap-2"><button onClick={()=>{setSelected(r);setPanel("followup")}} className="rounded-lg border border-slate-700 px-2 py-1 text-xs">Follow-up</button><button onClick={()=>{setSelected(r);setPanel("allocate")}} className="rounded-lg border border-emerald-700 px-2 py-1 text-xs text-emerald-300">Allocate</button></div></td></tr>)}</tbody></table></div></section>
  {selected&&<section className="mt-5 rounded-2xl border border-slate-800 bg-[#0d1423] p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-blue-400">Receivable File</p><h2 className="mt-1 text-xl font-semibold">{selected.invoice_no} · {selected.customer?.company_name||"Customer"}</h2><p className="mt-2 text-sm text-slate-400">Outstanding {selected.currency} {money(Math.max(0,Number(selected.total_amount)-Number(allocByInv[selected.id]||0)))}</p></div><div className="flex flex-wrap gap-2"><label className="flex items-center gap-2 rounded-xl border border-slate-700 px-3 py-2 text-sm"><input type="checkbox" checked={!!selected.credit_hold} onChange={e=>patch(selected.id,{credit_hold:e.target.checked})}/>Credit Hold</label><button onClick={()=>{setSelected(null);setPanel(null)}} className="rounded-xl border border-slate-700 px-4 py-2 text-sm">Close</button></div></div>
   <div className="mt-5 grid gap-4 lg:grid-cols-3"><div className="rounded-xl border border-slate-800 bg-slate-950/40 p-4"><p className="text-xs text-slate-500">Collection owner</p><select value={selected.collection_owner_id||""} onChange={e=>patch(selected.id,{collection_owner_id:e.target.value||null})} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"><option value="">Unassigned</option>{data.profiles.map((p:any)=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></div><div className="rounded-xl border border-slate-800 bg-slate-950/40 p-4"><p className="text-xs text-slate-500">Promise date</p><input type="date" value={selected.promised_payment_date||""} onChange={e=>patch(selected.id,{promised_payment_date:e.target.value||null,collection_status:e.target.value?"promise":selected.collection_status})} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"/></div><div className="rounded-xl border border-slate-800 bg-slate-950/40 p-4"><p className="text-xs text-slate-500">Next follow-up</p><input type="datetime-local" value={selected.next_follow_up_at?selected.next_follow_up_at.slice(0,16):""} onChange={e=>patch(selected.id,{next_follow_up_at:e.target.value?new Date(e.target.value).toISOString():null})} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"/></div></div>
   <div className="mt-5"><h3 className="font-semibold">Collection history</h3><div className="mt-3 space-y-2">{data.activities.filter((a:any)=>a.invoice_id===selected.id).slice(0,10).map((a:any)=><div key={a.id} className="rounded-xl border border-slate-800 p-3 text-sm"><div className="flex justify-between gap-4"><span className="font-medium">{a.activity_type} · {a.channel||"—"}</span><span className="text-xs text-slate-500">{new Date(a.activity_at).toLocaleString()}</span></div><p className="mt-1 text-slate-400">{a.notes||a.outcome||"No notes"}</p></div>)}{!data.activities.some((a:any)=>a.invoice_id===selected.id)&&<p className="text-sm text-slate-500">No collection activity yet.</p>}</div></div>
   <div className="mt-5 border-t border-slate-800 pt-4"><button onClick={async()=>{if(confirm("Delete this receivable? Only draft/cancelled invoices without allocations can be deleted.")){try{await deleteReceivable(selected.id);setSelected(null);await load()}catch(e:any){setError(e.message)}}}} className="text-xs text-red-300">Delete eligible invoice</button></div>
  </section>}
  {panel&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-2xl border border-slate-700 bg-[#0d1423] p-6"><div className="flex justify-between"><h2 className="text-xl font-semibold">{panel==="invoice"?"New Receivable":panel==="followup"?"Collection Follow-up":"Allocate Receipt"}</h2><button onClick={()=>setPanel(null)}>×</button></div>
   {panel==="invoice"&&<div className="mt-5 grid gap-3 md:grid-cols-2"><select value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"><option value="">Select customer *</option>{data.customers.map((c:any)=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select><input value={form.invoice_no} onChange={e=>setForm({...form,invoice_no:e.target.value})} placeholder="Invoice No. (auto if blank)" className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"/><select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"><option>AED</option><option>USD</option><option>EUR</option><option>GBP</option><option>IRR</option></select><input type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="Net amount *" className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"/><input type="number" value={form.tax_amount} onChange={e=>setForm({...form,tax_amount:e.target.value})} placeholder="Tax amount" className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"/><input type="date" value={form.issue_date} onChange={e=>setForm({...form,issue_date:e.target.value})} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"/><input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"/><select value={form.collection_owner_id} onChange={e=>setForm({...form,collection_owner_id:e.target.value})} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"><option value="">Collection owner</option>{data.profiles.map((p:any)=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select><select value={form.deal_id} onChange={e=>setForm({...form,deal_id:e.target.value})} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"><option value="">Link deal</option>{data.deals.filter((x:any)=>!form.customer_id||x.customer_id===form.customer_id).map((x:any)=><option key={x.id} value={x.id}>{x.deal_no} {x.commodity?`· ${x.commodity}`:""}</option>)}</select><select value={form.shipment_id} onChange={e=>setForm({...form,shipment_id:e.target.value})} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"><option value="">Link shipment</option>{data.shipments.filter((x:any)=>!form.customer_id||x.customer_id===form.customer_id).map((x:any)=><option key={x.id} value={x.id}>{x.shipment_no}</option>)}</select><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Internal notes" className="min-h-24 rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 md:col-span-2"/><button onClick={saveInvoice} className="rounded-xl bg-emerald-600 px-5 py-3 font-semibold md:col-span-2">Create Receivable</button></div>}
   {panel==="followup"&&<div className="mt-5 grid gap-3 md:grid-cols-2"><select value={follow.activity_type} onChange={e=>setFollow({...follow,activity_type:e.target.value})} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"><option value="follow_up">Follow-up</option><option value="reminder">Reminder</option><option value="call">Call</option><option value="escalation">Escalation</option><option value="promise">Promise to pay</option><option value="dispute">Dispute discussion</option></select><select value={follow.channel} onChange={e=>setFollow({...follow,channel:e.target.value})} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"><option>email</option><option>phone</option><option>whatsapp</option><option>meeting</option><option>letter</option></select><input value={follow.contact_person} onChange={e=>setFollow({...follow,contact_person:e.target.value})} placeholder="Contact person" className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"/><input value={follow.outcome} onChange={e=>setFollow({...follow,outcome:e.target.value})} placeholder="Outcome" className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"/><input type="datetime-local" value={follow.next_follow_up_at} onChange={e=>setFollow({...follow,next_follow_up_at:e.target.value?new Date(e.target.value).toISOString():""})} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"/><input type="date" value={follow.promised_payment_date} onChange={e=>setFollow({...follow,promised_payment_date:e.target.value})} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"/><textarea value={follow.notes} onChange={e=>setFollow({...follow,notes:e.target.value})} placeholder="Follow-up notes" className="min-h-28 rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 md:col-span-2"/><button onClick={saveFollow} className="rounded-xl bg-blue-600 px-5 py-3 font-semibold md:col-span-2">Save Activity</button></div>}
   {panel==="allocate"&&<div className="mt-5 grid gap-3"><select value={alloc.payment_id} onChange={e=>setAlloc({...alloc,payment_id:e.target.value})} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"><option value="">Select unapplied receipt *</option>{availableReceipts.filter((p:any)=>!selected||p.currency===selected.currency).map((p:any)=><option key={p.id} value={p.id}>{p.payment_no} · {p.currency} {money(p.available)} available · {d(p.payment_date)}</option>)}</select><input type="number" value={alloc.amount} onChange={e=>setAlloc({...alloc,amount:e.target.value})} placeholder="Allocation amount *" className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"/><textarea value={alloc.notes} onChange={e=>setAlloc({...alloc,notes:e.target.value})} placeholder="Allocation note" className="min-h-24 rounded-xl border border-slate-700 bg-slate-950 px-3 py-3"/><button onClick={saveAlloc} className="rounded-xl bg-emerald-600 px-5 py-3 font-semibold">Allocate Receipt</button></div>}
  </div></div>}
 </div></main>
}
