"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { getShipmentRegister, getShipmentTransitionContext, transitionShipment, type ShipmentRecord, type ShipmentStatusEvent, type ShippingAccess, type ShippingGateReadiness } from "@/lib/shipments-workspace";

const statuses=["planning","booked","picked_up","in_transit","customs","delivered","cancelled"];
const pretty=(v:string|null|undefined)=>(v||"—").replaceAll("_"," ");
const panel="rounded-2xl border border-slate-800 bg-[#0d1423]";
const input="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20";
const btn="rounded-xl border border-slate-700 bg-slate-950/40 px-4 py-2.5 text-sm font-medium text-slate-200 transition hover:border-blue-500 hover:text-white disabled:cursor-not-allowed disabled:opacity-40";
const primary="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-blue-500 disabled:cursor-not-allowed disabled:opacity-40";
const danger="rounded-xl border border-red-900 bg-red-950/30 px-4 py-2.5 text-sm font-semibold text-red-300 transition hover:bg-red-950/60 disabled:cursor-not-allowed disabled:opacity-40";

function StateBadge({state}:{state:string}){const c=state==="ready"?"border-emerald-800 bg-emerald-950/40 text-emerald-300":state==="missing"||state==="expired"||state==="rejected"?"border-red-900 bg-red-950/30 text-red-300":"border-amber-900 bg-amber-950/30 text-amber-300";return <span className={`rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider ${c}`}>{pretty(state)}</span>}
function Step({name,current}:{name:string;current:string}){const a=statuses.indexOf(current),i=statuses.indexOf(name),done=i<a&&a<6,active=name===current;return <div className={`rounded-xl border px-3 py-3 text-center ${active?"border-blue-500 bg-blue-950/35 text-blue-200":done?"border-emerald-900 bg-emerald-950/20 text-emerald-300":"border-slate-800 bg-slate-950/30 text-slate-500"}`}><p className="text-[10px] uppercase tracking-wider">{pretty(name)}</p><p className="mt-1 text-xs font-semibold">{active?"Current":done?"Completed":"Pending"}</p></div>}

export function ShipmentExecutionGate(){
 const[shipments,setShipments]=useState<ShipmentRecord[]>([]),[selectedId,setSelectedId]=useState(""),[access,setAccess]=useState<ShippingAccess|null>(null),[readiness,setReadiness]=useState<ShippingGateReadiness|null>(null),[next,setNext]=useState<string|null>(null),[history,setHistory]=useState<ShipmentStatusEvent[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[action,setAction]=useState<"next"|"cancel"|"override"|null>(null),[target,setTarget]=useState(""),[reason,setReason]=useState("");
 const selected=useMemo(()=>shipments.find(x=>x.id===selectedId)||null,[shipments,selectedId]);
 const load=async(preferred?:string)=>{setLoading(true);setError(null);try{const data=await getShipmentRegister();const list=data.shipments as ShipmentRecord[];setShipments(list);const id=preferred||selectedId||list.find(x=>!["delivered","cancelled"].includes(x.status))?.id||list[0]?.id||"";setSelectedId(id);if(id){const sh=list.find(x=>x.id===id);if(sh){const c=await getShipmentTransitionContext(sh);setAccess(c.access);setReadiness(c.readiness);setNext(c.nextStatus);setHistory(c.history)}}else{setAccess(null);setReadiness(null);setNext(null);setHistory([])}}catch(e:any){setError(e.message||"Unable to load shipment gate control.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!selectedId||loading)return;const sh=shipments.find(x=>x.id===selectedId);if(!sh)return;void getShipmentTransitionContext(sh).then(c=>{setAccess(c.access);setReadiness(c.readiness);setNext(c.nextStatus);setHistory(c.history)}).catch((e:any)=>setError(e.message))},[selectedId]);
 const run=async()=>{if(!selected||!action)return;const to=action==="next"?next:action==="cancel"?"cancelled":target;if(!to)return;setBusy(true);setError(null);try{await transitionShipment(selected.id,to,reason,action==="override");setMessage(action==="override"?`Manager override recorded: ${pretty(selected.status)} → ${pretty(to)}.`:`Shipment moved to ${pretty(to)} through controlled execution.`);setAction(null);setReason("");setTarget("");await load(selected.id)}catch(e:any){setError(e.message||"Shipment transition failed.")}finally{setBusy(false)}};
 const blocked=readiness&&readiness.gate_status!=="ready";
 const active=shipments.filter(x=>!["delivered","cancelled"].includes(x.status));
 const gateBlocked=active.filter(x=>["planning","booked","picked_up","in_transit","customs"].includes(x.status)).length;
 return <section className="px-5 pt-5 text-white md:px-8 md:pt-8">
   <div className={`${panel} overflow-hidden`}>
    <div className="border-b border-slate-800 p-5 md:p-6"><div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><div className="flex flex-wrap gap-2"><span className="rounded-full border border-blue-900 bg-blue-950/30 px-3 py-1 text-[10px] font-semibold uppercase tracking-[.16em] text-blue-300">Controlled Execution</span>{access&&<span className="rounded-full border border-slate-700 bg-slate-900 px-3 py-1 text-[10px] font-semibold uppercase tracking-[.12em] text-slate-300">{access.role} · {access.canOverride?"Manager Override":access.canWrite?"Operator":"Read Only"}</span>}</div><h2 className="mt-3 text-2xl font-bold">Shipment Execution Gate</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-400">Status progression is locked to operational sequence and approved document readiness. Every transition, cancellation and management override is audited.</p></div><div className="flex flex-wrap gap-2"><Link href="/documents" className={btn}>Open Document Control</Link><button className={btn} disabled={loading} onClick={()=>void load(selectedId)}>Refresh Gate</button></div></div></div>
    {error&&<div className="m-5 rounded-xl border border-red-900 bg-red-950/25 p-3 text-sm text-red-300">{error}<button className="ml-3 text-red-200 underline" onClick={()=>setError(null)}>Dismiss</button></div>}{message&&<div className="m-5 rounded-xl border border-emerald-900 bg-emerald-950/25 p-3 text-sm text-emerald-300">{message}<button className="ml-3 text-emerald-200 underline" onClick={()=>setMessage(null)}>Dismiss</button></div>}
    <div className="grid gap-5 p-5 md:p-6 xl:grid-cols-[1.15fr_1.85fr]">
      <div className="space-y-4"><label className="text-xs font-medium text-slate-400">Controlled Shipment<select className={`${input} mt-2`} value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">Select shipment</option>{shipments.map(s=><option key={s.id} value={s.id}>{s.shipment_no} · {pretty(s.status)} · {s.origin||"?"} → {s.destination||"?"}</option>)}</select></label>
       {selected?<div className="rounded-2xl border border-slate-800 bg-slate-950/30 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-bold">{selected.shipment_no}</p><p className="mt-1 text-xs text-slate-500">{selected.origin||"—"} → {selected.destination||"—"} · {selected.mode.toUpperCase()}</p></div><span className="rounded-lg border border-blue-900 bg-blue-950/30 px-3 py-1 text-xs font-semibold capitalize text-blue-300">{pretty(selected.status)}</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><p className="text-slate-500">Next controlled step</p><p className="mt-1 font-semibold">{next?pretty(next):"Terminal status"}</p></div><div><p className="text-slate-500">Required gate</p><p className="mt-1 font-semibold capitalize">{readiness?.gate||"None"}</p></div><div><p className="text-slate-500">Gate readiness</p><p className={`mt-1 font-semibold ${blocked?"text-red-300":"text-emerald-300"}`}>{readiness?`${readiness.completion_percent}% · ${readiness.gate_status.toUpperCase()}`:"Not required"}</p></div><div><p className="text-slate-500">Cargo controls</p><p className="mt-1 font-semibold">{[selected.is_dg?"DG":null,selected.temperature_controlled?"TEMP":null].filter(Boolean).join(" + ")||"Standard"}</p></div></div></div>:<div className="rounded-xl border border-dashed border-slate-700 p-6 text-center text-sm text-slate-500">No shipment selected.</div>}
       {selected&&access?.canWrite&&!["delivered","cancelled"].includes(selected.status)&&<div className="grid gap-2 sm:grid-cols-2"><button className={primary} disabled={!next||!!blocked} onClick={()=>{setAction("next");setReason("")}}>Advance to {pretty(next)}</button><button className={danger} onClick={()=>{setAction("cancel");setReason("")}}>Cancel Shipment</button>{access.canOverride&&<button className={`${btn} sm:col-span-2`} onClick={()=>{setAction("override");setTarget("");setReason("")}}>Manager Override / Correct Status</button>}</div>}
      </div>
      <div className="space-y-4"><div className="grid gap-2 sm:grid-cols-3 xl:grid-cols-6">{statuses.slice(0,6).map(x=><Step key={x} name={x} current={selected?.status||"planning"}/>)}</div>
       <div className="rounded-2xl border border-slate-800 bg-slate-950/30"><div className="flex items-center justify-between border-b border-slate-800 p-4"><div><h3 className="font-semibold">Next Gate Checklist</h3><p className="mt-1 text-xs text-slate-500">Only approved and non-expired documents satisfy the gate.</p></div>{readiness&&<span className={`rounded-lg border px-3 py-1 text-xs font-semibold ${blocked?"border-red-900 bg-red-950/25 text-red-300":"border-emerald-900 bg-emerald-950/25 text-emerald-300"}`}>{readiness.ready_count}/{readiness.required_count} ready</span>}</div><div className="divide-y divide-slate-800">{!readiness?<div className="p-5 text-sm text-slate-500">No document gate applies to the next transition.</div>:readiness.items.length===0?<div className="p-5 text-sm text-emerald-300">No documents are required for this gate.</div>:readiness.items.map((x,i)=><div key={`${x.document_type}-${i}`} className="flex items-center justify-between gap-4 p-4"><div><p className="text-sm font-medium">{x.document_type}</p><p className="mt-1 text-xs text-slate-500">{x.document_status?`Status: ${pretty(x.document_status)}`:"No approved document linked"}{x.expiry_date?` · Expiry ${x.expiry_date}`:""}</p></div><StateBadge state={x.state}/></div>)}</div></div>
       <div className="rounded-2xl border border-slate-800 bg-slate-950/30"><div className="border-b border-slate-800 p-4"><h3 className="font-semibold">Status Audit Trail</h3></div><div className="max-h-56 divide-y divide-slate-800 overflow-y-auto">{history.length===0?<div className="p-5 text-sm text-slate-500">No controlled transitions recorded yet.</div>:history.map(h=><div key={h.id} className="grid gap-2 p-4 text-xs sm:grid-cols-[1fr_.7fr_.7fr]"><div><p className="font-semibold text-slate-200">{pretty(h.from_status)} → {pretty(h.to_status)}</p><p className="mt-1 text-slate-500">{h.actor?.full_name||"System user"} · {new Date(h.created_at).toLocaleString()}</p></div><div><p className="text-slate-500">Gate</p><p className="mt-1">{pretty(h.gate)} · {h.readiness_percent??100}%</p></div><div><p className="text-slate-500">Control</p><p className={`mt-1 ${h.override_used?"text-amber-300":"text-emerald-300"}`}>{h.override_used?"Manager override":"Standard flow"}</p>{h.reason&&<p className="mt-1 text-slate-500">{h.reason}</p>}</div></div>)}</div></div>
      </div>
    </div>
   </div>
   {action&&selected&&<div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/80 p-4"><div className="w-full max-w-xl rounded-2xl border border-slate-700 bg-[#0b1120] p-5 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-blue-400">Controlled Status Change</p><h3 className="mt-2 text-xl font-bold">{action==="next"?`Advance to ${pretty(next)}`:action==="cancel"?"Cancel Shipment":"Manager Override"}</h3><p className="mt-2 text-sm text-slate-400">{selected.shipment_no} · Current status {pretty(selected.status)}</p></div><button className="text-2xl text-slate-400" onClick={()=>setAction(null)}>×</button></div>{action==="override"&&<label className="mt-5 block text-xs text-slate-400">Target Status<select className={`${input} mt-2`} value={target} onChange={e=>setTarget(e.target.value)}><option value="">Select target status</option>{statuses.filter(x=>x!==selected.status).map(x=><option key={x} value={x}>{pretty(x)}</option>)}</select></label>}<label className="mt-4 block text-xs text-slate-400">{action==="next"?"Operational note (optional)":"Reason (required)"}<textarea className={`${input} mt-2 min-h-24`} value={reason} onChange={e=>setReason(e.target.value)} placeholder={action==="cancel"?"State the cancellation reason...":action==="override"?"Explain why the controlled sequence must be overridden...":"Add transition note..."}/></label><div className="mt-5 flex justify-end gap-2"><button className={btn} onClick={()=>setAction(null)}>Back</button><button className={action==="cancel"?danger:primary} disabled={busy||(action==="cancel"&&reason.trim().length<5)||(action==="override"&&(!target||reason.trim().length<8))} onClick={()=>void run()}>{busy?"Processing...":action==="cancel"?"Confirm Cancellation":action==="override"?"Apply Controlled Override":"Confirm Transition"}</button></div></div></div>}
  </section>
}
