import { createClient } from "@/lib/supabase/client";

export type CustomerType = "customer"|"supplier"|"both"|"agent"|"shipping_line"|"warehouse";
export type CustomerStatus = "lead"|"active"|"inactive"|"blocked";
export type Customer = {id:string;customer_code:string|null;company_name:string;customer_type:CustomerType;status:CustomerStatus;contact_person:string|null;email:string|null;phone:string|null;mobile:string|null;website:string|null;country:string|null;city:string|null;address:string|null;tax_number:string|null;registration_number:string|null;industry:string|null;source:string|null;credit_limit:number;currency:string;notes:string|null;created_by:string|null;assigned_to:string|null;created_at:string;updated_at:string};
export type CreateCustomerInput = Partial<Omit<Customer,"id"|"created_at"|"updated_at"|"created_by">> & {company_name:string;customer_type?:CustomerType};
export type CustomerAccess={role:string;canWrite:boolean;canControlCredit:boolean;canDelete:boolean};
export type CustomerEvent={id:string;customer_id:string;event_type:string;from_value:string|null;to_value:string|null;reason:string|null;metadata:any;performed_by:string|null;created_at:string;actor?:{full_name?:string|null}|null};
export type CustomerSnapshot={opportunities:number;deals:number;quotations:number;shipments:number;active_shipments:number;open_invoices:number;open_invoice_value:number;payments:number;inventory_on_hand:number;last_event_at:string|null};
const s=()=>createClient();
const clean=(v:any)=>typeof v==="string"?(v.trim()||null):v;

async function sessionUserId(){const db=s();const{data,error}=await db.auth.getSession();if(error||!data.session?.user?.id)throw new Error("Your session is not available. Please sign in again and retry.");return data.session.user.id}
export async function getCustomerAccess():Promise<CustomerAccess>{const db=s();const[{data:role,error:r},{data:w,error:we},{data:c,error:ce},{data:d,error:de}]=await Promise.all([db.rpc("customer_current_role"),db.rpc("customer_can_write"),db.rpc("customer_can_control_credit"),db.rpc("customer_can_delete")]);if(r)throw r;if(we)throw we;if(ce)throw ce;if(de)throw de;return{role:String(role||"unknown"),canWrite:!!w,canControlCredit:!!c,canDelete:!!d}}
export async function getCustomers():Promise<Customer[]>{const{data,error}=await s().from("customers").select("*").order("created_at",{ascending:false});if(error)throw error;return(data??[]) as Customer[]}
export async function getCustomerEvents(customerId:string):Promise<CustomerEvent[]>{const{data,error}=await s().from("customer_events").select("*,actor:performed_by(full_name)").eq("customer_id",customerId).order("created_at",{ascending:false}).limit(50);if(error)throw error;return(data??[]) as unknown as CustomerEvent[]}
export async function getCustomerSnapshot(customerId:string):Promise<CustomerSnapshot>{const{data,error}=await s().rpc("customer_account_snapshot_v1",{p_customer_id:customerId});if(error)throw error;return data as CustomerSnapshot}
export async function createCustomer(values:CreateCustomerInput):Promise<Customer>{const db=s();const userId=await sessionUserId();const payload:any={...values,company_name:values.company_name.trim(),customer_type:values.customer_type||"customer",status:"lead",credit_limit:0,currency:"AED",created_by:userId};for(const k of Object.keys(payload))payload[k]=clean(payload[k]);const{data,error}=await db.from("customers").insert(payload).select("*").single();if(error)throw error;if(!data?.id)throw new Error("Customer save did not return a valid record.");return data as Customer}
export async function updateCustomer(id:string,values:Partial<CreateCustomerInput>):Promise<Customer>{const payload:any={...values,updated_at:new Date().toISOString()};for(const k of ["status","credit_limit","currency","assigned_to","created_by"])delete payload[k];for(const k of Object.keys(payload))payload[k]=clean(payload[k]);const{data,error}=await s().from("customers").update(payload).eq("id",id).select("*").single();if(error)throw error;if(!data?.id)throw new Error("Customer update did not affect a record.");return data as Customer}
export async function setCustomerStatus(id:string,status:CustomerStatus,reason?:string):Promise<Customer>{const{data,error}=await s().rpc("customer_set_status_v1",{p_customer_id:id,p_status:status,p_reason:reason||null});if(error)throw error;return data as Customer}
export async function setCustomerCredit(id:string,creditLimit:number,currency:string,reason:string):Promise<Customer>{const{data,error}=await s().rpc("customer_set_credit_v1",{p_customer_id:id,p_credit_limit:creditLimit,p_currency:currency,p_reason:reason});if(error)throw error;return data as Customer}
export async function assignCustomerOwner(id:string,ownerId:string|null,reason?:string):Promise<Customer>{const{data,error}=await s().rpc("customer_assign_owner_v1",{p_customer_id:id,p_owner_id:ownerId,p_reason:reason||null});if(error)throw error;return data as Customer}
export async function deleteCustomer(id:string,reason="Customer deletion requested"):Promise<void>{const{error}=await s().rpc("customer_delete_v1",{p_customer_id:id,p_reason:reason});if(error)throw error}
