import {createClient} from "@/lib/supabase/client";

export type DealRole="admin"|"ceo"|"manager"|"dealer"|"finance"|"logistics"|"operations"|"unknown";
export type DealStatus="draft"|"pending"|"review"|"approved"|"completed"|"cancelled";
export type DealRecord={id:string;deal_no:string;customer_id:string|null;supplier_id:string|null;dealer_id:string;buy_currency:string;sell_currency:string;amount:number;buy_rate:number|null;sell_rate:number|null;profit_aed:number;status:DealStatus;notes:string|null;commodity:string|null;origin_country:string|null;destination_country:string|null;incoterm:string|null;quantity:number|null;unit:string|null;buy_price:number|null;sell_price:number|null;profit:number|null;quotation_id:string|null;opportunity_id:string|null;created_at:string;updated_at:string;customers?:{company_name:string;status:string}|null;suppliers?:{company_name:string;status:string;kyc_status:string|null;kyc_expiry_date:string|null;rating:number|null}|null;profiles?:{full_name:string}|null};
export type DealSnapshot={shipments:number;active_shipments:number;delivered_shipments:number;invoices:number;open_invoices:number;receivable_value:number;paid_invoice_value?:number;cash_receipts?:number;payment_state:string;shipping_state:string;events:number};
export type DealEvent={id:string;deal_id:string;event_type:string;from_value:string|null;to_value:string|null;reason:string|null;metadata:Record<string,unknown>;performed_by:string|null;created_at:string};
export type Approval={id:string;entity_id:string;status:string;comments:string|null;requested_at:string|null;decided_at:string|null;requested_by:string|null;approver_id:string|null};
export type DealCreateInput={customer_id:string;supplier_id:string|null;commodity:string;origin_country:string;destination_country:string;incoterm:string;quantity:number;unit:string;buy_currency:string;sell_currency:string;buy_price:number;sell_price:number;notes?:string|null};

const s=()=>createClient();
const asJson=<T>(v:unknown)=>v as T;
export async function getDealRole():Promise<DealRole>{const{data,error}=await s().rpc("deal_current_role");if(error)throw error;return (data||"unknown") as DealRole}
export async function listDealProfiles(){const{data,error}=await s().from("profiles").select("id,full_name,role,active").eq("active",true).order("full_name");if(error)throw error;return data??[]}
export async function listDeals():Promise<DealRecord[]>{const{data,error}=await s().from("deals").select("*,customers(company_name,status),suppliers(company_name,status,kyc_status,kyc_expiry_date,rating),profiles:dealer_id(full_name)").order("created_at",{ascending:false});if(error)throw error;return (data??[]) as DealRecord[]}
export async function listDealEvents(dealIds:string[]):Promise<DealEvent[]>{if(!dealIds.length)return[];const{data,error}=await s().from("deal_events").select("*").in("deal_id",dealIds).order("created_at",{ascending:false});if(error)throw error;return (data??[]) as DealEvent[]}
export async function listDealApprovals(dealIds:string[]):Promise<Approval[]>{if(!dealIds.length)return[];const{data,error}=await s().from("approvals").select("id,entity_id,status,comments,requested_at,decided_at,requested_by,approver_id").eq("entity_type","deal").in("entity_id",dealIds).order("requested_at",{ascending:false});if(error)throw error;return (data??[]) as Approval[]}
export async function getDealSnapshot(id:string):Promise<DealSnapshot>{const{data,error}=await s().rpc("deal_account_snapshot_v1",{p_deal_id:id});if(error)throw error;return asJson<DealSnapshot>(data)}
export async function listCustomersForDeal(){const{data,error}=await s().from("customers").select("id,company_name,status,customer_type,currency").in("customer_type",["customer","both"]).eq("status","active").order("company_name");if(error)throw error;return data??[]}
export async function listSuppliersForDeal(){const{data,error}=await s().from("suppliers").select("id,company_name,status,kyc_status,kyc_expiry_date,rating,currency").eq("status","active").order("company_name");if(error)throw error;return data??[]}
export async function createDealMaster(v:DealCreateInput):Promise<DealRecord>{const client=s();const{data:{user},error:userError}=await client.auth.getUser();if(userError||!user)throw new Error("Authentication required.");const qty=Number(v.quantity)||0,buy=Number(v.buy_price)||0,sell=Number(v.sell_price)||0;if(!v.customer_id)throw new Error("Customer is required.");if(!v.commodity.trim())throw new Error("Commodity is required.");if(qty<=0)throw new Error("Quantity must be greater than zero.");if(sell<0||buy<0)throw new Error("Commercial prices cannot be negative.");const amount=qty*sell,profit=qty*(sell-buy);const dealNo=`VTC-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${String(Date.now()).slice(-6)}`;const{data,error}=await client.from("deals").insert({deal_no:dealNo,customer_id:v.customer_id,supplier_id:v.supplier_id||null,dealer_id:user.id,buy_currency:v.buy_currency,sell_currency:v.sell_currency,amount,buy_price:buy,sell_price:sell,profit,profit_aed:v.sell_currency==="AED"?profit:0,commodity:v.commodity.trim(),origin_country:v.origin_country.trim()||null,destination_country:v.destination_country.trim()||null,incoterm:v.incoterm.trim()||null,quantity:qty,unit:v.unit.trim(),notes:v.notes?.trim()||null}).select("*").single();if(error)throw error;return data as DealRecord}
export async function requestApproval(id:string,comments?:string){const{data,error}=await s().rpc("deal_request_approval_v1",{p_deal_id:id,p_comments:comments||null});if(error)throw error;return data as Approval}
export async function decideDealApproval(approvalId:string,decision:"approved"|"rejected",comments?:string){const{data,error}=await s().rpc("deal_decide_approval_v1",{p_approval_id:approvalId,p_decision:decision,p_comments:comments||null});if(error)throw error;return data as Approval}
export async function createShipmentFromDeal(id:string){const{data,error}=await s().rpc("deal_create_shipment_v1",{p_deal_id:id});if(error)throw error;return data}
export async function cancelDeal(id:string,reason:string){const{data,error}=await s().rpc("deal_cancel_v1",{p_deal_id:id,p_reason:reason});if(error)throw error;return data as DealRecord}
export async function completeDeal(id:string,reason?:string){const{data,error}=await s().rpc("deal_complete_v1",{p_deal_id:id,p_reason:reason||null});if(error)throw error;return data as DealRecord}
export async function assignDealOwner(id:string,ownerId:string,reason?:string){const{data,error}=await s().rpc("deal_assign_owner_v1",{p_deal_id:id,p_owner_id:ownerId,p_reason:reason||null});if(error)throw error;return data as DealRecord}
export async function deleteDeal(id:string,reason:string){const{data,error}=await s().rpc("deal_delete_v1",{p_deal_id:id,p_reason:reason});if(error)throw error;return Boolean(data)}
