import {createClient} from "@/lib/supabase/client";

export type EnterpriseApproval={id:string;entity_type:string;entity_id:string;approval_type:string;module:string;reference:string|null;amount:number|null;currency:string|null;priority:string;status:string;comments:string|null;requested_at:string;decided_at:string|null;due_at:string|null;escalation_level:number;requested_by:string|null;approver_id:string|null;requester:string;approver:string;overdue:boolean;can_decide:boolean};
export type OperationalException={id:string;exception_key:string;module:string;entity_type:string;entity_id:string|null;reference:string|null;title:string;detail:string|null;severity:"low"|"medium"|"high"|"critical";owner_id:string|null;status:string;detected_at:string;due_at:string|null;resolved_at:string|null;resolution_note:string|null};
export type EnterpriseSnapshot={commercial:{open_opportunities:number;draft_quotations:number;pending_quotations:number;active_deals:number};logistics:{active_shipments:number;delayed_shipments:number;dg_shipments:number};finance:{open_receivables:number;overdue_receivables:number;open_receivable_value:number;pending_payments:number};control:{pending_approvals:number;overdue_tasks:number;unread_notifications:number;open_exceptions:number;critical_exceptions:number};exceptions:OperationalException[]};
export type EnterpriseTask={id:string;title:string;description:string|null;entity_type:string|null;entity_id:string|null;entity_reference:string|null;assigned_to:string|null;created_by:string|null;priority:string;status:string;due_at:string|null;completed_at:string|null;created_at:string;updated_at:string};
export async function getEnterpriseApprovalQueue(){const s=createClient();const{data,error}=await s.rpc("enterprise_approval_queue_v1");if(error)throw error;return(data??[]) as EnterpriseApproval[]}
export async function decideEnterpriseApproval(id:string,decision:"approved"|"rejected",comments?:string){const s=createClient();const{data,error}=await s.rpc("enterprise_decide_approval_v1",{p_approval_id:id,p_decision:decision,p_comments:comments||null});if(error)throw error;return data}
export async function delegateEnterpriseApproval(delegateId:string,module:string,startsAt:string,endsAt:string,reason?:string){const s=createClient();const{data,error}=await s.rpc("enterprise_delegate_approval_v1",{p_delegate_id:delegateId,p_module:module||null,p_starts_at:startsAt,p_ends_at:endsAt,p_reason:reason||null});if(error)throw error;return data as string}
export async function getEnterpriseUsers(){const s=createClient();const{data,error}=await s.from("profiles").select("id,full_name,role").eq("active",true).order("full_name");if(error)throw error;return data??[]}
export async function getEnterpriseSnapshot(){const s=createClient();const{data,error}=await s.rpc("enterprise_control_snapshot_v1");if(error)throw error;return data as EnterpriseSnapshot}
export async function refreshEnterpriseExceptions(){const s=createClient();const first=await s.rpc("enterprise_refresh_exceptions_v1");if(first.error)throw first.error;const sync=await s.rpc("enterprise_sync_exception_notifications_v1");if(sync.error)throw sync.error;return first.data}
export async function decideEnterpriseException(id:string,action:"acknowledged"|"resolved"|"dismissed"|"open",note?:string){const s=createClient();const{data,error}=await s.rpc("enterprise_exception_decide_v1",{p_exception_id:id,p_action:action,p_note:note||null});if(error)throw error;return data}
export async function getLifecycleSnapshot(dealId:string){const s=createClient();const{data,error}=await s.rpc("enterprise_lifecycle_snapshot_v1",{p_deal_id:dealId});if(error)throw error;return data as any}
export async function getActiveDeals(){const s=createClient();const{data,error}=await s.from("deals").select("id,deal_no,status,quotation_id,opportunity_id").order("updated_at",{ascending:false}).limit(200);if(error)throw error;return data??[]}
export async function getEnterpriseTasks(){const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)throw new Error("Authentication required");const{data,error}=await s.from("tasks").select("*").or(`assigned_to.eq.${user.id},created_by.eq.${user.id}`).order("due_at",{ascending:true,nullsFirst:false});if(error)throw error;return(data??[]) as EnterpriseTask[]}
export async function setEnterpriseTaskStatus(id:string,status:"open"|"in_progress"|"blocked"|"done"|"cancelled"){const s=createClient();const patch:any={status,updated_at:new Date().toISOString(),completed_at:status==="done"?new Date().toISOString():null};const{data,error}=await s.from("tasks").update(patch).eq("id",id).select().single();if(error)throw error;return data as EnterpriseTask}
export async function createEnterpriseTask(payload:{title:string;description?:string;entity_type?:string;entity_id?:string|null;entity_reference?:string;assigned_to:string;priority:string;due_at?:string|null}){const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)throw new Error("Authentication required");const{data,error}=await s.from("tasks").insert({...payload,created_by:user.id,status:"open"}).select().single();if(error)throw error;return data as EnterpriseTask}
export async function getMyNotifications(){const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)throw new Error("Authentication required");const{data,error}=await s.from("notifications").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).limit(200);if(error)throw error;return data??[]}
export async function markEnterpriseNotification(id:string,read=true){const s=createClient();const{error}=await s.from("notifications").update({is_read:read,read_at:read?new Date().toISOString():null}).eq("id",id);if(error)throw error}
