import {createClient} from "@/lib/supabase/client";

export type EnterpriseApproval={id:string;entity_type:string;entity_id:string;approval_type:string;module:string;reference:string|null;amount:number|null;currency:string|null;priority:string;status:string;comments:string|null;requested_at:string;decided_at:string|null;due_at:string|null;escalation_level:number;requested_by:string|null;approver_id:string|null;requester:string;approver:string;overdue:boolean;can_decide:boolean};
export type OperationalException={id:string;exception_key:string;module:string;entity_type:string;entity_id:string|null;reference:string|null;title:string;detail:string|null;severity:"low"|"medium"|"high"|"critical";owner_id:string|null;status:string;detected_at:string;due_at:string|null;resolved_at:string|null;resolution_note:string|null};
export type EnterpriseSnapshot={commercial:{open_opportunities:number;draft_quotations:number;pending_quotations:number;active_deals:number};logistics:{active_shipments:number;delayed_shipments:number;dg_shipments:number};finance:{open_receivables:number;overdue_receivables:number;open_receivable_value:number;pending_payments:number};control:{pending_approvals:number;overdue_tasks:number;unread_notifications:number;open_exceptions:number;critical_exceptions:number};exceptions:OperationalException[]};

export async function getEnterpriseApprovalQueue(){const s=createClient();const{data,error}=await s.rpc("enterprise_approval_queue_v1");if(error)throw error;return(data??[]) as EnterpriseApproval[]}
export async function decideEnterpriseApproval(id:string,decision:"approved"|"rejected",comments?:string){const s=createClient();const{data,error}=await s.rpc("enterprise_decide_approval_v1",{p_approval_id:id,p_decision:decision,p_comments:comments||null});if(error)throw error;return data}
export async function delegateEnterpriseApproval(delegateId:string,module:string,startsAt:string,endsAt:string,reason?:string){const s=createClient();const{data,error}=await s.rpc("enterprise_delegate_approval_v1",{p_delegate_id:delegateId,p_module:module||null,p_starts_at:startsAt,p_ends_at:endsAt,p_reason:reason||null});if(error)throw error;return data as string}
export async function getEnterpriseUsers(){const s=createClient();const{data,error}=await s.from("profiles").select("id,full_name,role").eq("active",true).order("full_name");if(error)throw error;return data??[]}
export async function getEnterpriseSnapshot(){const s=createClient();const{data,error}=await s.rpc("enterprise_control_snapshot_v1");if(error)throw error;return data as EnterpriseSnapshot}
export async function refreshEnterpriseExceptions(){const s=createClient();const{data,error}=await s.rpc("enterprise_refresh_exceptions_v1");if(error)throw error;return data}
export async function decideEnterpriseException(id:string,action:"acknowledged"|"resolved"|"dismissed"|"open",note?:string){const s=createClient();const{data,error}=await s.rpc("enterprise_exception_decide_v1",{p_exception_id:id,p_action:action,p_note:note||null});if(error)throw error;return data}
export async function getLifecycleSnapshot(dealId:string){const s=createClient();const{data,error}=await s.rpc("enterprise_lifecycle_snapshot_v1",{p_deal_id:dealId});if(error)throw error;return data as any}
export async function getActiveDeals(){const s=createClient();const{data,error}=await s.from("deals").select("id,deal_no,status,quotation_id,opportunity_id").order("updated_at",{ascending:false}).limit(200);if(error)throw error;return data??[]}
