import { createClient } from "@/lib/supabase/client";

export type ShipmentRecord={id:string;shipment_no:string;deal_id:string|null;quotation_id:string|null;customer_id:string|null;supplier_id:string|null;mode:string;status:string;priority:string|null;risk_level:string|null;exception_status:string|null;customs_status:string|null;customs_reference:string|null;incoterm:string|null;origin:string|null;destination:string|null;place_of_receipt:string|null;port_of_loading:string|null;port_of_discharge:string|null;place_of_delivery:string|null;shipper_name:string|null;consignee_name:string|null;notify_party:string|null;carrier:string|null;booking_no:string|null;container_no:string|null;bl_no:string|null;awb_no:string|null;vessel_name:string|null;voyage_no:string|null;flight_no:string|null;etd:string|null;eta:string|null;actual_delivery_date:string|null;cargo_description:string|null;cargo_type:string|null;package_count:number|null;package_type:string|null;net_weight_kg:number|null;weight_kg:number|null;volume_cbm:number|null;is_dg:boolean|null;un_number:string|null;temperature_controlled:boolean|null;target_temperature_c:number|null;cost:number|null;currency:string|null;owner_id:string|null;notes:string|null;last_tracking_at:string|null;created_at:string|null;updated_at:string|null;customer?:{company_name?:string|null}|null;supplier?:{company_name?:string|null}|null;owner?:{full_name?:string|null}|null;deal?:{deal_no?:string|null}|null;quotation?:{quotation_no?:string|null}|null};
export type ShipmentUnit={id:string;shipment_id:string;unit_type:string;unit_no:string|null;equipment_type:string|null;seal_no:string|null;quantity:number|null;weight_kg:number|null;volume_cbm:number|null;status:string|null;current_location:string|null;last_event_at:string|null;notes:string|null};
export type ShipmentMilestone={id:string;shipment_id:string;milestone_type:string;title:string;planned_at:string|null;actual_at:string|null;status:string;location:string|null;responsible_party:string|null;notes:string|null;sequence_no:number|null};
export type ShipmentEvent={id:string;shipment_id:string;unit_id:string|null;event_type:string;event_time:string;location:string|null;source:string|null;reference_no:string|null;details:string|null;is_exception:boolean|null;severity:string|null};
export type ShipmentCharge={id:string;shipment_id:string;charge_type:string;description:string|null;vendor_id:string|null;currency:string;estimated_amount:number|null;actual_amount:number|null;billable_amount:number|null;status:string|null;reference_no:string|null;notes:string|null};
export type SelectOption={id:string;label:string};
const s=()=>createClient();const trim=(v:any)=>typeof v==="string"?(v.trim()||null):v;

export async function getShipmentRegister(){const db=s();const [shipments,customers,suppliers,profiles,deals,quotations]=await Promise.all([db.from("shipments").select("*,customer:customers(company_name),supplier:suppliers(company_name),owner:profiles(full_name),deal:deals(deal_no),quotation:quotations(quotation_no)").order("created_at",{ascending:false}),db.from("customers").select("id,company_name").order("company_name"),db.from("suppliers").select("id,company_name").order("company_name"),db.from("profiles").select("id,full_name").eq("active",true).order("full_name"),db.from("deals").select("id,deal_no").order("created_at",{ascending:false}),db.from("quotations").select("id,quotation_no").order("created_at",{ascending:false})]);const failed=[shipments,customers,suppliers,profiles,deals,quotations].find((r:any)=>r.error) as any;if(failed?.error)throw failed.error;return{shipments:(shipments.data??[]) as unknown as ShipmentRecord[],customers:(customers.data??[]).map((x:any)=>({id:x.id,label:x.company_name})),suppliers:(suppliers.data??[]).map((x:any)=>({id:x.id,label:x.company_name})),profiles:(profiles.data??[]).map((x:any)=>({id:x.id,label:x.full_name})),deals:(deals.data??[]).map((x:any)=>({id:x.id,label:x.deal_no})),quotations:(quotations.data??[]).map((x:any)=>({id:x.id,label:x.quotation_no||"Unnumbered quotation"}))}}
export async function getShipmentDetail(id:string){const db=s();const [u,m,e,c,d]=await Promise.all([db.from("shipment_units").select("*").eq("shipment_id",id).order("created_at"),db.from("shipment_milestones").select("*").eq("shipment_id",id).order("sequence_no"),db.from("shipment_events").select("*").eq("shipment_id",id).order("event_time",{ascending:false}),db.from("shipment_charges").select("*,vendor:suppliers(company_name)").eq("shipment_id",id).order("created_at"),db.from("documents").select("*").eq("entity_type","shipment").eq("entity_id",id).order("created_at",{ascending:false})]);const failed=[u,m,e,c,d].find((r:any)=>r.error) as any;if(failed?.error)throw failed.error;return{units:u.data??[],milestones:m.data??[],events:e.data??[],charges:c.data??[],documents:d.data??[]}}
export async function saveShipment(values:Partial<ShipmentRecord>&{id?:string}){const db=s();const{data:{user}}=await db.auth.getUser();if(!user)throw new Error("Authentication required");const payload:any={...values,updated_at:new Date().toISOString()};delete payload.id;for(const k of ["customer","supplier","owner","deal","quotation"])delete payload[k];Object.keys(payload).forEach(k=>payload[k]=trim(payload[k]));if(values.id){const{data,error}=await db.from("shipments").update(payload).eq("id",values.id).select("*").single();if(error)throw error;return data}payload.shipment_no=values.shipment_no||`SHP-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${String(Date.now()).slice(-6)}`;payload.created_by=user.id;payload.owner_id=payload.owner_id||user.id;const{data,error}=await db.from("shipments").insert(payload).select("*").single();if(error)throw error;return data}
export async function deleteShipment(id:string){const db=s();const{count,error}=await db.from("invoices").select("id",{count:"exact",head:true}).eq("shipment_id",id);if(error)throw error;if((count??0)>0)throw new Error("Shipment has financial records and cannot be deleted. Cancel it instead.");const r=await db.from("shipments").delete().eq("id",id);if(r.error)throw r.error}
export async function addUnit(shipment_id:string,v:Partial<ShipmentUnit>){const{data,error}=await s().from("shipment_units").insert({shipment_id,unit_type:v.unit_type||"container",unit_no:trim(v.unit_no),equipment_type:trim(v.equipment_type),seal_no:trim(v.seal_no),quantity:Number(v.quantity||1),weight_kg:v.weight_kg||null,volume_cbm:v.volume_cbm||null,status:v.status||"planned",current_location:trim(v.current_location),notes:trim(v.notes)}).select().single();if(error)throw error;return data}
export async function updateUnit(id:string,patch:Partial<ShipmentUnit>){const{data,error}=await s().from("shipment_units").update({...patch,updated_at:new Date().toISOString()}).eq("id",id).select().single();if(error)throw error;return data}
export async function deleteUnit(id:string){const{error}=await s().from("shipment_units").delete().eq("id",id);if(error)throw error}
export async function addMilestone(shipment_id:string,v:Partial<ShipmentMilestone>){const{data,error}=await s().from("shipment_milestones").insert({shipment_id,milestone_type:v.milestone_type||"custom",title:v.title||"Milestone",planned_at:v.planned_at||null,status:v.status||"pending",location:trim(v.location),responsible_party:trim(v.responsible_party),notes:trim(v.notes),sequence_no:v.sequence_no||1}).select().single();if(error)throw error;return data}
export async function updateMilestone(id:string,patch:Partial<ShipmentMilestone>){const p:any={...patch,updated_at:new Date().toISOString()};if(p.status==="completed"&&!p.actual_at)p.actual_at=new Date().toISOString();const{data,error}=await s().from("shipment_milestones").update(p).eq("id",id).select().single();if(error)throw error;return data}
export async function deleteMilestone(id:string){const{error}=await s().from("shipment_milestones").delete().eq("id",id);if(error)throw error}
export async function addEvent(shipment_id:string,v:Partial<ShipmentEvent>){const db=s();const{data:{user}}=await db.auth.getUser();const payload={shipment_id,unit_id:v.unit_id||null,event_type:v.event_type||"update",event_time:v.event_time||new Date().toISOString(),location:trim(v.location),source:trim(v.source)||"manual",reference_no:trim(v.reference_no),details:trim(v.details),is_exception:Boolean(v.is_exception),severity:v.severity||"info",created_by:user?.id||null};const{data,error}=await db.from("shipment_events").insert(payload).select().single();if(error)throw error;const patch:any={last_tracking_at:payload.event_time,updated_at:new Date().toISOString()};if(payload.is_exception)patch.exception_status=payload.severity==="critical"?"escalated":"watch";await db.from("shipments").update(patch).eq("id",shipment_id);return data}
export async function deleteEvent(id:string){const{error}=await s().from("shipment_events").delete().eq("id",id);if(error)throw error}
export async function addCharge(shipment_id:string,v:Partial<ShipmentCharge>){const{data,error}=await s().from("shipment_charges").insert({shipment_id,charge_type:v.charge_type||"other",description:trim(v.description),vendor_id:v.vendor_id||null,currency:v.currency||"AED",estimated_amount:Number(v.estimated_amount||0),actual_amount:Number(v.actual_amount||0),billable_amount:Number(v.billable_amount||0),status:v.status||"estimated",reference_no:trim(v.reference_no),notes:trim(v.notes)}).select().single();if(error)throw error;return data}
export async function updateCharge(id:string,patch:Partial<ShipmentCharge>){const{data,error}=await s().from("shipment_charges").update({...patch,updated_at:new Date().toISOString()}).eq("id",id).select().single();if(error)throw error;return data}
export async function deleteCharge(id:string){const{error}=await s().from("shipment_charges").delete().eq("id",id);if(error)throw error}
