import {createClient} from "@/lib/supabase/client";
export type SupplierStatus="pending"|"active"|"inactive"|"blocked";
export type KycStatus="pending"|"approved"|"expired"|"rejected";
export type Supplier={id:string;supplier_code:string|null;company_name:string;status:SupplierStatus;contact_person:string|null;email:string|null;phone:string|null;website:string|null;country:string|null;city:string|null;address:string|null;tax_number:string|null;registration_number:string|null;category:string|null;currency:string|null;payment_terms:string|null;kyc_status:KycStatus|null;kyc_expiry_date:string|null;kyc_reviewed_at:string|null;kyc_reviewed_by:string|null;rating:number|null;notes:string|null;created_by:string|null;account_manager_id:string|null;created_at:string|null;updated_at:string|null};
export type SupplierAccess={role:string;canWrite:boolean;canControl:boolean;canControlTerms:boolean;canRate:boolean;canDelete:boolean};
export type SupplierEvent={id:string;supplier_id:string;event_type:string;from_value:string|null;to_value:string|null;reason:string|null;metadata:any;performed_by:string|null;created_at:string;actor?:{full_name?:string|null}|null};
export type SupplierSnapshot={quotations:number;deals:number;shipments:number;open_payables:number;open_payable_value:number;payments:number;charges:number;charge_value:number;inventory_items:number;risk_score:number;risk_band:"normal"|"watch"|"high";last_event_at:string|null};
export type SupplierMasterInput=Partial<Pick<Supplier,"supplier_code"|"company_name"|"contact_person"|"email"|"phone"|"website"|"country"|"city"|"address"|"tax_number"|"registration_number"|"category"|"notes">>&{company_name:string};
const db=()=>createClient(); const clean=(v:any)=>typeof v==="string"?(v.trim()||null):v;
async function sessionUserId(){const s=db();const{data,error}=await s.auth.getSession();if(error||!data.session?.user?.id)throw new Error("Your session is not available. Please sign in again and retry.");return data.session.user.id}
export async function getSupplierAccess():Promise<SupplierAccess>{const s=db();const [r,w,c,t,ra,d]=await Promise.all([s.rpc("supplier_current_role"),s.rpc("supplier_can_write"),s.rpc("supplier_can_control"),s.rpc("supplier_can_control_terms"),s.rpc("supplier_can_rate"),s.rpc("supplier_can_delete")]);for(const x of [r,w,c,t,ra,d])if(x.error)throw x.error;return{role:String(r.data||"unknown"),canWrite:!!w.data,canControl:!!c.data,canControlTerms:!!t.data,canRate:!!ra.data,canDelete:!!d.data}}
export async function getSuppliers():Promise<Supplier[]>{const{data,error}=await db().from("suppliers").select("*").order("created_at",{ascending:false});if(error)throw error;return(data??[]) as Supplier[]}
export async function getSupplierEvents(id:string):Promise<SupplierEvent[]>{const{data,error}=await db().from("supplier_events").select("*,actor:performed_by(full_name)").eq("supplier_id",id).order("created_at",{ascending:false}).limit(60);if(error)throw error;return(data??[]) as unknown as SupplierEvent[]}
export async function getSupplierSnapshot(id:string):Promise<SupplierSnapshot>{const{data,error}=await db().rpc("supplier_account_snapshot_v1",{p_supplier_id:id});if(error)throw error;return data as SupplierSnapshot}
export async function createSupplier(v:SupplierMasterInput){const s=db();const userId=await sessionUserId();const p:any={...v,company_name:v.company_name.trim(),created_by:userId};for(const k of Object.keys(p))p[k]=clean(p[k]);const{data,error}=await s.from("suppliers").insert(p).select("*").single();if(error)throw error;if(!data?.id)throw new Error("Supplier save did not return a valid record.");return data as Supplier}
export async function updateSupplier(id:string,v:Partial<SupplierMasterInput>){const p:any={...v,updated_at:new Date().toISOString()};for(const k of ["status","kyc_status","kyc_expiry_date","kyc_reviewed_at","kyc_reviewed_by","currency","payment_terms","rating","account_manager_id","created_by"])delete p[k];for(const k of Object.keys(p))p[k]=clean(p[k]);const{data,error}=await db().from("suppliers").update(p).eq("id",id).select("*").single();if(error)throw error;if(!data?.id)throw new Error("Supplier update did not affect a record.");return data as Supplier}
export async function setSupplierStatus(id:string,status:SupplierStatus,reason?:string){const{data,error}=await db().rpc("supplier_set_status_v1",{p_supplier_id:id,p_status:status,p_reason:reason||null});if(error)throw error;return data as Supplier}
export async function setSupplierKyc(id:string,status:KycStatus,expiry:string|null,reason?:string){const{data,error}=await db().rpc("supplier_set_kyc_v2",{p_supplier_id:id,p_kyc_status:status,p_expiry_date:expiry||null,p_reason:reason||null});if(error)throw error;return data as Supplier}
export async function setSupplierTerms(id:string,currency:string,terms:string,reason:string){const{data,error}=await db().rpc("supplier_set_terms_v1",{p_supplier_id:id,p_currency:currency,p_payment_terms:terms,p_reason:reason});if(error)throw error;return data as Supplier}
export async function assignSupplierManager(id:string,managerId:string|null,reason?:string){const{data,error}=await db().rpc("supplier_assign_manager_v1",{p_supplier_id:id,p_manager_id:managerId,p_reason:reason||null});if(error)throw error;return data as Supplier}
export async function rateSupplier(id:string,rating:number,reason?:string){const{data,error}=await db().rpc("supplier_set_rating_v1",{p_supplier_id:id,p_rating:rating,p_reason:reason||null});if(error)throw error;return data as Supplier}
export async function deleteSupplier(id:string,reason:string){const{error}=await db().rpc("supplier_delete_v1",{p_supplier_id:id,p_reason:reason});if(error)throw error}
