"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
const field="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500";
const money=(n:number,c:string)=>`${c} ${new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(n||0)}`;
const d=(days:number)=>new Date(Date.now()+days*86400000).toISOString().slice(0,10);
const empty={forecast_date:d(7),flow_type:"inflow",category:"other",description:"",currency:"AED",amount:0,probability:100,status:"planned",notes:""};
export function TreasuryForecast(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[msg,setMsg]=useState(""),[horizon,setHorizon]=useState(30),[currency,setCurrency]=useState("all"),[form,setForm]=useState<any|null>(null);
 const load=async()=>{setLoading(true);setMsg("");const s=createClient();const[a,i,p,fx,adj]=await Promise.all([
  s.from("treasury_accounts").select("*").eq("status","active"),
  s.from("invoices").select("*,customers(company_name),suppliers(company_name)").not("status","in",'(paid,cancelled)'),
  s.from("payments").select("*").not("status","in",'(completed,cancelled,failed)'),
  s.from("fx_settlements").select("*,fx_deals(deal_no,counterparty_name)").neq("status","completed"),
  s.from("treasury_forecast_adjustments").select("*").neq("status","cancelled").order("forecast_date")
 ]);for(const r of[a,i,p,fx,adj])if(r.error){setMsg(r.error.message);setLoading(false);return}setData({accounts:a.data??[],invoices:i.data??[],payments:p.data??[],fx:fx.data??[],adjustments:adj.data??[]});setLoading(false)};useEffect(()=>{void load()},[]);
 const events=useMemo(()=>{if(!data)return[];const out:any[]=[];for(const x of data.invoices){if(!x.due_date)continue;out.push({id:`inv-${x.id}`,date:x.due_date,type:x.invoice_type==="receivable"?"inflow":"outflow",source:"Invoice",ref:x.invoice_no,description:x.invoice_type==="receivable"?(x.customers?.company_name||"Customer receipt"):(x.suppliers?.company_name||"Supplier payment"),currency:x.currency,amount:Number(x.total_amount||0),probability:x.invoice_type==="receivable"?85:100,status:x.status})}for(const x of data.payments){const date=x.scheduled_date||x.payment_date;if(!date)continue;out.push({id:`pay-${x.id}`,date,type:x.payment_type==="receipt"?"inflow":"outflow",source:"Payment",ref:x.payment_no,description:x.beneficiary_name||x.purpose||"Scheduled payment",currency:x.currency,amount:Number(x.amount||0),probability:x.status==="approved"?100:80,status:x.status})}for(const x of data.fx){if(!x.settlement_date)continue;out.push({id:`fx-${x.id}`,date:x.settlement_date,type:x.settlement_type==="receipt"?"inflow":"outflow",source:"FX Settlement",ref:x.reference_no||x.fx_deals?.deal_no||"FX",description:x.fx_deals?.counterparty_name||x.bank_name||"FX settlement",currency:x.currency,amount:Number(x.amount||0),probability:x.status==="completed"?100:90,status:x.status})}for(const x of data.adjustments)out.push({id:`adj-${x.id}`,date:x.forecast_date,type:x.flow_type,source:"Manual",ref:x.category,description:x.description,currency:x.currency,amount:Number(x.amount||0),probability:Number(x.probability||100),status:x.status});return out},[data]);
 const currencies=useMemo(()=>Array.from(new Set([...(data?.accounts??[]).map((x:any)=>x.currency),...events.map(x=>x.currency)])).filter(Boolean).sort(),[data,events]);
 const filtered=useMemo(()=>events.filter(x=>x.date>=d(0)&&x.date<=d(horizon)&&(currency==="all"||x.currency===currency)).sort((a,b)=>a.date.localeCompare(b.date)),[events,horizon,currency]);
 const positions=useMemo(()=>{const cc=currency==="all"?currencies:[currency];return cc.map(c=>{const start=(data?.accounts??[]).filter((x:any)=>x.currency===c).reduce((n:number,x:any)=>n+Number(x.available_balance||0),0);const ev=filtered.filter(x=>x.currency===c);const inflow=ev.filter(x=>x.type==="inflow").reduce((n,x)=>n+x.amount,0),outflow=ev.filter(x=>x.type==="outflow").reduce((n,x)=>n+x.amount,0),weightedIn=ev.filter(x=>x.type==="inflow").reduce((n,x)=>n+x.amount*x.probability/100,0),weightedOut=ev.filter(x=>x.type==="outflow").reduce((n,x)=>n+x.amount*x.probability/100,0);return{currency:c,start,inflow,outflow,end:start+inflow-outflow,weightedEnd:start+weightedIn-weightedOut}})},[data,filtered,currency,currencies]);
 const saveAdjustment=async()=>{if(!form.description.trim()||Number(form.amount)<=0)return setMsg("Description and amount are required.");const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)return setMsg("Authentication required.");const{error}=await s.from("treasury_forecast_adjustments").insert({...form,amount:Number(form.amount),probability:Number(form.probability),created_by:user.id});if(error)return setMsg(error.message);setForm(null);await load()};
 if(loading)return <main className="p-8 text-white"><div className="rounded-2xl border border-slate-800 bg-[#0d1423] p-10 text-center text-slate-400">Loading cash forecast...</div></main>;
 return <main className="p-5 text-white md:p-8"><header className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.24em] text-blue-400">VTC Treasury</p><h1 className="mt-2 text-3xl font-bold">Cash Forecast & Liquidity Planning</h1><p className="mt-2 text-sm text-slate-400">Forward-looking cash visibility using bank balances, receivables, payables, scheduled payments, FX settlements and treasury adjustments.</p></div><div className="flex gap-2"><button onClick={()=>setForm({...empty})} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold">+ Forecast Adjustment</button><button onClick={()=>void load()} className="rounded-xl border border-slate-700 px-5 py-3 text-sm">Refresh</button></div></header>{msg&&<div className="mt-4 rounded-xl border border-slate-700 bg-slate-900/60 px-4 py-3 text-sm">{msg}</div>}
 <section className="mt-6 grid gap-3 md:grid-cols-[180px_180px_1fr]"><select className={field} value={horizon} onChange={e=>setHorizon(Number(e.target.value))}><option value={7}>Next 7 Days</option><option value={30}>Next 30 Days</option><option value={60}>Next 60 Days</option><option value={90}>Next 90 Days</option></select><select className={field} value={currency} onChange={e=>setCurrency(e.target.value)}><option value="all">All currencies</option>{currencies.map(c=><option key={c}>{c}</option>)}</select><div className="flex items-center text-xs text-slate-500">Forecast is kept by currency. No cross-currency conversion is applied.</div></section>
 <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{positions.map(p=><div key={p.currency} className={`rounded-2xl border p-5 ${p.weightedEnd<0?'border-red-900/60 bg-red-950/10':'border-slate-800 bg-[#0d1423]'}`}><div className="flex justify-between"><div><p className="text-xs uppercase tracking-wider text-slate-500">{p.currency} Liquidity</p><p className="mt-2 text-2xl font-bold">{money(p.weightedEnd,p.currency)}</p></div><span className="text-xs text-slate-500">Weighted</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><span className="text-slate-500">Opening</span><p className="mt-1 font-semibold">{money(p.start,p.currency)}</p></div><div><span className="text-slate-500">Closing</span><p className="mt-1 font-semibold">{money(p.end,p.currency)}</p></div><div><span className="text-slate-500">Inflows</span><p className="mt-1 font-semibold text-emerald-400">+ {money(p.inflow,p.currency)}</p></div><div><span className="text-slate-500">Outflows</span><p className="mt-1 font-semibold text-amber-300">- {money(p.outflow,p.currency)}</p></div></div></div>)}</section>
 <section className="mt-5 rounded-2xl border border-slate-800 bg-[#0d1423] p-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Liquidity Timeline</h3><p className="mt-1 text-xs text-slate-500">All forecast events within the selected horizon.</p></div><span className="text-xs text-slate-500">{filtered.length} events</span></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="text-left text-xs uppercase tracking-wider text-slate-500"><tr><th className="p-3">Date</th><th>Direction</th><th>Source</th><th>Reference</th><th>Description</th><th>Currency</th><th>Amount</th><th>Probability</th><th>Status</th></tr></thead><tbody>{filtered.length?filtered.map(x=><tr key={x.id} className="border-t border-slate-800"><td className="p-3">{x.date}</td><td className={x.type==="inflow"?'text-emerald-400':'text-amber-300'}>{x.type}</td><td>{x.source}</td><td>{x.ref||'-'}</td><td>{x.description}</td><td>{x.currency}</td><td>{money(x.amount,x.currency)}</td><td>{x.probability}%</td><td>{x.status}</td></tr>):<tr><td colSpan={9} className="p-10 text-center text-slate-500">No forecast events in this period.</td></tr>}</tbody></table></div></section>
 {form&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-5"><section className="w-full max-w-3xl rounded-3xl border border-slate-700 bg-[#0d1423] p-6"><div className="flex justify-between"><div><h3 className="text-xl font-semibold">Forecast Adjustment</h3><p className="mt-1 text-xs text-slate-500">Add a planned cash event not yet represented by an invoice, payment or FX settlement.</p></div><button onClick={()=>setForm(null)}>×</button></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><input type="date" className={field} value={form.forecast_date} onChange={e=>setForm({...form,forecast_date:e.target.value})}/><select className={field} value={form.flow_type} onChange={e=>setForm({...form,flow_type:e.target.value})}><option value="inflow">Inflow</option><option value="outflow">Outflow</option></select><input className={field} placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><input className={field} placeholder="Description *" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><select className={field} value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}>{["AED","USD","EUR","GBP","CNY","INR","IRR"].map(c=><option key={c}>{c}</option>)}</select><input type="number" min="0" className={field} placeholder="Amount *" value={form.amount} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/><input type="number" min="0" max="100" className={field} placeholder="Probability %" value={form.probability} onChange={e=>setForm({...form,probability:Number(e.target.value)})}/><select className={field} value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>planned</option><option>confirmed</option><option>cancelled</option></select></div><textarea className={`${field} mt-3 min-h-24`} placeholder="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setForm(null)} className="rounded-xl border border-slate-700 px-4 py-2">Cancel</button><button onClick={()=>void saveAdjustment()} className="rounded-xl bg-blue-600 px-5 py-2 font-semibold">Save Forecast Event</button></div></section></div>}</main>}
