"use client";

import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";

const field="rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500";
const money=(n:number,c="AED")=>`${c} ${new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(n||0)}`;
type Tab="queue"|"payments"|"fx"|"payables"|"history";

export function TreasuryApprovalCenter(){
 const[data,setData]=useState<any>({payments:[],fx:[],payables:[],generic:[],profiles:[],user:null,role:""}),[loading,setLoading]=useState(true),[msg,setMsg]=useState(""),[tab,setTab]=useState<Tab>("queue"),[search,setSearch]=useState("");
 const load=async()=>{setLoading(true);setMsg("");try{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user)throw new Error("Authentication required");const[p,fx,appr,inv,profile,profiles]=await Promise.all([
  s.from("payments").select("*,customers(company_name),suppliers(company_name),invoices(invoice_no)").order("created_at",{ascending:false}),
  s.from("fx_approvals").select("*,fx_deals(*),profiles:approver_id(full_name)").order("created_at",{ascending:false}),
  s.from("approvals").select("*,requester:requested_by(full_name),approver:approver_id(full_name)").order("requested_at",{ascending:false}),
  s.from("invoices").select("*,suppliers(company_name),customers(company_name),finance_owner:finance_owner_id(full_name),approved_user:approved_by(full_name)").eq("invoice_type","payable").order("due_date",{ascending:true}),
  s.from("profiles").select("id,full_name,role,active").eq("id",user.id).single(),
  s.from("profiles").select("id,full_name,role,active").eq("active",true).order("full_name")
 ]);for(const r of[p,fx,appr,inv,profile,profiles])if(r.error)throw r.error;setData({payments:p.data??[],fx:fx.data??[],generic:appr.data??[],payables:inv.data??[],profiles:profiles.data??[],user,role:profile.data?.role??""})}catch(e:any){setMsg(e.message||"Unable to load approval center")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const canApprove=["admin","ceo","manager","finance"].includes(data.role);
 const pendingPayments=data.payments.filter((x:any)=>x.approval_required!==false&&!["approved","rejected"].includes(x.approval_status||"pending")&&!["completed","cancelled"].includes(x.status));
 const pendingFx=data.fx.filter((x:any)=>x.status==="pending");
 const pendingPayables=data.payables.filter((x:any)=>!["paid","cancelled"].includes(x.status)&&["pending","required","pending_approval"].includes(x.approval_status||"not_required"));
 const genericPending=data.generic.filter((x:any)=>x.status==="pending");
 const allQueue=useMemo(()=>[
  ...pendingPayments.map((x:any)=>({kind:"payment",id:x.id,ref:x.payment_no,title:x.beneficiary_name||x.suppliers?.company_name||x.customers?.company_name||"Payment",amount:Number(x.amount||0),currency:x.currency,priority:x.priority||"normal",date:x.scheduled_date||x.payment_date||x.created_at,status:x.approval_status||"pending",raw:x})),
  ...pendingFx.map((x:any)=>({kind:"fx",id:x.id,ref:x.fx_deals?.deal_no||"FX",title:x.fx_deals?.counterparty_name||"FX Deal",amount:Number(x.fx_deals?.base_amount||0),currency:x.fx_deals?.base_currency||"",priority:x.approval_level>1?"high":"normal",date:x.created_at,status:x.status,raw:x})),
  ...pendingPayables.map((x:any)=>({kind:"payable",id:x.id,ref:x.invoice_no,title:x.suppliers?.company_name||"Supplier Payable",amount:Number(x.total_amount||0),currency:x.currency,priority:x.payment_priority||"normal",date:x.scheduled_payment_date||x.due_date||x.issue_date,status:x.approval_status||"pending",raw:x})),
  ...genericPending.filter((x:any)=>["payment","treasury","finance"].includes(x.approval_type)||["payment","invoice","fx_deal"].includes(x.entity_type)).map((x:any)=>({kind:"generic",id:x.id,ref:x.entity_type,title:x.approval_type,amount:0,currency:"",priority:"normal",date:x.requested_at,status:x.status,raw:x}))
 ].sort((a,b)=>priorityRank(b.priority)-priorityRank(a.priority)||String(a.date||"").localeCompare(String(b.date||""))),[data]);
 const stats={pending:allQueue.length,payments:pendingPayments.length,fx:pendingFx.length,payables:pendingPayables.length,critical:allQueue.filter(x=>["critical","high"].includes(x.priority)).length,history:data.generic.filter((x:any)=>x.status!=="pending").length+data.fx.filter((x:any)=>x.status!=="pending").length};
 const decidePayment=async(x:any,approved:boolean)=>{if(!canApprove)return setMsg("Your role cannot approve treasury transactions.");const comments=prompt(approved?"Approval comments (optional)":"Rejection reason")??"";const s=createClient();const patch:any={approval_status:approved?"approved":"rejected",approved_by:approved?data.user.id:null,updated_at:new Date().toISOString()};if(approved&&x.compliance_status==="cleared")patch.status="approved";if(!approved)patch.status="cancelled";const{error}=await s.from("payments").update(patch).eq("id",x.id);if(error)return setMsg(error.message);await s.from("payment_events").insert({payment_id:x.id,event_type:approved?"approval_granted":"approval_rejected",status_from:x.status,status_to:patch.status??x.status,notes:comments||null,created_by:data.user.id});setMsg(approved?"Payment approved.":"Payment rejected.");await load()};
 const decideFx=async(a:any,approved:boolean)=>{if(!canApprove)return setMsg("Your role cannot approve treasury transactions.");const comments=prompt(approved?"Approval comments (optional)":"Rejection reason")??"";const s=createClient();const now=new Date().toISOString();const{error}=await s.from("fx_approvals").update({status:approved?"approved":"rejected",comments:comments||null,approver_id:data.user.id,decided_at:now}).eq("id",a.id);if(error)return setMsg(error.message);await s.from("fx_deals").update({status:approved?"approved":"cancelled",approved_by:approved?data.user.id:null,updated_at:now}).eq("id",a.fx_deal_id);setMsg(approved?"FX deal approved.":"FX deal rejected.");await load()};
 const decidePayable=async(x:any,approved:boolean)=>{if(!canApprove)return setMsg("Your role cannot approve treasury transactions.");const comments=prompt(approved?"Approval comments (optional)":"Rejection reason")??"";const s=createClient();const{error}=await s.from("invoices").update({approval_status:approved?"approved":"rejected",approved_by:approved?data.user.id:null,approved_at:approved?new Date().toISOString():null,payment_hold:!approved,updated_at:new Date().toISOString()}).eq("id",x.id);if(error)return setMsg(error.message);await s.from("payable_activities").insert({invoice_id:x.id,activity_type:approved?"approval_granted":"approval_rejected",channel:"system",notes:comments||null,outcome:approved?"approved":"rejected",created_by:data.user.id});setMsg(approved?"Payable approved for payment planning.":"Payable rejected / placed on hold.");await load()};
 const decideGeneric=async(a:any,approved:boolean)=>{if(!canApprove)return setMsg("Your role cannot approve treasury transactions.");const comments=prompt(approved?"Approval comments (optional)":"Rejection reason")??"";const s=createClient();const{error}=await s.from("approvals").update({status:approved?"approved":"rejected",comments:comments||null,approver_id:data.user.id,decided_at:new Date().toISOString()}).eq("id",a.id);if(error)return setMsg(error.message);setMsg(approved?"Approval completed.":"Approval rejected.");await load()};
 const decide=(item:any,approved:boolean)=>item.kind==="payment"?decidePayment(item.raw,approved):item.kind==="fx"?decideFx(item.raw,approved):item.kind==="payable"?decidePayable(item.raw,approved):decideGeneric(item.raw,approved);
 if(loading)return <main className="p-8 text-white"><div className="rounded-2xl border border-slate-800 bg-[#0d1423] p-10 text-center text-slate-400">Loading Treasury Approval Center...</div></main>;
 return <main className="p-5 text-white md:p-8"><header className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.24em] text-blue-400">VTC Treasury Governance</p><h1 className="mt-2 text-3xl font-bold">Treasury Approval Center</h1><p className="mt-2 text-sm text-slate-400">One decision queue for payments, FX transactions and supplier payables with accountable approval history.</p></div><div className="flex gap-2"><span className={`rounded-xl border px-4 py-3 text-xs ${canApprove?'border-emerald-900 text-emerald-300':'border-amber-900 text-amber-300'}`}>{canApprove?`Approval Role · ${data.role}`:`View Only · ${data.role}`}</span><button onClick={()=>void load()} className="rounded-xl border border-slate-700 px-4 py-3 text-sm">Refresh</button></div></header>{msg&&<div className="mt-4 rounded-xl border border-slate-700 bg-slate-900/60 px-4 py-3 text-sm">{msg}</div>}
 <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><K label="Pending Decisions" value={String(stats.pending)} risk={stats.pending>0}/><K label="Payments" value={String(stats.payments)}/><K label="FX" value={String(stats.fx)}/><K label="Payables" value={String(stats.payables)}/><K label="High / Critical" value={String(stats.critical)} risk={stats.critical>0}/><K label="Decision History" value={String(stats.history)}/></section>
 <div className="mt-6 flex flex-wrap gap-2">{([['queue','Decision Queue'],['payments','Payments'],['fx','FX'],['payables','Payables'],['history','History']] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`rounded-xl px-4 py-2 text-sm ${tab===k?'bg-blue-600':'bg-slate-900 text-slate-300'}`}>{l}</button>)}</div>
 {tab!=="history"&&<section className="mt-5 rounded-2xl border border-slate-800 bg-[#0d1423]"><div className="border-b border-slate-800 p-4"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search reference, counterparty, type or amount..." className={`${field} w-full max-w-2xl`}/></div><Queue rows={allQueue.filter(x=>(tab==="queue"||x.kind===tab.slice(0,-1)||tab==="payables"&&x.kind==="payable")&&`${x.ref} ${x.title} ${x.kind} ${x.amount}`.toLowerCase().includes(search.toLowerCase()))} canApprove={canApprove} decide={decide}/></section>}
 {tab==="history"&&<History generic={data.generic} fx={data.fx}/>}</main>;
}
function Queue({rows,canApprove,decide}:{rows:any[],canApprove:boolean,decide:(x:any,a:boolean)=>void}){return <div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="text-left text-xs uppercase tracking-wider text-slate-500"><tr><th className="p-4">Type / Reference</th><th>Counterparty</th><th>Amount</th><th>Priority</th><th>Requested / Due</th><th>Status</th><th className="p-4 text-right">Decision</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={`${x.kind}-${x.id}`} className="border-t border-slate-800"><td className="p-4"><span className="rounded-full bg-blue-500/10 px-2 py-1 text-[10px] font-bold uppercase text-blue-300">{x.kind}</span><p className="mt-2 font-semibold">{x.ref}</p></td><td>{x.title}</td><td>{x.amount?money(x.amount,x.currency):'-'}</td><td><span className={`rounded-full px-2 py-1 text-xs ${['critical','high'].includes(x.priority)?'bg-red-500/10 text-red-300':'bg-slate-800 text-slate-300'}`}>{x.priority}</span></td><td>{x.date?new Date(x.date).toLocaleDateString('en-GB'):'-'}</td><td>{x.status}</td><td className="p-4"><div className="flex justify-end gap-2"><button disabled={!canApprove} onClick={()=>void decide(x,false)} className="rounded-lg border border-red-900 px-3 py-2 text-xs text-red-300 disabled:opacity-40">Reject</button><button disabled={!canApprove} onClick={()=>void decide(x,true)} className="rounded-lg border border-emerald-800 px-3 py-2 text-xs text-emerald-300 disabled:opacity-40">Approve</button></div></td></tr>):<tr><td colSpan={7} className="p-10 text-center text-slate-500">No pending decisions in this queue.</td></tr>}</tbody></table></div>}
function History({generic,fx}:{generic:any[],fx:any[]}){const rows=[...generic.filter(x=>x.status!=="pending").map(x=>({type:x.approval_type,ref:x.entity_type,status:x.status,who:x.approver?.full_name||'-',when:x.decided_at,comments:x.comments})),...fx.filter(x=>x.status!=="pending").map(x=>({type:"FX",ref:x.fx_deals?.deal_no||'-',status:x.status,who:x.profiles?.full_name||'-',when:x.decided_at,comments:x.comments}))].sort((a,b)=>String(b.when||"").localeCompare(String(a.when||"")));return <section className="mt-5 rounded-2xl border border-slate-800 bg-[#0d1423]"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Type</th><th>Reference</th><th>Status</th><th>Approver</th><th>Decision Time</th><th className="p-4">Comments</th></tr></thead><tbody>{rows.length?rows.map((x,i)=><tr key={i} className="border-t border-slate-800"><td className="p-4">{x.type}</td><td>{x.ref}</td><td className={x.status==='approved'?'text-emerald-400':'text-red-300'}>{x.status}</td><td>{x.who}</td><td>{x.when?new Date(x.when).toLocaleString('en-GB'):'-'}</td><td className="p-4 text-slate-400">{x.comments||'-'}</td></tr>):<tr><td colSpan={6} className="p-10 text-center text-slate-500">No completed approval decisions yet.</td></tr>}</tbody></table></div></section>}
function priorityRank(v:string){return v==="critical"?4:v==="high"?3:v==="normal"?2:1}
function K({label,value,risk=false}:{label:string,value:string,risk?:boolean}){return <div className={`rounded-2xl border p-4 ${risk?'border-amber-900/60 bg-amber-950/10':'border-slate-800 bg-[#0d1423]'}`}><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p><p className={`mt-2 text-2xl font-bold ${risk?'text-amber-300':''}`}>{value}</p></div>}
