-- Shipping controlled status transitions and document gates.
create table if not exists public.shipment_status_events (
  id uuid primary key default gen_random_uuid(), shipment_id uuid not null references public.shipments(id) on delete cascade,
  from_status text, to_status text not null, gate text, readiness_percent integer, override_used boolean not null default false,
  reason text, performed_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now()
);
alter table public.shipment_status_events enable row level security;
drop policy if exists shipment_status_events_read on public.shipment_status_events;
create policy shipment_status_events_read on public.shipment_status_events for select to authenticated using (true);

create or replace function public.shipping_current_role() returns text language sql stable security definer set search_path=public as $$ select coalesce((select role::text from public.profiles where id=auth.uid()),'dealer') $$;
create or replace function public.shipping_can_write() returns boolean language sql stable security definer set search_path=public as $$ select public.shipping_current_role() in ('admin','ceo','manager','dealer') $$;
create or replace function public.shipping_can_override() returns boolean language sql stable security definer set search_path=public as $$ select public.shipping_current_role() in ('admin','ceo','manager') $$;
revoke all on function public.shipping_current_role() from public,anon; revoke all on function public.shipping_can_write() from public,anon; revoke all on function public.shipping_can_override() from public,anon;
grant execute on function public.shipping_current_role() to authenticated,service_role; grant execute on function public.shipping_can_write() to authenticated,service_role; grant execute on function public.shipping_can_override() to authenticated,service_role;

update public.document_requirement_rules set gate='customs',updated_at=now() where entity_type='shipment' and document_type in ('Bill of Lading','Air Waybill') and gate='dispatch';
insert into public.document_requirement_rules(entity_type,document_type,gate,modes,sort_order,notes) select 'shipment','Booking Confirmation','booking',array['sea','air','courier','multimodal']::text[],5,'Booking evidence required before moving a planned shipment to booked status.' where not exists(select 1 from public.document_requirement_rules where entity_type='shipment' and document_type='Booking Confirmation' and gate='booking');
insert into public.document_requirement_rules(entity_type,document_type,gate,modes,sort_order,notes) select 'shipment','CMR / Road Waybill','customs',array['road']::text[],35,'Road transport document required for customs readiness.' where not exists(select 1 from public.document_requirement_rules where entity_type='shipment' and document_type='CMR / Road Waybill' and gate='customs');
insert into public.document_requirement_rules(entity_type,document_type,gate,modes,sort_order,notes) select 'shipment','Rail Waybill','customs',array['rail']::text[],35,'Rail transport document required for customs readiness.' where not exists(select 1 from public.document_requirement_rules where entity_type='shipment' and document_type='Rail Waybill' and gate='customs');
insert into public.document_requirement_rules(entity_type,document_type,gate,modes,requires_temperature_controlled,sort_order,notes) select 'shipment','Temperature Control Instructions','dispatch','{}'::text[],true,25,'Temperature handling instructions required before controlled cargo dispatch.' where not exists(select 1 from public.document_requirement_rules where entity_type='shipment' and document_type='Temperature Control Instructions' and gate='dispatch');
insert into public.document_requirement_rules(entity_type,document_type,gate,modes,sort_order,notes) select 'shipment','Delivery Order','delivery','{}'::text[],90,'Delivery release document required before marking a shipment delivered.' where not exists(select 1 from public.document_requirement_rules where entity_type='shipment' and document_type='Delivery Order' and gate='delivery');

create or replace function public.shipment_transition_gate(p_to_status text) returns text language sql immutable as $$ select case p_to_status when 'booked' then 'booking' when 'picked_up' then 'dispatch' when 'in_transit' then 'dispatch' when 'customs' then 'customs' when 'delivered' then 'delivery' else null end $$;
create or replace function public.shipping_gate_readiness_v1(p_shipment_id uuid,p_gate text) returns jsonb language plpgsql stable security definer set search_path=public as $$ declare r jsonb;items jsonb;total int;ready int;blocked int; begin if auth.uid() is null then raise exception 'Authentication required'; end if; r:=public.document_readiness_v1('shipment',p_shipment_id); select coalesce(jsonb_agg(x),'[]'::jsonb),count(*),count(*) filter(where x->>'state'='ready'),count(*) filter(where x->>'state'<>'ready') into items,total,ready,blocked from jsonb_array_elements(coalesce(r->'items','[]'::jsonb)) x where x->>'gate'=p_gate; return jsonb_build_object('shipment_id',p_shipment_id,'gate',p_gate,'required_count',coalesce(total,0),'ready_count',coalesce(ready,0),'blocked_count',coalesce(blocked,0),'completion_percent',case when coalesce(total,0)=0 then 100 else round(100.0*ready/total)::int end,'gate_status',case when coalesce(blocked,0)=0 then 'ready' else 'blocked' end,'items',coalesce(items,'[]'::jsonb)); end $$;
revoke all on function public.shipping_gate_readiness_v1(uuid,text) from public,anon; grant execute on function public.shipping_gate_readiness_v1(uuid,text) to authenticated,service_role;

-- Transition implementation is superseded by v21 below; retained in history for parity with production migration sequence.
create or replace function public.shipment_status_hard_lock_v1() returns trigger language plpgsql as $$ begin if new.status is distinct from old.status and coalesce(current_setting('vtc.shipping_transition',true),'0')<>'1' then raise exception 'Direct shipment status changes are disabled. Use controlled shipment transition.'; end if; return new; end $$;
drop trigger if exists trg_shipment_status_hard_lock on public.shipments; create trigger trg_shipment_status_hard_lock before update on public.shipments for each row execute function public.shipment_status_hard_lock_v1();
create index if not exists shipment_status_events_shipment_created_idx on public.shipment_status_events(shipment_id,created_at desc);
