-- Finance Control Center v45
-- Controlled payments, invoice workflow, maker-checker approvals, finance audit and scoped RLS.

create table if not exists public.finance_events (
  id uuid primary key default gen_random_uuid(), entity_type text not null check (entity_type in ('invoice','payment')), entity_id uuid not null,
  event_type text not null, from_status text, to_status text, reason text, metadata jsonb not null default '{}'::jsonb,
  performed_by uuid references public.profiles(id), created_at timestamptz not null default now()
);
create index if not exists finance_events_entity_idx on public.finance_events(entity_type,entity_id,created_at desc);
alter table public.finance_events enable row level security;

create or replace function public.finance_current_role() returns text language sql security definer set search_path=public as $$ select coalesce((select lower(role::text) from public.profiles where id=auth.uid() and active=true limit 1),'unknown') $$;
create or replace function public.finance_can_write() returns boolean language sql security definer set search_path=public as $$ select public.finance_current_role() in ('admin','ceo','manager','finance') $$;
create or replace function public.finance_can_approve() returns boolean language sql security definer set search_path=public as $$ select public.finance_current_role() in ('admin','ceo','manager') $$;
revoke all on function public.finance_current_role() from public,anon; revoke all on function public.finance_can_write() from public,anon; revoke all on function public.finance_can_approve() from public,anon;
grant execute on function public.finance_current_role(),public.finance_can_write(),public.finance_can_approve() to authenticated;

create or replace function public.payment_status_guard_v1() returns trigger language plpgsql set search_path=public as $$ begin if tg_op='UPDATE' and new.status is distinct from old.status and current_user not in ('postgres','service_role') then raise exception 'Payment status is controlled by Finance Workflow.'; end if; if tg_op='INSERT' and current_user not in ('postgres','service_role') then new.status:='pending'; new.approved_by:=null; end if; return new; end $$;
drop trigger if exists trg_payment_status_guard_v1 on public.payments; create trigger trg_payment_status_guard_v1 before insert or update on public.payments for each row execute function public.payment_status_guard_v1();
create or replace function public.invoice_status_guard_v1() returns trigger language plpgsql set search_path=public as $$ begin if tg_op='UPDATE' and new.status is distinct from old.status and current_user not in ('postgres','service_role') then raise exception 'Invoice status is controlled by Finance Workflow.'; end if; return new; end $$;
drop trigger if exists trg_invoice_status_guard_v1 on public.invoices; create trigger trg_invoice_status_guard_v1 before update on public.invoices for each row execute function public.invoice_status_guard_v1();

create or replace function public.finance_create_payment_v1(p_payload jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid(); v_role text:=public.finance_current_role(); v public.payments%rowtype; v_no text;
begin
 if v_user is null or v_role not in ('admin','ceo','manager','finance') then raise exception 'Finance write access required.'; end if;
 if coalesce((p_payload->>'amount')::numeric,0)<=0 then raise exception 'Payment amount must be greater than zero.'; end if;
 if coalesce(p_payload->>'payment_type','') not in ('receipt','payment') then raise exception 'Payment type must be receipt or payment.'; end if;
 if nullif(p_payload->>'invoice_id','') is not null and not exists(select 1 from public.invoices where id=(p_payload->>'invoice_id')::uuid) then raise exception 'Invoice not found.'; end if;
 v_no:=coalesce(nullif(btrim(p_payload->>'payment_no'),''),'PAY-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS'));
 insert into public.payments(payment_no,invoice_id,deal_id,payment_type,currency,amount,payment_date,method,bank_name,reference_no,status,notes,created_by,supplier_id,customer_id,beneficiary_name,beneficiary_country,beneficiary_bank,beneficiary_iban,beneficiary_account_no,beneficiary_swift,intermediary_bank,source_account,purpose,priority,approval_required,approval_status,compliance_status,scheduled_date,bank_fee,fx_rate,instruction_reference)
 values(v_no,nullif(p_payload->>'invoice_id','')::uuid,nullif(p_payload->>'deal_id','')::uuid,p_payload->>'payment_type',coalesce(nullif(p_payload->>'currency',''),'AED'),(p_payload->>'amount')::numeric,coalesce(nullif(p_payload->>'payment_date','')::date,current_date),nullif(p_payload->>'method',''),nullif(p_payload->>'bank_name',''),nullif(p_payload->>'reference_no',''),'pending',nullif(p_payload->>'notes',''),v_user,nullif(p_payload->>'supplier_id','')::uuid,nullif(p_payload->>'customer_id','')::uuid,nullif(p_payload->>'beneficiary_name',''),nullif(p_payload->>'beneficiary_country',''),nullif(p_payload->>'beneficiary_bank',''),nullif(p_payload->>'beneficiary_iban',''),nullif(p_payload->>'beneficiary_account_no',''),nullif(p_payload->>'beneficiary_swift',''),nullif(p_payload->>'intermediary_bank',''),nullif(p_payload->>'source_account',''),nullif(p_payload->>'purpose',''),coalesce(nullif(p_payload->>'priority',''),'normal'),true,'pending',coalesce(nullif(p_payload->>'compliance_status',''),'pending'),nullif(p_payload->>'scheduled_date','')::date,coalesce(nullif(p_payload->>'bank_fee','')::numeric,0),nullif(p_payload->>'fx_rate','')::numeric,nullif(p_payload->>'instruction_reference','')) returning * into v;
 insert into public.finance_events(entity_type,entity_id,event_type,to_status,metadata,performed_by) values('payment',v.id,'payment_created','pending',jsonb_build_object('payment_no',v.payment_no,'amount',v.amount,'currency',v.currency,'type',v.payment_type),v_user);
 return to_jsonb(v);
end $$;

create or replace function public.finance_approve_payment_v1(p_payment_id uuid,p_comments text default null) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_user uuid:=auth.uid(); v public.payments%rowtype; begin if v_user is null or not public.finance_can_approve() then raise exception 'Manager approval required.'; end if; select * into v from public.payments where id=p_payment_id for update; if not found then raise exception 'Payment not found.'; end if; if v.status<>'pending' then raise exception 'Only pending payments can be approved.'; end if; if v.created_by=v_user and public.finance_current_role()='manager' then raise exception 'Maker-checker rule: creator cannot approve their own payment.'; end if; update public.payments set status='approved',approval_status='approved',approved_by=v_user,updated_at=now() where id=p_payment_id returning * into v; insert into public.finance_events(entity_type,entity_id,event_type,from_status,to_status,reason,performed_by) values('payment',v.id,'payment_approved','pending','approved',nullif(btrim(p_comments),''),v_user); return to_jsonb(v); end $$;
create or replace function public.finance_settle_payment_v1(p_payment_id uuid,p_outcome text,p_reference text default null,p_reason text default null) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_user uuid:=auth.uid(); v_role text:=public.finance_current_role(); v public.payments%rowtype; begin if v_user is null or v_role not in ('admin','ceo','manager','finance') then raise exception 'Finance write access required.'; end if; if p_outcome not in ('completed','failed') then raise exception 'Outcome must be completed or failed.'; end if; select * into v from public.payments where id=p_payment_id for update; if not found then raise exception 'Payment not found.'; end if; if v.status<>'approved' then raise exception 'Only approved payments can be settled.'; end if; if p_outcome='failed' and length(btrim(coalesce(p_reason,'')))<5 then raise exception 'Failure reason is required.'; end if; update public.payments set status=p_outcome,reference_no=coalesce(nullif(btrim(p_reference),''),reference_no),executed_at=case when p_outcome='completed' then now() else executed_at end,settlement_status=case when p_outcome='completed' then 'settled' else 'failed' end,failure_reason=case when p_outcome='failed' then btrim(p_reason) else null end,updated_at=now() where id=p_payment_id returning * into v; insert into public.finance_events(entity_type,entity_id,event_type,from_status,to_status,reason,performed_by) values('payment',v.id,'payment_'||p_outcome,'approved',p_outcome,nullif(btrim(p_reason),''),v_user); return to_jsonb(v); end $$;
create or replace function public.finance_cancel_payment_v1(p_payment_id uuid,p_reason text) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_user uuid:=auth.uid(); v_role text:=public.finance_current_role(); v public.payments%rowtype; v_from text; begin if v_user is null or v_role not in ('admin','ceo','manager','finance') then raise exception 'Finance write access required.'; end if; if length(btrim(coalesce(p_reason,'')))<5 then raise exception 'Cancellation reason is required.'; end if; select * into v from public.payments where id=p_payment_id for update; if not found then raise exception 'Payment not found.'; end if; if v.status not in ('pending','approved') then raise exception 'Only pending or approved payments can be cancelled.'; end if; v_from:=v.status; update public.payments set status='cancelled',approval_status='cancelled',failure_reason=btrim(p_reason),updated_at=now() where id=p_payment_id returning * into v; insert into public.finance_events(entity_type,entity_id,event_type,from_status,to_status,reason,performed_by) values('payment',v.id,'payment_cancelled',v_from,'cancelled',btrim(p_reason),v_user); return to_jsonb(v); end $$;

create or replace function public.finance_issue_invoice_v1(p_invoice_id uuid,p_due_date date default null) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_user uuid:=auth.uid(); v_role text:=public.finance_current_role(); v public.invoices%rowtype; begin if v_user is null or v_role not in ('admin','ceo','manager','finance') then raise exception 'Finance write access required.'; end if; select * into v from public.invoices where id=p_invoice_id for update; if not found then raise exception 'Invoice not found.'; end if; if v.status<>'draft' then raise exception 'Only draft invoices can be issued.'; end if; if coalesce(v.total_amount,0)<=0 then raise exception 'Invoice total must be greater than zero.'; end if; if v.invoice_type='receivable' and v.customer_id is null then raise exception 'Receivable invoice requires a customer.'; end if; if v.invoice_type='payable' and v.supplier_id is null then raise exception 'Payable invoice requires a supplier.'; end if; update public.invoices set status='issued',issue_date=current_date,due_date=coalesce(p_due_date,due_date,current_date+30),updated_at=now() where id=p_invoice_id returning * into v; insert into public.finance_events(entity_type,entity_id,event_type,from_status,to_status,performed_by) values('invoice',v.id,'invoice_issued','draft','issued',v_user); return to_jsonb(v); end $$;
create or replace function public.finance_set_invoice_dispute_v1(p_invoice_id uuid,p_status text,p_reason text default null) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_user uuid:=auth.uid(); v_role text:=public.finance_current_role(); v public.invoices%rowtype; begin if v_user is null or v_role not in ('admin','ceo','manager','finance') then raise exception 'Finance write access required.'; end if; if p_status not in ('clear','disputed','resolved') then raise exception 'Invalid dispute status.'; end if; if p_status='disputed' and length(btrim(coalesce(p_reason,'')))<5 then raise exception 'Dispute reason is required.'; end if; select * into v from public.invoices where id=p_invoice_id for update; if not found then raise exception 'Invoice not found.'; end if; update public.invoices set dispute_status=p_status,dispute_reason=case when p_status='clear' then null else nullif(btrim(p_reason),'') end,credit_hold=(p_status='disputed'),updated_at=now() where id=p_invoice_id returning * into v; insert into public.finance_events(entity_type,entity_id,event_type,reason,performed_by) values('invoice',v.id,'invoice_dispute_'||p_status,nullif(btrim(p_reason),''),v_user); return to_jsonb(v); end $$;
create or replace function public.finance_set_collection_v1(p_invoice_id uuid,p_collection_status text,p_owner_id uuid default null,p_promised_date date default null,p_next_follow_up timestamptz default null,p_notes text default null) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_user uuid:=auth.uid(); v_role text:=public.finance_current_role(); v public.invoices%rowtype; begin if v_user is null or v_role not in ('admin','ceo','manager','finance') then raise exception 'Finance write access required.'; end if; if p_collection_status not in ('open','contacted','promised','escalated','closed') then raise exception 'Invalid collection status.'; end if; select * into v from public.invoices where id=p_invoice_id for update; if not found then raise exception 'Invoice not found.'; end if; if v.invoice_type<>'receivable' then raise exception 'Collection workflow applies only to receivables.'; end if; update public.invoices set collection_status=p_collection_status,collection_owner_id=coalesce(p_owner_id,collection_owner_id,v_user),promised_payment_date=p_promised_date,last_follow_up_at=now(),next_follow_up_at=p_next_follow_up,notes=case when nullif(btrim(p_notes),'') is null then notes else concat_ws(E'\n',notes,'Collection: '||btrim(p_notes)) end,updated_at=now() where id=p_invoice_id returning * into v; insert into public.finance_events(entity_type,entity_id,event_type,reason,performed_by) values('invoice',v.id,'collection_'||p_collection_status,nullif(btrim(p_notes),''),v_user); return to_jsonb(v); end $$;
create or replace function public.finance_cancel_invoice_v1(p_invoice_id uuid,p_reason text) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_user uuid:=auth.uid(); v_role text:=public.finance_current_role(); v public.invoices%rowtype; v_from text; begin if v_user is null or v_role not in ('admin','ceo','manager') then raise exception 'Manager approval required to cancel an invoice.'; end if; if length(btrim(coalesce(p_reason,'')))<5 then raise exception 'Cancellation reason is required.'; end if; select * into v from public.invoices where id=p_invoice_id for update; if not found then raise exception 'Invoice not found.'; end if; if v.status in ('paid','cancelled') then raise exception 'Paid or cancelled invoice cannot be cancelled.'; end if; if exists(select 1 from public.payments p where p.invoice_id=v.id and p.status='completed') then raise exception 'Invoice with completed payments cannot be cancelled.'; end if; v_from:=v.status; update public.invoices set status='cancelled',collection_status='closed',payment_hold=true,notes=concat_ws(E'\n',notes,'Cancelled: '||btrim(p_reason)),updated_at=now() where id=p_invoice_id returning * into v; insert into public.finance_events(entity_type,entity_id,event_type,from_status,to_status,reason,performed_by) values('invoice',v.id,'invoice_cancelled',v_from,'cancelled',btrim(p_reason),v_user); return to_jsonb(v); end $$;

create or replace function public.finance_snapshot_v1() returns jsonb language plpgsql security definer set search_path=public as $$ begin if auth.uid() is null or public.finance_current_role() not in ('admin','ceo','manager','finance') then raise exception 'Finance access required.'; end if; return jsonb_build_object('role',public.finance_current_role(),'can_write',public.finance_can_write(),'can_approve',public.finance_can_approve(),'receivables',coalesce((select jsonb_agg(to_jsonb(x)) from (select i.*,c.company_name customer_name,d.deal_no from public.invoices i left join public.customers c on c.id=i.customer_id left join public.deals d on d.id=i.deal_id where i.invoice_type='receivable' order by i.due_date nulls last)x),'[]'::jsonb),'payables',coalesce((select jsonb_agg(to_jsonb(x)) from (select i.*,s.company_name supplier_name,d.deal_no from public.invoices i left join public.suppliers s on s.id=i.supplier_id left join public.deals d on d.id=i.deal_id where i.invoice_type='payable' order by i.due_date nulls last)x),'[]'::jsonb),'payments',coalesce((select jsonb_agg(to_jsonb(p) order by p.created_at desc) from public.payments p),'[]'::jsonb),'events',coalesce((select jsonb_agg(to_jsonb(e) order by e.created_at desc) from public.finance_events e),'[]'::jsonb)); end $$;

revoke all on function public.finance_create_payment_v1(jsonb),public.finance_approve_payment_v1(uuid,text),public.finance_settle_payment_v1(uuid,text,text,text),public.finance_cancel_payment_v1(uuid,text),public.finance_issue_invoice_v1(uuid,date),public.finance_set_invoice_dispute_v1(uuid,text,text),public.finance_set_collection_v1(uuid,text,uuid,date,timestamptz,text),public.finance_cancel_invoice_v1(uuid,text),public.finance_snapshot_v1() from public,anon;
grant execute on function public.finance_create_payment_v1(jsonb),public.finance_approve_payment_v1(uuid,text),public.finance_settle_payment_v1(uuid,text,text,text),public.finance_cancel_payment_v1(uuid,text),public.finance_issue_invoice_v1(uuid,date),public.finance_set_invoice_dispute_v1(uuid,text,text),public.finance_set_collection_v1(uuid,text,uuid,date,timestamptz,text),public.finance_cancel_invoice_v1(uuid,text),public.finance_snapshot_v1() to authenticated;

drop policy if exists authenticated_insert on public.payments; drop policy if exists authenticated_update on public.payments; drop policy if exists authenticated_select on public.payments; drop policy if exists manager_delete on public.payments;
create policy payments_read_roles on public.payments for select to authenticated using (public.finance_current_role() in ('admin','ceo','manager','finance') or (public.finance_current_role()='dealer' and (deal_id in (select d.id from public.deals d where d.dealer_id=auth.uid()) or created_by=auth.uid())) or (public.finance_current_role() in ('operations','logistics') and deal_id is not null));
create policy payments_insert_finance on public.payments for insert to authenticated with check (public.finance_can_write()); create policy payments_update_finance on public.payments for update to authenticated using (public.finance_can_write()) with check (public.finance_can_write()); create policy payments_delete_control on public.payments for delete to authenticated using (public.finance_current_role() in ('admin','ceo'));
drop policy if exists authenticated_select on public.invoices; create policy invoices_read_roles on public.invoices for select to authenticated using (public.finance_current_role() in ('admin','ceo','manager','finance') or (public.finance_current_role()='dealer' and deal_id in (select d.id from public.deals d where d.dealer_id=auth.uid())) or (public.finance_current_role() in ('operations','logistics') and shipment_id is not null));
create policy finance_events_read on public.finance_events for select to authenticated using (public.finance_current_role() in ('admin','ceo','manager','finance'));
